// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxString } from "./wxString_gen.ts";

// --- Helper: create a wxString from a JS string ---
export function createWxString(s: string): wxString
{
    const buf = new TextEncoder().encode(s + "\0");
    const ptr = Deno.UnsafePointer.of(buf);
    const result = wxString.CreateUTF8(ptr);
    if (!result)
    {
        throw new Error(`Failed to create wxString for: ${s}`);
    }
    return result;
}

// --- Helper: read a JS string from a wxString* ---
export function readWxString(wxStrPtr: Deno.PointerValue): string
{
    const buf = lib.symbols.kwxUtf8Buffer_Create(wxStrPtr);
    const data = lib.symbols.kwxUtf8Buffer_Data(buf);
    const result = data ? Deno.UnsafePointerView.getCString(data) : "";
    lib.symbols.kwxUtf8Buffer_Delete(buf);
    return result;
}

// --- Helper: read and delete a wxString* returned from a getter ---
export function readAndDeleteWxString(wxStrPtr: Deno.PointerValue): string
{
    const result = readWxString(wxStrPtr);
    lib.symbols.wxString_Delete(wxStrPtr);
    return result;
}
