// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export function Null_AcceleratorTable(): Deno.PointerValue {
    return lib.symbols.Null_AcceleratorTable();
}

export function Null_Bitmap(): Deno.PointerValue {
    return lib.symbols.Null_Bitmap();
}

export function Null_Brush(): Deno.PointerValue {
    return lib.symbols.Null_Brush();
}

export function Null_Colour(): Deno.PointerValue {
    return lib.symbols.Null_Colour();
}

export function Null_Cursor(): Deno.PointerValue {
    return lib.symbols.Null_Cursor();
}

export function Null_Font(): Deno.PointerValue {
    return lib.symbols.Null_Font();
}

export function Null_Icon(): Deno.PointerValue {
    return lib.symbols.Null_Icon();
}

export function Null_Palette(): Deno.PointerValue {
    return lib.symbols.Null_Palette();
}

export function Null_Pen(): Deno.PointerValue {
    return lib.symbols.Null_Pen();
}

export function kwxSysErrorCode(): number {
    return lib.symbols.kwxSysErrorCode();
}

export function kwxSysErrorMsg(nErrCode: number): Deno.PointerValue {
    return lib.symbols.kwxSysErrorMsg(nErrCode);
}

export function LogErrorMsg(message: Deno.PointerValue): void {
    lib.symbols.LogErrorMsg(message);
}

export function LogFatalErrorMsg(message: Deno.PointerValue): void {
    lib.symbols.LogFatalErrorMsg(message);
}

export function LogMessageMsg(message: Deno.PointerValue): void {
    lib.symbols.LogMessageMsg(message);
}

export function LogWarningMsg(message: Deno.PointerValue): void {
    lib.symbols.LogWarningMsg(message);
}

export function expSetDefaultAssertHandler(): void {
    lib.symbols.expSetDefaultAssertHandler();
}

export function Quantize(src: Deno.PointerValue, dest: Deno.PointerValue, desiredNoColours: number, eightBitData: Deno.PointerValue, flags: number): boolean {
    return (lib.symbols.Quantize(src, dest, desiredNoColours, eightBitData, flags) as number) !== 0;
}

export function QuantizePalette(src: Deno.PointerValue, dest: Deno.PointerValue, pPalette: Deno.PointerValue, desiredNoColours: number, eightBitData: Deno.PointerValue, flags: number): boolean {
    return (lib.symbols.QuantizePalette(src, dest, pPalette, desiredNoColours, eightBitData, flags) as number) !== 0;
}

export function wxCFree(pointer: Deno.PointerValue): void {
    lib.symbols.wxCFree(pointer);
}

export function wxGetkwxLocale(): Deno.PointerValue {
    return lib.symbols.wxGetkwxLocale();
}

export function wxGetkwxTranslation(text: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxGetkwxTranslation(text);
}

export function wxMutexGui_Enter(): void {
    lib.symbols.wxMutexGui_Enter();
}

export function wxMutexGui_Leave(): void {
    lib.symbols.wxMutexGui_Leave();
}

export function kwxUtf8Buffer_Create(str: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.kwxUtf8Buffer_Create(str);
}

export function kwxUtf8Buffer_Data(buf: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.kwxUtf8Buffer_Data(buf);
}

export function kwxUtf8Buffer_Delete(buf: Deno.PointerValue): void {
    lib.symbols.kwxUtf8Buffer_Delete(buf);
}

export function PushProvider(provider: Deno.PointerValue): void {
    lib.symbols.PushProvider(provider);
}

export function RemoveProvider(provider: Deno.PointerValue): boolean {
    return (lib.symbols.RemoveProvider(provider) as number) !== 0;
}

export function expCP_DEFAULT_STYLE(): number {
    return lib.symbols.expCP_DEFAULT_STYLE();
}

export function expCP_NO_TLW_RESIZE(): number {
    return lib.symbols.expCP_NO_TLW_RESIZE();
}

export function kwxMessageBox(message: Deno.PointerValue, caption: Deno.PointerValue, style: number, parent: Deno.PointerValue, x: number, y: number): number {
    return lib.symbols.kwxMessageBox(message, caption, style, parent, x, y);
}

export function expNB_TOP(): number {
    return lib.symbols.expNB_TOP();
}

export function expNB_BOTTOM(): number {
    return lib.symbols.expNB_BOTTOM();
}

export function expNB_LEFT(): number {
    return lib.symbols.expNB_LEFT();
}

export function expNB_RIGHT(): number {
    return lib.symbols.expNB_RIGHT();
}

export function expBK_HITTEST_NOWHERE(): number {
    return lib.symbols.expBK_HITTEST_NOWHERE();
}

export function expBK_HITTEST_ONICON(): number {
    return lib.symbols.expBK_HITTEST_ONICON();
}

export function expBK_HITTEST_ONLABEL(): number {
    return lib.symbols.expBK_HITTEST_ONLABEL();
}

export function expBK_HITTEST_ONITEM(): number {
    return lib.symbols.expBK_HITTEST_ONITEM();
}

export function expBK_HITTEST_ONPAGE(): number {
    return lib.symbols.expBK_HITTEST_ONPAGE();
}

export function expCHB_DEFAULT(): number {
    return lib.symbols.expCHB_DEFAULT();
}

export function expCHB_TOP(): number {
    return lib.symbols.expCHB_TOP();
}

export function expCHB_BOTTOM(): number {
    return lib.symbols.expCHB_BOTTOM();
}

export function expCHB_LEFT(): number {
    return lib.symbols.expCHB_LEFT();
}

export function expCHB_RIGHT(): number {
    return lib.symbols.expCHB_RIGHT();
}

export function expLB_DEFAULT(): number {
    return lib.symbols.expLB_DEFAULT();
}

export function expLB_TOP(): number {
    return lib.symbols.expLB_TOP();
}

export function expLB_BOTTOM(): number {
    return lib.symbols.expLB_BOTTOM();
}

export function expLB_LEFT(): number {
    return lib.symbols.expLB_LEFT();
}

export function expLB_RIGHT(): number {
    return lib.symbols.expLB_RIGHT();
}

export function expTBK_BUTTONBAR(): number {
    return lib.symbols.expTBK_BUTTONBAR();
}

export function expTBK_HORZ_LAYOUT(): number {
    return lib.symbols.expTBK_HORZ_LAYOUT();
}

export function expPGMAN_DEFAULT_STYLE(): number {
    return lib.symbols.expPGMAN_DEFAULT_STYLE();
}

export function expPROPSHEET_DEFAULT(): number {
    return lib.symbols.expPROPSHEET_DEFAULT();
}

export function expPROPSHEET_NOTEBOOK(): number {
    return lib.symbols.expPROPSHEET_NOTEBOOK();
}

export function expPROPSHEET_TOOLBOOK(): number {
    return lib.symbols.expPROPSHEET_TOOLBOOK();
}

export function expPROPSHEET_CHOICEBOOK(): number {
    return lib.symbols.expPROPSHEET_CHOICEBOOK();
}

export function expPROPSHEET_LISTBOOK(): number {
    return lib.symbols.expPROPSHEET_LISTBOOK();
}

export function expPROPSHEET_BUTTONTOOLBOOK(): number {
    return lib.symbols.expPROPSHEET_BUTTONTOOLBOOK();
}

export function expPROPSHEET_TREEBOOK(): number {
    return lib.symbols.expPROPSHEET_TREEBOOK();
}

export function expPROPSHEET_SHRINKTOFIT(): number {
    return lib.symbols.expPROPSHEET_SHRINKTOFIT();
}

export function expTL_SINGLE(): number {
    return lib.symbols.expTL_SINGLE();
}

export function expTL_MULTIPLE(): number {
    return lib.symbols.expTL_MULTIPLE();
}

export function expTL_CHECKBOX(): number {
    return lib.symbols.expTL_CHECKBOX();
}

export function expTL_3STATE(): number {
    return lib.symbols.expTL_3STATE();
}

export function expTL_USER_3STATE(): number {
    return lib.symbols.expTL_USER_3STATE();
}

export function expTL_NO_HEADER(): number {
    return lib.symbols.expTL_NO_HEADER();
}

export function expTL_DEFAULT_STYLE(): number {
    return lib.symbols.expTL_DEFAULT_STYLE();
}

export function expWEBVIEW_ZOOM_TINY(): number {
    return lib.symbols.expWEBVIEW_ZOOM_TINY();
}

export function expWEBVIEW_ZOOM_SMALL(): number {
    return lib.symbols.expWEBVIEW_ZOOM_SMALL();
}

export function expWEBVIEW_ZOOM_MEDIUM(): number {
    return lib.symbols.expWEBVIEW_ZOOM_MEDIUM();
}

export function expWEBVIEW_ZOOM_LARGE(): number {
    return lib.symbols.expWEBVIEW_ZOOM_LARGE();
}

export function expWEBVIEW_ZOOM_LARGEST(): number {
    return lib.symbols.expWEBVIEW_ZOOM_LARGEST();
}

export function expWEBVIEW_ZOOM_TYPE_LAYOUT(): number {
    return lib.symbols.expWEBVIEW_ZOOM_TYPE_LAYOUT();
}

export function expWEBVIEW_ZOOM_TYPE_TEXT(): number {
    return lib.symbols.expWEBVIEW_ZOOM_TYPE_TEXT();
}

export function expWEBVIEW_RELOAD_DEFAULT(): number {
    return lib.symbols.expWEBVIEW_RELOAD_DEFAULT();
}

export function expWEBVIEW_RELOAD_NO_CACHE(): number {
    return lib.symbols.expWEBVIEW_RELOAD_NO_CACHE();
}

export function expWEBVIEW_FIND_WRAP(): number {
    return lib.symbols.expWEBVIEW_FIND_WRAP();
}

export function expWEBVIEW_FIND_ENTIRE_WORD(): number {
    return lib.symbols.expWEBVIEW_FIND_ENTIRE_WORD();
}

export function expWEBVIEW_FIND_MATCH_CASE(): number {
    return lib.symbols.expWEBVIEW_FIND_MATCH_CASE();
}

export function expWEBVIEW_FIND_HIGHLIGHT_RESULT(): number {
    return lib.symbols.expWEBVIEW_FIND_HIGHLIGHT_RESULT();
}

export function expWEBVIEW_FIND_BACKWARDS(): number {
    return lib.symbols.expWEBVIEW_FIND_BACKWARDS();
}

export function expWEBVIEW_FIND_DEFAULT(): number {
    return lib.symbols.expWEBVIEW_FIND_DEFAULT();
}

export function expWEBVIEW_NAV_ERR_CONNECTION(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_CONNECTION();
}

export function expWEBVIEW_NAV_ERR_CERTIFICATE(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_CERTIFICATE();
}

export function expWEBVIEW_NAV_ERR_AUTH(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_AUTH();
}

export function expWEBVIEW_NAV_ERR_SECURITY(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_SECURITY();
}

export function expWEBVIEW_NAV_ERR_NOT_FOUND(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_NOT_FOUND();
}

export function expWEBVIEW_NAV_ERR_REQUEST(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_REQUEST();
}

export function expWEBVIEW_NAV_ERR_USER_CANCELLED(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_USER_CANCELLED();
}

export function expWEBVIEW_NAV_ERR_OTHER(): number {
    return lib.symbols.expWEBVIEW_NAV_ERR_OTHER();
}

export function expWEBVIEW_NAV_ACTION_NONE(): number {
    return lib.symbols.expWEBVIEW_NAV_ACTION_NONE();
}

export function expWEBVIEW_NAV_ACTION_USER(): number {
    return lib.symbols.expWEBVIEW_NAV_ACTION_USER();
}

export function expWEBVIEW_NAV_ACTION_OTHER(): number {
    return lib.symbols.expWEBVIEW_NAV_ACTION_OTHER();
}

