// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class kwxArtProv {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(pObject: Deno.PointerValue, callback: Deno.PointerValue): kwxArtProv | null {
    const rawPtr = lib.symbols.kwxArtProv_Create(pObject, callback);
    if (rawPtr === null) return null;
    return new kwxArtProv(rawPtr);
  }

  Release(): void {
    lib.symbols.kwxArtProv_Release(this.#ptr);
  }

}
