// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class kwxCommand {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(canUndo: number, name: Deno.PointerValue, pObject: Deno.PointerValue, callback: Deno.PointerValue): kwxCommand | null {
    const rawPtr = lib.symbols.kwxCommand_Create(canUndo, name, pObject, callback);
    if (rawPtr === null) return null;
    return new kwxCommand(rawPtr);
  }

  Delete(): void {
    lib.symbols.kwxCommand_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  CanUndo(): boolean {
    return (lib.symbols.kwxCommand_CanUndo(this.#ptr) as number) !== 0;
  }

  GetName(): Deno.PointerValue {
    return lib.symbols.kwxCommand_GetName(this.#ptr);
  }

}
