// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxDropTarget } from "./wxDropTarget_gen.ts";

export class kwxDropTarget extends wxDropTarget {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(pObject: Deno.PointerValue): kwxDropTarget | null {
    const rawPtr = lib.symbols.kwxDropTarget_Create(pObject);
    if (rawPtr === null) return null;
    return new kwxDropTarget(rawPtr);
  }

  Delete(): void {
    lib.symbols.kwxDropTarget_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  SetOnData(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxDropTarget_SetOnData(this._ptr, pFunction);
  }

  SetOnDragOver(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxDropTarget_SetOnDragOver(this._ptr, pFunction);
  }

  SetOnDrop(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxDropTarget_SetOnDrop(this._ptr, pFunction);
  }

  SetOnEnter(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxDropTarget_SetOnEnter(this._ptr, pFunction);
  }

  SetOnLeave(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxDropTarget_SetOnLeave(this._ptr, pFunction);
  }

}
