// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class kwxGridTable {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(pObject: Deno.PointerValue, fnGetNumberRows: Deno.PointerValue, fnGetNumberCols: Deno.PointerValue, fnGetValue: Deno.PointerValue, fnSetValue: Deno.PointerValue, fnIsEmptyCell: Deno.PointerValue, fnClear: Deno.PointerValue, fnInsertRows: Deno.PointerValue, fnAppendRows: Deno.PointerValue, fnDeleteRows: Deno.PointerValue, fnInsertCols: Deno.PointerValue, fnAppendCols: Deno.PointerValue, fnDeleteCols: Deno.PointerValue, fnSetRowLabelValue: Deno.PointerValue, fnSetColLabelValue: Deno.PointerValue, fnGetRowLabelValue: Deno.PointerValue, fnGetColLabelValue: Deno.PointerValue): kwxGridTable | null {
    const rawPtr = lib.symbols.kwxGridTable_Create(pObject, fnGetNumberRows, fnGetNumberCols, fnGetValue, fnSetValue, fnIsEmptyCell, fnClear, fnInsertRows, fnAppendRows, fnDeleteRows, fnInsertCols, fnAppendCols, fnDeleteCols, fnSetRowLabelValue, fnSetColLabelValue, fnGetRowLabelValue, fnGetColLabelValue);
    if (rawPtr === null) return null;
    return new kwxGridTable(rawPtr);
  }

  Delete(): void {
    lib.symbols.kwxGridTable_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetView(): Deno.PointerValue {
    return lib.symbols.kwxGridTable_GetView(this.#ptr);
  }

  SendTableMessage(id: number, val1: number, val2: number): Deno.PointerValue {
    return lib.symbols.kwxGridTable_SendTableMessage(this.#ptr, id, val1, val2);
  }

}
