// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class kwxLog {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(pObject: Deno.PointerValue, pFunction: Deno.PointerValue): kwxLog | null {
    const rawPtr = lib.symbols.kwxLog_Create(pObject, pFunction);
    if (rawPtr === null) return null;
    return new kwxLog(rawPtr);
  }

  Delete(): void {
    lib.symbols.kwxLog_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddTraceMask(str: Deno.PointerValue): void {
    lib.symbols.kwxLog_AddTraceMask(this.#ptr, str);
  }

  DontCreateOnDemand(): void {
    lib.symbols.kwxLog_DontCreateOnDemand(this.#ptr);
  }

  EnableLogging(doIt: boolean): number {
    return lib.symbols.kwxLog_EnableLogging(this.#ptr, doIt ? 1 : 0);
  }

  Flush(): void {
    lib.symbols.kwxLog_Flush(this.#ptr);
  }

  FlushActive(): void {
    lib.symbols.kwxLog_FlushActive(this.#ptr);
  }

  GetActiveTarget(): Deno.PointerValue {
    return lib.symbols.kwxLog_GetActiveTarget();
  }

  GetTimestamp(): Deno.PointerValue {
    return lib.symbols.kwxLog_GetTimestamp(this.#ptr);
  }

  GetVerbose(): number {
    return lib.symbols.kwxLog_GetVerbose(this.#ptr);
  }

  HasPendingMessages(): boolean {
    return (lib.symbols.kwxLog_HasPendingMessages(this.#ptr) as number) !== 0;
  }

  IsAllowedTraceMask(mask: Deno.PointerValue): boolean {
    return (lib.symbols.kwxLog_IsAllowedTraceMask(this.#ptr, mask) as number) !== 0;
  }

  IsEnabled(): boolean {
    return (lib.symbols.kwxLog_IsEnabled(this.#ptr) as number) !== 0;
  }

  OnLog(level: number, szString: Deno.PointerValue, timestamp: number): void {
    lib.symbols.kwxLog_OnLog(this.#ptr, level, szString, timestamp);
  }

  RemoveTraceMask(str: Deno.PointerValue): void {
    lib.symbols.kwxLog_RemoveTraceMask(this.#ptr, str);
  }

  Resume(): void {
    lib.symbols.kwxLog_Resume(this.#ptr);
  }

  SetActiveTarget(): Deno.PointerValue {
    return lib.symbols.kwxLog_SetActiveTarget(this.#ptr);
  }

  SetTimestamp(timestamp: Deno.PointerValue): void {
    lib.symbols.kwxLog_SetTimestamp(this.#ptr, timestamp);
  }

  SetVerbose(bVerbose: number): void {
    lib.symbols.kwxLog_SetVerbose(this.#ptr, bVerbose);
  }

  Suspend(): void {
    lib.symbols.kwxLog_Suspend(this.#ptr);
  }

}
