// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class kwxPreviewFrame {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(pObject: Deno.PointerValue, init: Deno.PointerValue, createCanvas: Deno.PointerValue, createToolbar: Deno.PointerValue, preview: Deno.PointerValue, parent: Deno.PointerValue, title: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): kwxPreviewFrame | null {
    const rawPtr = lib.symbols.kwxPreviewFrame_Create(pObject, init, createCanvas, createToolbar, preview, parent, title, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new kwxPreviewFrame(rawPtr);
  }

  GetControlBar(): Deno.PointerValue {
    return lib.symbols.kwxPreviewFrame_GetControlBar(this.#ptr);
  }

  GetPreviewCanvas(): Deno.PointerValue {
    return lib.symbols.kwxPreviewFrame_GetPreviewCanvas(this.#ptr);
  }

  GetPrintPreview(): Deno.PointerValue {
    return lib.symbols.kwxPreviewFrame_GetPrintPreview(this.#ptr);
  }

  Initialize(): void {
    lib.symbols.kwxPreviewFrame_Initialize(this.#ptr);
  }

  SetControlBar(obj: Deno.PointerValue): void {
    lib.symbols.kwxPreviewFrame_SetControlBar(this.#ptr, obj);
  }

  SetPreviewCanvas(obj: Deno.PointerValue): void {
    lib.symbols.kwxPreviewFrame_SetPreviewCanvas(this.#ptr, obj);
  }

  SetPrintPreview(obj: Deno.PointerValue): void {
    lib.symbols.kwxPreviewFrame_SetPrintPreview(this.#ptr, obj);
  }

}
