// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxDropTarget } from "./wxDropTarget_gen.ts";

export class kwxTextDropTarget extends wxDropTarget {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(pObject: Deno.PointerValue, pFunction: Deno.PointerValue): kwxTextDropTarget | null {
    const rawPtr = lib.symbols.kwxTextDropTarget_Create(pObject, pFunction);
    if (rawPtr === null) return null;
    return new kwxTextDropTarget(rawPtr);
  }

  Delete(): void {
    lib.symbols.kwxTextDropTarget_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  SetOnData(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnData(this._ptr, pFunction);
  }

  SetOnDragOver(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnDragOver(this._ptr, pFunction);
  }

  SetOnDrop(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnDrop(this._ptr, pFunction);
  }

  SetOnEnter(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnEnter(this._ptr, pFunction);
  }

  SetOnLeave(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnLeave(this._ptr, pFunction);
  }

}
