// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class kwxTextDropTarget {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(pObject: Deno.PointerValue, pFunction: Deno.PointerValue): kwxTextDropTarget | null {
    const rawPtr = lib.symbols.kwxTextDropTarget_Create(pObject, pFunction);
    if (rawPtr === null) return null;
    return new kwxTextDropTarget(rawPtr);
  }

  Delete(): void {
    lib.symbols.kwxTextDropTarget_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  SetOnData(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnData(this.#ptr, pFunction);
  }

  SetOnDragOver(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnDragOver(this.#ptr, pFunction);
  }

  SetOnDrop(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnDrop(this.#ptr, pFunction);
  }

  SetOnEnter(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnEnter(this.#ptr, pFunction);
  }

  SetOnLeave(pFunction: Deno.PointerValue): void {
    lib.symbols.kwxTextDropTarget_SetOnLeave(this.#ptr, pFunction);
  }

}
