// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxEvent } from "./wxEvent_gen.ts";

export class wxActivateEvent extends wxEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  GetActive(): boolean {
    return (lib.symbols.wxActivateEvent_GetActive(this._ptr) as number) !== 0;
  }

}
