// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAcceleratorEntry {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(flags: number, keyCode: number, cmd: number): wxAcceleratorEntry | null {
    const rawPtr = lib.symbols.wxAcceleratorEntry_Create(flags, keyCode, cmd);
    if (rawPtr === null) return null;
    return new wxAcceleratorEntry(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxAcceleratorEntry_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetCommand(): number {
    return lib.symbols.wxAcceleratorEntry_GetCommand(this.#ptr);
  }

  GetFlags(): number {
    return lib.symbols.wxAcceleratorEntry_GetFlags(this.#ptr);
  }

  GetKeyCode(): number {
    return lib.symbols.wxAcceleratorEntry_GetKeyCode(this.#ptr);
  }

  Set(flags: number, keyCode: number, cmd: number, item: Deno.PointerValue): void {
    lib.symbols.wxAcceleratorEntry_Set(this.#ptr, flags, keyCode, cmd, item);
  }

}
