// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAcceleratorTable {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(count: number, entries: Deno.PointerValue): wxAcceleratorTable | null {
    const rawPtr = lib.symbols.wxAcceleratorTable_Create(count, entries);
    if (rawPtr === null) return null;
    return new wxAcceleratorTable(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxAcceleratorTable_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
