// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAnimationCtrl {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxAnimationCtrl | null {
    const rawPtr = lib.symbols.wxAnimationCtrl_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxAnimationCtrl(rawPtr);
  }

  static CreateWithAnimation(parent: Deno.PointerValue, id: number, anim: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxAnimationCtrl | null {
    const rawPtr = lib.symbols.wxAnimationCtrl_CreateWithAnimation(parent, id, anim, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxAnimationCtrl(rawPtr);
  }

  GetAnimation(anim: Deno.PointerValue): void {
    lib.symbols.wxAnimationCtrl_GetAnimation(this._ptr, anim);
  }

  GetInactiveBitmap(bmp: Deno.PointerValue): void {
    lib.symbols.wxAnimationCtrl_GetInactiveBitmap(this._ptr, bmp);
  }

  IsPlaying(): boolean {
    return (lib.symbols.wxAnimationCtrl_IsPlaying(this._ptr) as number) !== 0;
  }

  LoadFile(filename: Deno.PointerValue, type_: number): boolean {
    return (lib.symbols.wxAnimationCtrl_LoadFile(this._ptr, filename, type_) as number) !== 0;
  }

  Load(stream: Deno.PointerValue, type_: number): boolean {
    return (lib.symbols.wxAnimationCtrl_Load(this._ptr, stream, type_) as number) !== 0;
  }

  Play(): boolean {
    return (lib.symbols.wxAnimationCtrl_Play(this._ptr) as number) !== 0;
  }

  SetAnimation(anim: Deno.PointerValue): void {
    lib.symbols.wxAnimationCtrl_SetAnimation(this._ptr, anim);
  }

  SetInactiveBitmap(bmp: Deno.PointerValue): void {
    lib.symbols.wxAnimationCtrl_SetInactiveBitmap(this._ptr, bmp);
  }

  Stop(): void {
    lib.symbols.wxAnimationCtrl_Stop(this._ptr);
  }

}
