// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiManager {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(managedWnd: Deno.PointerValue, flags: number): wxAuiManager | null {
    const rawPtr = lib.symbols.wxAuiManager_Create(managedWnd, flags);
    if (rawPtr === null) return null;
    return new wxAuiManager(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxAuiManager_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  DetachPane(window: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiManager_DetachPane(this.#ptr, window) as number) !== 0;
  }

  GetAllPanes(): Deno.PointerValue {
    return lib.symbols.wxAuiManager_GetAllPanes(this.#ptr);
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxAuiManager_GetArtProvider(this.#ptr);
  }

  GetDockSizeConstraint(widthPct: Deno.PointerValue, heightPct: Deno.PointerValue): void {
    lib.symbols.wxAuiManager_GetDockSizeConstraint(this.#ptr, widthPct, heightPct);
  }

  GetFlags(): number {
    return lib.symbols.wxAuiManager_GetFlags(this.#ptr);
  }

  GetManagedWindow(): Deno.PointerValue {
    return lib.symbols.wxAuiManager_GetManagedWindow(this.#ptr);
  }

  HideHint(): void {
    lib.symbols.wxAuiManager_HideHint(this.#ptr);
  }

  InsertPane(window: Deno.PointerValue, insertLocation: Deno.PointerValue, insertLevel: number): boolean {
    return (lib.symbols.wxAuiManager_InsertPane(this.#ptr, window, insertLocation, insertLevel) as number) !== 0;
  }

  LoadPaneInfo(panePart: Deno.PointerValue, pane: Deno.PointerValue): void {
    lib.symbols.wxAuiManager_LoadPaneInfo(this.#ptr, panePart, pane);
  }

  LoadPerspective(perspective: Deno.PointerValue, update: boolean): boolean {
    return (lib.symbols.wxAuiManager_LoadPerspective(this.#ptr, perspective, update ? 1 : 0) as number) !== 0;
  }

  SavePaneInfo(pane: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiManager_SavePaneInfo(this.#ptr, pane);
  }

  SavePerspective(): Deno.PointerValue {
    return lib.symbols.wxAuiManager_SavePerspective(this.#ptr);
  }

  SetArtProvider(artProvider: Deno.PointerValue): void {
    lib.symbols.wxAuiManager_SetArtProvider(this.#ptr, artProvider);
  }

  SetDockSizeConstraint(widthpct: number, heightpct: number): void {
    lib.symbols.wxAuiManager_SetDockSizeConstraint(this.#ptr, widthpct, heightpct);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxAuiManager_SetFlags(this.#ptr, flags);
  }

  SetManagedWindow(managedWnd: Deno.PointerValue): void {
    lib.symbols.wxAuiManager_SetManagedWindow(this.#ptr, managedWnd);
  }

  ShowHint(rect: Deno.PointerValue): void {
    lib.symbols.wxAuiManager_ShowHint(this.#ptr, rect);
  }

  UnInit(): void {
    lib.symbols.wxAuiManager_UnInit(this.#ptr);
  }

  Update(): void {
    lib.symbols.wxAuiManager_Update(this.#ptr);
  }

  AddPane(window: Deno.PointerValue, direction: number, caption: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiManager_AddPane(this.#ptr, window, direction, caption) as number) !== 0;
  }

  AddPaneByPaneInfo(window: Deno.PointerValue, paneInfo: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiManager_AddPaneByPaneInfo(this.#ptr, window, paneInfo) as number) !== 0;
  }

  AddPaneByPaneInfoAndDropPosition(window: Deno.PointerValue, paneInfo: Deno.PointerValue, x: number, y: number): boolean {
    return (lib.symbols.wxAuiManager_AddPaneByPaneInfoAndDropPosition(this.#ptr, window, paneInfo, x, y) as number) !== 0;
  }

  GetPaneByWindow(window: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiManager_GetPaneByWindow(this.#ptr, window);
  }

  GetPaneByName(name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiManager_GetPaneByName(this.#ptr, name);
  }

  GetManager(window: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiManager_GetManager(window);
  }

}
