// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiNotebookPage {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  Window(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebookPage_Window(this.#ptr);
  }

  Caption(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebookPage_Caption(this.#ptr);
  }

  Tooltip(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebookPage_Tooltip(this.#ptr);
  }

  Bitmap(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebookPage_Bitmap(this.#ptr);
  }

  Rect(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebookPage_Rect(this.#ptr);
  }

  Active(): boolean {
    return (lib.symbols.wxAuiNotebookPage_Active(this.#ptr) as number) !== 0;
  }

}
