// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiToolBarItemArray {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxAuiToolBarItemArray | null {
    const rawPtr = lib.symbols.wxAuiToolBarItemArray_Create();
    if (rawPtr === null) return null;
    return new wxAuiToolBarItemArray(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxAuiToolBarItemArray_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetCount(): number {
    return lib.symbols.wxAuiToolBarItemArray_GetCount(this.#ptr);
  }

  Item(index: number): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItemArray_Item(this.#ptr, index);
  }

}
