// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiDefaultTabArt {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxAuiDefaultTabArt | null {
    const rawPtr = lib.symbols.wxAuiDefaultTabArt_Create();
    if (rawPtr === null) return null;
    return new wxAuiDefaultTabArt(rawPtr);
  }

  Clone(): Deno.PointerValue {
    return lib.symbols.wxAuiDefaultTabArt_Clone(this.#ptr);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxAuiDefaultTabArt_SetFlags(this.#ptr, flags);
  }

  SetSizingInfo(width: number, height: number, tabCount: bigint): void {
    lib.symbols.wxAuiDefaultTabArt_SetSizingInfo(this.#ptr, width, height, tabCount);
  }

  SetNormalFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_SetNormalFont(this.#ptr, font);
  }

  SetSelectedFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_SetSelectedFont(this.#ptr, font);
  }

  SetMeasuringFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_SetMeasuringFont(this.#ptr, font);
  }

  SetColour(colour: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_SetColour(this.#ptr, colour);
  }

  SetActiveColour(colour: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_SetActiveColour(this.#ptr, colour);
  }

  DrawBackground(dc: Deno.PointerValue, window: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_DrawBackground(this.#ptr, dc, window, rect);
  }

  DrawTab(dc: Deno.PointerValue, window: Deno.PointerValue, pane: Deno.PointerValue, inRect: Deno.PointerValue, closeButtonState: number, outTabRect: Deno.PointerValue, outButtonRect: Deno.PointerValue, xExtent: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_DrawTab(this.#ptr, dc, window, pane, inRect, closeButtonState, outTabRect, outButtonRect, xExtent);
  }

  DrawButton(dc: Deno.PointerValue, window: Deno.PointerValue, inRect: Deno.PointerValue, bitmapId: number, buttonState: number, orientation: number, outRect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultTabArt_DrawButton(this.#ptr, dc, window, inRect, bitmapId, buttonState, orientation, outRect);
  }

  GetIndentSize(): number {
    return lib.symbols.wxAuiDefaultTabArt_GetIndentSize(this.#ptr);
  }

  GetTabSize(dc: Deno.PointerValue, window: Deno.PointerValue, caption: Deno.PointerValue, bitmap: Deno.PointerValue, active: boolean, closeButtonState: number, xExtent: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiDefaultTabArt_GetTabSize(this.#ptr, dc, window, caption, bitmap, active ? 1 : 0, closeButtonState, xExtent);
  }

  ShowDropDown(window: Deno.PointerValue, items: Deno.PointerValue, activeIdx: number): number {
    return lib.symbols.wxAuiDefaultTabArt_ShowDropDown(this.#ptr, window, items, activeIdx);
  }

  GetBestTabCtrlSize(window: Deno.PointerValue, pages: Deno.PointerValue, width: number, height: number): number {
    return lib.symbols.wxAuiDefaultTabArt_GetBestTabCtrlSize(this.#ptr, window, pages, width, height);
  }

}
