// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiDefaultToolBarArt {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxAuiDefaultToolBarArt | null {
    const rawPtr = lib.symbols.wxAuiDefaultToolBarArt_Create();
    if (rawPtr === null) return null;
    return new wxAuiDefaultToolBarArt(rawPtr);
  }

  Clone(): Deno.PointerValue {
    return lib.symbols.wxAuiDefaultToolBarArt_Clone(this.#ptr);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxAuiDefaultToolBarArt_SetFlags(this.#ptr, flags);
  }

  GetFlags(): number {
    return lib.symbols.wxAuiDefaultToolBarArt_GetFlags(this.#ptr);
  }

  SetFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_SetFont(this.#ptr, font);
  }

  GetFont(): Deno.PointerValue {
    return lib.symbols.wxAuiDefaultToolBarArt_GetFont(this.#ptr);
  }

  SetTextOrientation(orientation: number): void {
    lib.symbols.wxAuiDefaultToolBarArt_SetTextOrientation(this.#ptr, orientation);
  }

  GetTextOrientation(): number {
    return lib.symbols.wxAuiDefaultToolBarArt_GetTextOrientation(this.#ptr);
  }

  DrawBackground(dc: Deno.PointerValue, window: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawBackground(this.#ptr, dc, window, rect);
  }

  DrawPlainBackground(dc: Deno.PointerValue, window: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawPlainBackground(this.#ptr, dc, window, rect);
  }

  DrawLabel(dc: Deno.PointerValue, window: Deno.PointerValue, item: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawLabel(this.#ptr, dc, window, item, rect);
  }

  DrawButton(dc: Deno.PointerValue, window: Deno.PointerValue, item: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawButton(this.#ptr, dc, window, item, rect);
  }

  DrawDropDownButton(dc: Deno.PointerValue, window: Deno.PointerValue, item: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawDropDownButton(this.#ptr, dc, window, item, rect);
  }

  DrawControlLabel(dc: Deno.PointerValue, window: Deno.PointerValue, item: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawControlLabel(this.#ptr, dc, window, item, rect);
  }

  DrawSeparator(dc: Deno.PointerValue, window: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawSeparator(this.#ptr, dc, window, rect);
  }

  DrawGripper(dc: Deno.PointerValue, window: Deno.PointerValue, rect: Deno.PointerValue): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawGripper(this.#ptr, dc, window, rect);
  }

  DrawOverflowButton(dc: Deno.PointerValue, window: Deno.PointerValue, rect: Deno.PointerValue, state: number): void {
    lib.symbols.wxAuiDefaultToolBarArt_DrawOverflowButton(this.#ptr, dc, window, rect, state);
  }

  GetLabelSize(dc: Deno.PointerValue, window: Deno.PointerValue, item: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiDefaultToolBarArt_GetLabelSize(this.#ptr, dc, window, item);
  }

  GetToolSize(dc: Deno.PointerValue, window: Deno.PointerValue, item: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiDefaultToolBarArt_GetToolSize(this.#ptr, dc, window, item);
  }

  GetElementSize(element: number): number {
    return lib.symbols.wxAuiDefaultToolBarArt_GetElementSize(this.#ptr, element);
  }

  SetElementSize(element_id: number, size: number): void {
    lib.symbols.wxAuiDefaultToolBarArt_SetElementSize(this.#ptr, element_id, size);
  }

  ShowDropDown(window: Deno.PointerValue, items: Deno.PointerValue): number {
    return lib.symbols.wxAuiDefaultToolBarArt_ShowDropDown(this.#ptr, window, items);
  }

}
