// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiTabContainer {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxAuiTabContainer | null {
    const rawPtr = lib.symbols.wxAuiTabContainer_Create();
    if (rawPtr === null) return null;
    return new wxAuiTabContainer(rawPtr);
  }

  SetArtProvider(artId: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetArtProvider(this.#ptr, artId);
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxAuiTabContainer_GetArtProvider(this.#ptr);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxAuiTabContainer_SetFlags(this.#ptr, flags);
  }

  GetFlags(): number {
    return lib.symbols.wxAuiTabContainer_GetFlags(this.#ptr);
  }

  AddPage(page: Deno.PointerValue, info: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabContainer_AddPage(this.#ptr, page, info) as number) !== 0;
  }

  InsertPage(page: Deno.PointerValue, info: Deno.PointerValue, idx: bigint): boolean {
    return (lib.symbols.wxAuiTabContainer_InsertPage(this.#ptr, page, info, idx) as number) !== 0;
  }

  MovePage(page: Deno.PointerValue, newIdx: bigint): boolean {
    return (lib.symbols.wxAuiTabContainer_MovePage(this.#ptr, page, newIdx) as number) !== 0;
  }

  RemovePage(page: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabContainer_RemovePage(this.#ptr, page) as number) !== 0;
  }

  SetActivePageByWindow(page: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabContainer_SetActivePageByWindow(this.#ptr, page) as number) !== 0;
  }

  SetActivePage(page: bigint): boolean {
    return (lib.symbols.wxAuiTabContainer_SetActivePage(this.#ptr, page) as number) !== 0;
  }

  SetNoneActive(): void {
    lib.symbols.wxAuiTabContainer_SetNoneActive(this.#ptr);
  }

  GetActivePage(): number {
    return lib.symbols.wxAuiTabContainer_GetActivePage(this.#ptr);
  }

  GetWindowFromIdx(idx: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiTabContainer_GetWindowFromIdx(this.#ptr, idx);
  }

  GetIdxFromWindow(page: Deno.PointerValue): number {
    return lib.symbols.wxAuiTabContainer_GetIdxFromWindow(this.#ptr, page);
  }

  GetPageCount(): bigint {
    return lib.symbols.wxAuiTabContainer_GetPageCount(this.#ptr) as bigint;
  }

  GetPage(idx: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiTabContainer_GetPage(this.#ptr, idx);
  }

  GetPages(): Deno.PointerValue {
    return lib.symbols.wxAuiTabContainer_GetPages(this.#ptr);
  }

  SetNormalFont(normalFont: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetNormalFont(this.#ptr, normalFont);
  }

  SetSelectedFont(selectedFont: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetSelectedFont(this.#ptr, selectedFont);
  }

  SetMeasuringFont(measuringFont: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetMeasuringFont(this.#ptr, measuringFont);
  }

  SetColour(colour: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetColour(this.#ptr, colour);
  }

  SetActiveColour(colour: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetActiveColour(this.#ptr, colour);
  }

  DoShowHide(): void {
    lib.symbols.wxAuiTabContainer_DoShowHide(this.#ptr);
  }

  SetRect(rect: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_SetRect(this.#ptr, rect);
  }

  RemoveButton(id: number): void {
    lib.symbols.wxAuiTabContainer_RemoveButton(this.#ptr, id);
  }

  AddButton(id: number, location: number, normalBitmap: Deno.PointerValue, disabledBitmap: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_AddButton(this.#ptr, id, location, normalBitmap, disabledBitmap);
  }

  GetTabOffset(): bigint {
    return lib.symbols.wxAuiTabContainer_GetTabOffset(this.#ptr) as bigint;
  }

  SetTabOffset(offset: bigint): void {
    lib.symbols.wxAuiTabContainer_SetTabOffset(this.#ptr, offset);
  }

  IsTabVisible(tabPage: number, tabOffset: number, dc: Deno.PointerValue, window: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabContainer_IsTabVisible(this.#ptr, tabPage, tabOffset, dc, window) as number) !== 0;
  }

  MakeTabVisible(tabPage: number, win: Deno.PointerValue): void {
    lib.symbols.wxAuiTabContainer_MakeTabVisible(this.#ptr, tabPage, win);
  }

}
