// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAutoBufferedPaintDC {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(window: Deno.PointerValue): wxAutoBufferedPaintDC | null {
    const rawPtr = lib.symbols.wxAutoBufferedPaintDC_Create(window);
    if (rawPtr === null) return null;
    return new wxAutoBufferedPaintDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxAutoBufferedPaintDC_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
