// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiMDIChildFrame {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, title: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxAuiMDIChildFrame | null {
    const rawPtr = lib.symbols.wxAuiMDIChildFrame_Create(parent, id, title, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxAuiMDIChildFrame(rawPtr);
  }

  Activate(): void {
    lib.symbols.wxAuiMDIChildFrame_Activate(this.#ptr);
  }

  GetMenuBar(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetMenuBar(this.#ptr);
  }

  SetMenuBar(menuBar: Deno.PointerValue): void {
    lib.symbols.wxAuiMDIChildFrame_SetMenuBar(this.#ptr, menuBar);
  }

  GetStatusBar(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetStatusBar(this.#ptr);
  }

  CreateStatusBar(number: number, style: number, id: number): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_CreateStatusBar(this.#ptr, number, style, id);
  }

  GetToolBar(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetToolBar(this.#ptr);
  }

  CreateToolBar(style: number, id: number): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_CreateToolBar(this.#ptr, style, id);
  }

  SetTitle(title: Deno.PointerValue): void {
    lib.symbols.wxAuiMDIChildFrame_SetTitle(this.#ptr, title);
  }

  GetTitle(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetTitle(this.#ptr);
  }

  SetIcons(icons: Deno.PointerValue): void {
    lib.symbols.wxAuiMDIChildFrame_SetIcons(this.#ptr, icons);
  }

  GetIcons(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetIcons(this.#ptr);
  }

  SetIcon(icon: Deno.PointerValue): void {
    lib.symbols.wxAuiMDIChildFrame_SetIcon(this.#ptr, icon);
  }

  GetIcon(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetIcon(this.#ptr);
  }

  GetMDIParent(): Deno.PointerValue {
    return lib.symbols.wxAuiMDIChildFrame_GetMDIParent(this.#ptr);
  }

}
