// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiNotebook {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static CreateDefault(): wxAuiNotebook | null {
    const rawPtr = lib.symbols.wxAuiNotebook_CreateDefault();
    if (rawPtr === null) return null;
    return new wxAuiNotebook(rawPtr);
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxAuiNotebook | null {
    const rawPtr = lib.symbols.wxAuiNotebook_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxAuiNotebook(rawPtr);
  }

  CreateFromDefault(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): boolean {
    return (lib.symbols.wxAuiNotebook_CreateFromDefault(this.#ptr, parent, id, x, y, width, height, style) as number) !== 0;
  }

  AddPageWithBitmap(page: Deno.PointerValue, caption: Deno.PointerValue, select: boolean, bitmap: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiNotebook_AddPageWithBitmap(this.#ptr, page, caption, select ? 1 : 0, bitmap) as number) !== 0;
  }

  AddPage(page: Deno.PointerValue, text: Deno.PointerValue, select: boolean, imageId: number): boolean {
    return (lib.symbols.wxAuiNotebook_AddPage(this.#ptr, page, text, select ? 1 : 0, imageId) as number) !== 0;
  }

  AdvanceSelection(forward: boolean): void {
    lib.symbols.wxAuiNotebook_AdvanceSelection(this.#ptr, forward ? 1 : 0);
  }

  ChangeSelection(index: bigint): number {
    return lib.symbols.wxAuiNotebook_ChangeSelection(this.#ptr, index);
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxAuiNotebook_DeleteAllPages(this.#ptr) as number) !== 0;
  }

  DeletePage(page: bigint): boolean {
    return (lib.symbols.wxAuiNotebook_DeletePage(this.#ptr, page) as number) !== 0;
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebook_GetArtProvider(this.#ptr);
  }

  GetCurrentPage(): Deno.PointerValue {
    return lib.symbols.wxAuiNotebook_GetCurrentPage(this.#ptr);
  }

  GetHeightForPageHeight(pageHeight: number): number {
    return lib.symbols.wxAuiNotebook_GetHeightForPageHeight(this.#ptr, pageHeight);
  }

  GetPage(page_idx: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiNotebook_GetPage(this.#ptr, page_idx);
  }

  GetPageBitmap(page: bigint, bmp: Deno.PointerValue): void {
    lib.symbols.wxAuiNotebook_GetPageBitmap(this.#ptr, page, bmp);
  }

  GetPageCount(): bigint {
    return lib.symbols.wxAuiNotebook_GetPageCount(this.#ptr) as bigint;
  }

  GetPageIndex(pageWnd: Deno.PointerValue): number {
    return lib.symbols.wxAuiNotebook_GetPageIndex(this.#ptr, pageWnd);
  }

  GetPageText(page: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiNotebook_GetPageText(this.#ptr, page);
  }

  GetPageToolTip(pageIdx: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiNotebook_GetPageToolTip(this.#ptr, pageIdx);
  }

  GetSelection(): number {
    return lib.symbols.wxAuiNotebook_GetSelection(this.#ptr);
  }

  GetTabCtrlHeight(): number {
    return lib.symbols.wxAuiNotebook_GetTabCtrlHeight(this.#ptr);
  }

  InsertPageWithBitmap(page_idx: bigint, page: Deno.PointerValue, caption: Deno.PointerValue, select: boolean, bitmap: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiNotebook_InsertPageWithBitmap(this.#ptr, page_idx, page, caption, select ? 1 : 0, bitmap) as number) !== 0;
  }

  InsertPage(index: bigint, page: Deno.PointerValue, text: Deno.PointerValue, select: boolean, imageId: number): boolean {
    return (lib.symbols.wxAuiNotebook_InsertPage(this.#ptr, index, page, text, select ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(page: bigint): boolean {
    return (lib.symbols.wxAuiNotebook_RemovePage(this.#ptr, page) as number) !== 0;
  }

  SetArtProvider(artId: Deno.PointerValue): void {
    lib.symbols.wxAuiNotebook_SetArtProvider(this.#ptr, artId);
  }

  SetFont(font: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiNotebook_SetFont(this.#ptr, font) as number) !== 0;
  }

  SetMeasuringFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiNotebook_SetMeasuringFont(this.#ptr, font);
  }

  SetNormalFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiNotebook_SetNormalFont(this.#ptr, font);
  }

  SetPageBitmap(page: bigint, bitmap: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiNotebook_SetPageBitmap(this.#ptr, page, bitmap) as number) !== 0;
  }

  SetPageImage(index: bigint, imageId: number): boolean {
    return (lib.symbols.wxAuiNotebook_SetPageImage(this.#ptr, index, imageId) as number) !== 0;
  }

  SetPageText(page: bigint, text: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiNotebook_SetPageText(this.#ptr, page, text) as number) !== 0;
  }

  SetPageToolTip(page: bigint, text: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiNotebook_SetPageToolTip(this.#ptr, page, text) as number) !== 0;
  }

  SetSelectedFont(font: Deno.PointerValue): void {
    lib.symbols.wxAuiNotebook_SetSelectedFont(this.#ptr, font);
  }

  SetSelection(new_page: bigint): bigint {
    return lib.symbols.wxAuiNotebook_SetSelection(this.#ptr, new_page) as bigint;
  }

  SetTabCtrlHeight(height: number): void {
    lib.symbols.wxAuiNotebook_SetTabCtrlHeight(this.#ptr, height);
  }

  ShowWindowMenu(): boolean {
    return (lib.symbols.wxAuiNotebook_ShowWindowMenu(this.#ptr) as number) !== 0;
  }

  SetUniformBitmapSize(width: number, height: number): void {
    lib.symbols.wxAuiNotebook_SetUniformBitmapSize(this.#ptr, width, height);
  }

  Split(page: bigint, direction: number): void {
    lib.symbols.wxAuiNotebook_Split(this.#ptr, page, direction);
  }

}
