// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxAuiToolBarItem {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static CreateDefault(): wxAuiToolBarItem | null {
    const rawPtr = lib.symbols.wxAuiToolBarItem_CreateDefault();
    if (rawPtr === null) return null;
    return new wxAuiToolBarItem(rawPtr);
  }

  static Create(source: Deno.PointerValue): wxAuiToolBarItem | null {
    const rawPtr = lib.symbols.wxAuiToolBarItem_Create(source);
    if (rawPtr === null) return null;
    return new wxAuiToolBarItem(rawPtr);
  }

  Copy(source: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_Copy(this._ptr, source);
  }

  Assign(source: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_Assign(this._ptr, source);
  }

  SetWindow(window: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetWindow(this._ptr, window);
  }

  GetWindow(): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_GetWindow(this._ptr);
  }

  SetId(new_id: number): void {
    lib.symbols.wxAuiToolBarItem_SetId(this._ptr, new_id);
  }

  GetId(): number {
    return lib.symbols.wxAuiToolBarItem_GetId(this._ptr);
  }

  SetKind(new_kind: number): void {
    lib.symbols.wxAuiToolBarItem_SetKind(this._ptr, new_kind);
  }

  GetKind(): number {
    return lib.symbols.wxAuiToolBarItem_GetKind(this._ptr);
  }

  SetState(new_state: number): void {
    lib.symbols.wxAuiToolBarItem_SetState(this._ptr, new_state);
  }

  GetState(): number {
    return lib.symbols.wxAuiToolBarItem_GetState(this._ptr);
  }

  SetSizerItem(sizerItem: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetSizerItem(this._ptr, sizerItem);
  }

  GetSizerItem(): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_GetSizerItem(this._ptr);
  }

  SetLabel(label: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetLabel(this._ptr, label);
  }

  GetLabel(): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_GetLabel(this._ptr);
  }

  SetBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetBitmap(this._ptr, bitmap);
  }

  GetBitmap(ref: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_GetBitmap(this._ptr, ref);
  }

  SetDisabledBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetDisabledBitmap(this._ptr, bitmap);
  }

  GetDisabledBitmap(ref: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_GetDisabledBitmap(this._ptr, ref);
  }

  SetHoverBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetHoverBitmap(this._ptr, bitmap);
  }

  GetHoverBitmap(ref: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_GetHoverBitmap(this._ptr, ref);
  }

  SetShortHelp(helpString: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetShortHelp(this._ptr, helpString);
  }

  GetShortHelp(): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_GetShortHelp(this._ptr);
  }

  SetLongHelp(helpString: Deno.PointerValue): void {
    lib.symbols.wxAuiToolBarItem_SetLongHelp(this._ptr, helpString);
  }

  GetLongHelp(): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_GetLongHelp(this._ptr);
  }

  SetMinSize(width: number, height: number): void {
    lib.symbols.wxAuiToolBarItem_SetMinSize(this._ptr, width, height);
  }

  GetMinSize(): Deno.PointerValue {
    return lib.symbols.wxAuiToolBarItem_GetMinSize(this._ptr);
  }

  SetSpacerPixels(spacerPixels: number): void {
    lib.symbols.wxAuiToolBarItem_SetSpacerPixels(this._ptr, spacerPixels);
  }

  GetSpacerPixels(): number {
    return lib.symbols.wxAuiToolBarItem_GetSpacerPixels(this._ptr);
  }

  SetProportion(proportion: number): void {
    lib.symbols.wxAuiToolBarItem_SetProportion(this._ptr, proportion);
  }

  GetProportion(): number {
    return lib.symbols.wxAuiToolBarItem_GetProportion(this._ptr);
  }

  SetActive(enable: boolean): void {
    lib.symbols.wxAuiToolBarItem_SetActive(this._ptr, enable ? 1 : 0);
  }

  IsActive(): boolean {
    return (lib.symbols.wxAuiToolBarItem_IsActive(this._ptr) as number) !== 0;
  }

  SetHasDropDown(enable: boolean): void {
    lib.symbols.wxAuiToolBarItem_SetHasDropDown(this._ptr, enable ? 1 : 0);
  }

  HasDropDown(): boolean {
    return (lib.symbols.wxAuiToolBarItem_HasDropDown(this._ptr) as number) !== 0;
  }

  SetSticky(enable: boolean): void {
    lib.symbols.wxAuiToolBarItem_SetSticky(this._ptr, enable ? 1 : 0);
  }

  IsSticky(): boolean {
    return (lib.symbols.wxAuiToolBarItem_IsSticky(this._ptr) as number) !== 0;
  }

  SetUserData(userData: number): void {
    lib.symbols.wxAuiToolBarItem_SetUserData(this._ptr, userData);
  }

  GetUserData(): number {
    return lib.symbols.wxAuiToolBarItem_GetUserData(this._ptr);
  }

  SetAlignment(alignment: number): void {
    lib.symbols.wxAuiToolBarItem_SetAlignment(this._ptr, alignment);
  }

  GetAlignment(): number {
    return lib.symbols.wxAuiToolBarItem_GetAlignment(this._ptr);
  }

}
