// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxAuiTabCtrl extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  SetArtProvider(artId: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetArtProvider(this._ptr, artId);
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxAuiTabCtrl_GetArtProvider(this._ptr);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxAuiTabCtrl_SetFlags(this._ptr, flags);
  }

  GetFlags(): number {
    return lib.symbols.wxAuiTabCtrl_GetFlags(this._ptr);
  }

  AddPage(page: Deno.PointerValue, info: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabCtrl_AddPage(this._ptr, page, info) as number) !== 0;
  }

  InsertPage(page: Deno.PointerValue, info: Deno.PointerValue, idx: bigint): boolean {
    return (lib.symbols.wxAuiTabCtrl_InsertPage(this._ptr, page, info, idx) as number) !== 0;
  }

  MovePage(page: Deno.PointerValue, newIdx: bigint): boolean {
    return (lib.symbols.wxAuiTabCtrl_MovePage(this._ptr, page, newIdx) as number) !== 0;
  }

  RemovePage(page: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabCtrl_RemovePage(this._ptr, page) as number) !== 0;
  }

  SetActivePageByWindow(page: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabCtrl_SetActivePageByWindow(this._ptr, page) as number) !== 0;
  }

  SetActivePage(page: bigint): boolean {
    return (lib.symbols.wxAuiTabCtrl_SetActivePage(this._ptr, page) as number) !== 0;
  }

  SetNoneActive(): void {
    lib.symbols.wxAuiTabCtrl_SetNoneActive(this._ptr);
  }

  GetActivePage(): number {
    return lib.symbols.wxAuiTabCtrl_GetActivePage(this._ptr);
  }

  GetWindowFromIdx(idx: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiTabCtrl_GetWindowFromIdx(this._ptr, idx);
  }

  GetIdxFromWindow(page: Deno.PointerValue): number {
    return lib.symbols.wxAuiTabCtrl_GetIdxFromWindow(this._ptr, page);
  }

  GetPageCount(): bigint {
    return lib.symbols.wxAuiTabCtrl_GetPageCount(this._ptr) as bigint;
  }

  GetPage(idx: bigint): Deno.PointerValue {
    return lib.symbols.wxAuiTabCtrl_GetPage(this._ptr, idx);
  }

  GetPages(): Deno.PointerValue {
    return lib.symbols.wxAuiTabCtrl_GetPages(this._ptr);
  }

  SetNormalFont(normalFont: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetNormalFont(this._ptr, normalFont);
  }

  SetSelectedFont(selectedFont: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetSelectedFont(this._ptr, selectedFont);
  }

  SetMeasuringFont(measuringFont: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetMeasuringFont(this._ptr, measuringFont);
  }

  SetColour(colour: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetColour(this._ptr, colour);
  }

  SetActiveColour(colour: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetActiveColour(this._ptr, colour);
  }

  DoShowHide(): void {
    lib.symbols.wxAuiTabCtrl_DoShowHide(this._ptr);
  }

  SetRect(rect: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_SetRect(this._ptr, rect);
  }

  RemoveButton(id: number): void {
    lib.symbols.wxAuiTabCtrl_RemoveButton(this._ptr, id);
  }

  AddButton(id: number, location: number, normalBitmap: Deno.PointerValue, disabledBitmap: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_AddButton(this._ptr, id, location, normalBitmap, disabledBitmap);
  }

  GetTabOffset(): bigint {
    return lib.symbols.wxAuiTabCtrl_GetTabOffset(this._ptr) as bigint;
  }

  SetTabOffset(offset: bigint): void {
    lib.symbols.wxAuiTabCtrl_SetTabOffset(this._ptr, offset);
  }

  IsTabVisible(tabPage: number, tabOffset: number, dc: Deno.PointerValue, window: Deno.PointerValue): boolean {
    return (lib.symbols.wxAuiTabCtrl_IsTabVisible(this._ptr, tabPage, tabOffset, dc, window) as number) !== 0;
  }

  MakeTabVisible(tabPage: number, win: Deno.PointerValue): void {
    lib.symbols.wxAuiTabCtrl_MakeTabVisible(this._ptr, tabPage, win);
  }

}
