// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxBitmapDataObject {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(bitmap: Deno.PointerValue): wxBitmapDataObject | null {
    const rawPtr = lib.symbols.BitmapDataObject_Create(bitmap);
    if (rawPtr === null) return null;
    return new wxBitmapDataObject(rawPtr);
  }

  static CreateEmpty(): wxBitmapDataObject | null {
    const rawPtr = lib.symbols.BitmapDataObject_CreateEmpty();
    if (rawPtr === null) return null;
    return new wxBitmapDataObject(rawPtr);
  }

  Delete(): void {
    lib.symbols.BitmapDataObject_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.BitmapDataObject_GetBitmap(this.#ptr, bitmap);
  }

  SetBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.BitmapDataObject_SetBitmap(this.#ptr, bitmap);
  }

}
