// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxBitmap {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(data: Deno.PointerValue, type_: number, width: number, height: number, depth: number): wxBitmap | null {
    const rawPtr = lib.symbols.wxBitmap_Create(data, type_, width, height, depth);
    if (rawPtr === null) return null;
    return new wxBitmap(rawPtr);
  }

  static CreateDefault(): wxBitmap | null {
    const rawPtr = lib.symbols.wxBitmap_CreateDefault();
    if (rawPtr === null) return null;
    return new wxBitmap(rawPtr);
  }

  static CreateEmpty(width: number, height: number, depth: number): wxBitmap | null {
    const rawPtr = lib.symbols.wxBitmap_CreateEmpty(width, height, depth);
    if (rawPtr === null) return null;
    return new wxBitmap(rawPtr);
  }

  static CreateLoad(name: Deno.PointerValue, type_: number): wxBitmap | null {
    const rawPtr = lib.symbols.wxBitmap_CreateLoad(name, type_);
    if (rawPtr === null) return null;
    return new wxBitmap(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxBitmap_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddHandler(handler: Deno.PointerValue): void {
    lib.symbols.wxBitmap_AddHandler(handler);
  }

  CleanUpHandlers(): void {
    lib.symbols.wxBitmap_CleanUpHandlers();
  }

  CreateFromXPM(): Deno.PointerValue {
    return lib.symbols.wxBitmap_CreateFromXPM(this.#ptr);
  }

  FindHandlerByExtension(type_: number): Deno.PointerValue {
    return lib.symbols.wxBitmap_FindHandlerByExtension(this.#ptr, type_);
  }

  FindHandlerByName(name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxBitmap_FindHandlerByName(name);
  }

  FindHandlerByType(type_: number): Deno.PointerValue {
    return lib.symbols.wxBitmap_FindHandlerByType(type_);
  }

  GetDepth(): number {
    return lib.symbols.wxBitmap_GetDepth(this.#ptr);
  }

  GetHeight(): number {
    return lib.symbols.wxBitmap_GetHeight(this.#ptr);
  }

  GetMask(): Deno.PointerValue {
    return lib.symbols.wxBitmap_GetMask(this.#ptr);
  }

  GetSubBitmap(x: number, y: number, width: number, height: number, ref: Deno.PointerValue): void {
    lib.symbols.wxBitmap_GetSubBitmap(this.#ptr, x, y, width, height, ref);
  }

  GetWidth(): number {
    return lib.symbols.wxBitmap_GetWidth(this.#ptr);
  }

  InitStandardHandlers(): void {
    lib.symbols.wxBitmap_InitStandardHandlers();
  }

  InsertHandler(handler: Deno.PointerValue): void {
    lib.symbols.wxBitmap_InsertHandler(handler);
  }

  LoadFile(name: Deno.PointerValue, type_: number): number {
    return lib.symbols.wxBitmap_LoadFile(this.#ptr, name, type_);
  }

  IsOk(): boolean {
    return (lib.symbols.wxBitmap_IsOk(this.#ptr) as number) !== 0;
  }

  RemoveHandler(name: Deno.PointerValue): boolean {
    return (lib.symbols.wxBitmap_RemoveHandler(name) as number) !== 0;
  }

  SaveFile(name: Deno.PointerValue, type_: number, cmap: Deno.PointerValue): number {
    return lib.symbols.wxBitmap_SaveFile(this.#ptr, name, type_, cmap);
  }

  SetMask(mask: Deno.PointerValue): void {
    lib.symbols.wxBitmap_SetMask(this.#ptr, mask);
  }

}
