// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxComboBox } from "./wxComboBox_gen.ts";

export class wxBitmapComboBox extends wxComboBox {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, value: Deno.PointerValue, x: number, y: number, width: number, height: number, n: number, str: Deno.PointerValue, style: number): wxBitmapComboBox | null {
    const rawPtr = lib.symbols.wxBitmapComboBox_Create(parent, id, value, x, y, width, height, n, str, style);
    if (rawPtr === null) return null;
    return new wxBitmapComboBox(rawPtr);
  }

  Append(item: Deno.PointerValue, bitmap: Deno.PointerValue): void {
    lib.symbols.wxBitmapComboBox_Append(this._ptr, item, bitmap);
  }

  AppendWithClientData(item: Deno.PointerValue, bitmap: Deno.PointerValue, data: Deno.PointerValue): void {
    lib.symbols.wxBitmapComboBox_AppendWithClientData(this._ptr, item, bitmap, data);
  }

  Insert(item: Deno.PointerValue, bitmap: Deno.PointerValue, pos: number): void {
    lib.symbols.wxBitmapComboBox_Insert(this._ptr, item, bitmap, pos);
  }

  InsertWithClientData(item: Deno.PointerValue, bitmap: Deno.PointerValue, pos: number, data: Deno.PointerValue): void {
    lib.symbols.wxBitmapComboBox_InsertWithClientData(this._ptr, item, bitmap, pos, data);
  }

  GetItemBitmap(index: number): Deno.PointerValue {
    return lib.symbols.wxBitmapComboBox_GetItemBitmap(this._ptr, index);
  }

  SetItemBitmap(index: number, bitmap: Deno.PointerValue): void {
    lib.symbols.wxBitmapComboBox_SetItemBitmap(this._ptr, index, bitmap);
  }

  GetBitmapSize(): Deno.PointerValue {
    return lib.symbols.wxBitmapComboBox_GetBitmapSize(this._ptr);
  }

}
