// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxBookCtrlBase {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  CreateFromDefault(parent: Deno.PointerValue, winid: number, x: number, y: number, width: number, height: number, style: number, name: Deno.PointerValue): boolean {
    return (lib.symbols.wxBookCtrlBase_CreateFromDefault(this.#ptr, parent, winid, x, y, width, height, style, name) as number) !== 0;
  }

  SetPageSize(width: number, height: number): void {
    lib.symbols.wxBookCtrlBase_SetPageSize(this.#ptr, width, height);
  }

  HitTest(x: number, y: number, flags: Deno.PointerValue): number {
    return lib.symbols.wxBookCtrlBase_HitTest(this.#ptr, x, y, flags);
  }

  GetPageImage(nPage: bigint): number {
    return lib.symbols.wxBookCtrlBase_GetPageImage(this.#ptr, nPage);
  }

  SetPageImage(page: bigint, image: number): boolean {
    return (lib.symbols.wxBookCtrlBase_SetPageImage(this.#ptr, page, image) as number) !== 0;
  }

  GetPageText(nPage: bigint): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetPageText(this.#ptr, nPage);
  }

  SetPageText(page: bigint, text: Deno.PointerValue): boolean {
    return (lib.symbols.wxBookCtrlBase_SetPageText(this.#ptr, page, text) as number) !== 0;
  }

  GetSelection(): number {
    return lib.symbols.wxBookCtrlBase_GetSelection(this.#ptr);
  }

  GetCurrentPage(): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetCurrentPage(this.#ptr);
  }

  SetSelection(page: bigint): number {
    return lib.symbols.wxBookCtrlBase_SetSelection(this.#ptr, page);
  }

  AdvanceSelection(forward: boolean): void {
    lib.symbols.wxBookCtrlBase_AdvanceSelection(this.#ptr, forward ? 1 : 0);
  }

  ChangeSelection(page: bigint): number {
    return lib.symbols.wxBookCtrlBase_ChangeSelection(this.#ptr, page);
  }

  FindPage(page: Deno.PointerValue): number {
    return lib.symbols.wxBookCtrlBase_FindPage(this.#ptr, page);
  }

  AddPage(page: Deno.PointerValue, text: Deno.PointerValue, select: boolean, imageId: number): boolean {
    return (lib.symbols.wxBookCtrlBase_AddPage(this.#ptr, page, text, select ? 1 : 0, imageId) as number) !== 0;
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxBookCtrlBase_DeleteAllPages(this.#ptr) as number) !== 0;
  }

  DeletePage(page: bigint): boolean {
    return (lib.symbols.wxBookCtrlBase_DeletePage(this.#ptr, page) as number) !== 0;
  }

  InsertPage(index: bigint, page: Deno.PointerValue, text: Deno.PointerValue, select: boolean, imageId: number): boolean {
    return (lib.symbols.wxBookCtrlBase_InsertPage(this.#ptr, index, page, text, select ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(page: bigint): boolean {
    return (lib.symbols.wxBookCtrlBase_RemovePage(this.#ptr, page) as number) !== 0;
  }

  GetPageCount(): bigint {
    return lib.symbols.wxBookCtrlBase_GetPageCount(this.#ptr) as bigint;
  }

  GetPage(page: bigint): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetPage(this.#ptr, page);
  }

  AssignImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxBookCtrlBase_AssignImageList(this.#ptr, imageList);
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxBookCtrlBase_SetImageList(this.#ptr, imageList);
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetImageList(this.#ptr);
  }

}
