// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxPGProperty } from "./wxPGProperty_gen.ts";

export class wxBoolProperty extends wxPGProperty {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(label: Deno.PointerValue, name: Deno.PointerValue, value: boolean): wxBoolProperty | null {
    const rawPtr = lib.symbols.wxBoolProperty_Create(label, name, value ? 1 : 0);
    if (rawPtr === null) return null;
    return new wxBoolProperty(rawPtr);
  }

}
