// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxBoxSizer {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(orient: number): wxBoxSizer | null {
    const rawPtr = lib.symbols.wxBoxSizer_Create(orient);
    if (rawPtr === null) return null;
    return new wxBoxSizer(rawPtr);
  }

  CalcMin(): Deno.PointerValue {
    return lib.symbols.wxBoxSizer_CalcMin(this.#ptr);
  }

  GetOrientation(): number {
    return lib.symbols.wxBoxSizer_GetOrientation(this.#ptr);
  }

  RecalcSizes(): void {
    lib.symbols.wxBoxSizer_RecalcSizes(this.#ptr);
  }

}
