// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxBookCtrlBase extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  CreateFromDefault(parent: Deno.PointerValue, winid: number, x: number, y: number, width: number, height: number, style: number, name: Deno.PointerValue): boolean {
    return (lib.symbols.wxBookCtrlBase_CreateFromDefault(this._ptr, parent, winid, x, y, width, height, style, name) as number) !== 0;
  }

  SetPageSize(width: number, height: number): void {
    lib.symbols.wxBookCtrlBase_SetPageSize(this._ptr, width, height);
  }

  HitTest(x: number, y: number, flags: Deno.PointerValue): number {
    return lib.symbols.wxBookCtrlBase_HitTest(this._ptr, x, y, flags);
  }

  GetPageImage(nPage: bigint): number {
    return lib.symbols.wxBookCtrlBase_GetPageImage(this._ptr, nPage);
  }

  SetPageImage(page: bigint, image: number): boolean {
    return (lib.symbols.wxBookCtrlBase_SetPageImage(this._ptr, page, image) as number) !== 0;
  }

  GetPageText(nPage: bigint): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetPageText(this._ptr, nPage);
  }

  SetPageText(page: bigint, text: Deno.PointerValue): boolean {
    return (lib.symbols.wxBookCtrlBase_SetPageText(this._ptr, page, text) as number) !== 0;
  }

  GetSelection(): number {
    return lib.symbols.wxBookCtrlBase_GetSelection(this._ptr);
  }

  GetCurrentPage(): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetCurrentPage(this._ptr);
  }

  SetSelection(page: bigint): number {
    return lib.symbols.wxBookCtrlBase_SetSelection(this._ptr, page);
  }

  AdvanceSelection(forward: boolean): void {
    lib.symbols.wxBookCtrlBase_AdvanceSelection(this._ptr, forward ? 1 : 0);
  }

  ChangeSelection(page: bigint): number {
    return lib.symbols.wxBookCtrlBase_ChangeSelection(this._ptr, page);
  }

  FindPage(page: Deno.PointerValue): number {
    return lib.symbols.wxBookCtrlBase_FindPage(this._ptr, page);
  }

  AddPage(page: Deno.PointerValue, text: Deno.PointerValue, select: boolean, imageId: number): boolean {
    return (lib.symbols.wxBookCtrlBase_AddPage(this._ptr, page, text, select ? 1 : 0, imageId) as number) !== 0;
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxBookCtrlBase_DeleteAllPages(this._ptr) as number) !== 0;
  }

  DeletePage(page: bigint): boolean {
    return (lib.symbols.wxBookCtrlBase_DeletePage(this._ptr, page) as number) !== 0;
  }

  InsertPage(index: bigint, page: Deno.PointerValue, text: Deno.PointerValue, select: boolean, imageId: number): boolean {
    return (lib.symbols.wxBookCtrlBase_InsertPage(this._ptr, index, page, text, select ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(page: bigint): boolean {
    return (lib.symbols.wxBookCtrlBase_RemovePage(this._ptr, page) as number) !== 0;
  }

  GetPageCount(): bigint {
    return lib.symbols.wxBookCtrlBase_GetPageCount(this._ptr) as bigint;
  }

  GetPage(page: bigint): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetPage(this._ptr, page);
  }

  AssignImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxBookCtrlBase_AssignImageList(this._ptr, imageList);
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxBookCtrlBase_SetImageList(this._ptr, imageList);
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxBookCtrlBase_GetImageList(this._ptr);
  }

}
