// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxBufferedPaintDC {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(window: Deno.PointerValue, style: number): wxBufferedPaintDC | null {
    const rawPtr = lib.symbols.wxBufferedPaintDC_Create(window, style);
    if (rawPtr === null) return null;
    return new wxBufferedPaintDC(rawPtr);
  }

  static CreateWithBitmap(window: Deno.PointerValue, bitmap: Deno.PointerValue, style: number): wxBufferedPaintDC | null {
    const rawPtr = lib.symbols.wxBufferedPaintDC_CreateWithBitmap(window, bitmap, style);
    if (rawPtr === null) return null;
    return new wxBufferedPaintDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxBufferedPaintDC_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
