// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxBusyCursor {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxBusyCursor | null {
    const rawPtr = lib.symbols.wxBusyCursor_Create();
    if (rawPtr === null) return null;
    return new wxBusyCursor(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxBusyCursor_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  CreateWithCursor(): Deno.PointerValue {
    return lib.symbols.wxBusyCursor_CreateWithCursor(this.#ptr);
  }

}
