// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxCalendarDateAttr {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(textColour: Deno.PointerValue, backColour: Deno.PointerValue, borderColour: Deno.PointerValue, font: Deno.PointerValue, border: number): wxCalendarDateAttr | null {
    const rawPtr = lib.symbols.wxCalendarDateAttr_Create(textColour, backColour, borderColour, font, border);
    if (rawPtr === null) return null;
    return new wxCalendarDateAttr(rawPtr);
  }

  static CreateDefault(): wxCalendarDateAttr | null {
    const rawPtr = lib.symbols.wxCalendarDateAttr_CreateDefault();
    if (rawPtr === null) return null;
    return new wxCalendarDateAttr(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxCalendarDateAttr_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetBackgroundColour(ref: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_GetBackgroundColour(this.#ptr, ref);
  }

  GetBorder(): number {
    return lib.symbols.wxCalendarDateAttr_GetBorder(this.#ptr);
  }

  GetBorderColour(ref: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_GetBorderColour(this.#ptr, ref);
  }

  GetFont(ref: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_GetFont(this.#ptr, ref);
  }

  GetTextColour(ref: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_GetTextColour(this.#ptr, ref);
  }

  HasBackgroundColour(): boolean {
    return (lib.symbols.wxCalendarDateAttr_HasBackgroundColour(this.#ptr) as number) !== 0;
  }

  HasBorder(): boolean {
    return (lib.symbols.wxCalendarDateAttr_HasBorder(this.#ptr) as number) !== 0;
  }

  HasBorderColour(): boolean {
    return (lib.symbols.wxCalendarDateAttr_HasBorderColour(this.#ptr) as number) !== 0;
  }

  HasFont(): boolean {
    return (lib.symbols.wxCalendarDateAttr_HasFont(this.#ptr) as number) !== 0;
  }

  HasTextColour(): boolean {
    return (lib.symbols.wxCalendarDateAttr_HasTextColour(this.#ptr) as number) !== 0;
  }

  IsHoliday(): boolean {
    return (lib.symbols.wxCalendarDateAttr_IsHoliday(this.#ptr) as number) !== 0;
  }

  SetBackgroundColour(col: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_SetBackgroundColour(this.#ptr, col);
  }

  SetBorder(border: number): void {
    lib.symbols.wxCalendarDateAttr_SetBorder(this.#ptr, border);
  }

  SetBorderColour(col: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_SetBorderColour(this.#ptr, col);
  }

  SetFont(font: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_SetFont(this.#ptr, font);
  }

  SetHoliday(holiday: number): void {
    lib.symbols.wxCalendarDateAttr_SetHoliday(this.#ptr, holiday);
  }

  SetTextColour(col: Deno.PointerValue): void {
    lib.symbols.wxCalendarDateAttr_SetTextColour(this.#ptr, col);
  }

}
