// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxCalculateLayoutEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(id: number): wxCalculateLayoutEvent | null {
    const rawPtr = lib.symbols.wxCalculateLayoutEvent_Create(id);
    if (rawPtr === null) return null;
    return new wxCalculateLayoutEvent(rawPtr);
  }

  GetFlags(): number {
    return lib.symbols.wxCalculateLayoutEvent_GetFlags(this.#ptr);
  }

  GetRect(): Deno.PointerValue {
    return lib.symbols.wxCalculateLayoutEvent_GetRect(this.#ptr);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxCalculateLayoutEvent_SetFlags(this.#ptr, flags);
  }

  SetRect(x: number, y: number, width: number, height: number): void {
    lib.symbols.wxCalculateLayoutEvent_SetRect(this.#ptr, x, y, width, height);
  }

}
