// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxChoice extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, n: number, str: Deno.PointerValue, style: number): wxChoice | null {
    const rawPtr = lib.symbols.wxChoice_Create(parent, id, left, top, width, height, n, str, style);
    if (rawPtr === null) return null;
    return new wxChoice(rawPtr);
  }

  Append(item: Deno.PointerValue): void {
    lib.symbols.wxChoice_Append(this._ptr, item);
  }

  Clear(): void {
    lib.symbols.wxChoice_Clear(this._ptr);
  }

  Delete(index: number): void {
    lib.symbols.wxChoice_Delete(this._ptr, index);
  }

  FindString(str: Deno.PointerValue): number {
    return lib.symbols.wxChoice_FindString(this._ptr, str);
  }

  GetCount(): number {
    return lib.symbols.wxChoice_GetCount(this._ptr);
  }

  GetSelection(): number {
    return lib.symbols.wxChoice_GetSelection(this._ptr);
  }

  GetString(index: number): Deno.PointerValue {
    return lib.symbols.wxChoice_GetString(this._ptr, index);
  }

  SetSelection(index: number): void {
    lib.symbols.wxChoice_SetSelection(this._ptr, index);
  }

  SetString(index: number, str: Deno.PointerValue): void {
    lib.symbols.wxChoice_SetString(this._ptr, index, str);
  }

  SetColumns(n: number): void {
    lib.symbols.wxChoice_SetColumns(this._ptr, n);
  }

  GetColumns(): number {
    return lib.symbols.wxChoice_GetColumns(this._ptr);
  }

  GetCurrentSelection(): number {
    return lib.symbols.wxChoice_GetCurrentSelection(this._ptr);
  }

}
