// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxCheckBox {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxCheckBox | null {
    const rawPtr = lib.symbols.wxCheckBox_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxCheckBox(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxCheckBox_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetValue(): boolean {
    return (lib.symbols.wxCheckBox_GetValue(this.#ptr) as number) !== 0;
  }

  SetValue(value: boolean): void {
    lib.symbols.wxCheckBox_SetValue(this.#ptr, value ? 1 : 0);
  }

  Get3StateValue(): number {
    return lib.symbols.wxCheckBox_Get3StateValue(this.#ptr);
  }

  Is3State(): boolean {
    return (lib.symbols.wxCheckBox_Is3State(this.#ptr) as number) !== 0;
  }

  Set3StateValue(state: number): void {
    lib.symbols.wxCheckBox_Set3StateValue(this.#ptr, state);
  }

  Is3rdStateAllowedForUser(): boolean {
    return (lib.symbols.wxCheckBox_Is3rdStateAllowedForUser(this.#ptr) as number) !== 0;
  }

}
