// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxChoicebook {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxChoicebook | null {
    const rawPtr = lib.symbols.wxChoicebook_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxChoicebook(rawPtr);
  }

  AddPage(pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxChoicebook_AddPage(this.#ptr, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  AdvanceSelection(bForward: boolean): void {
    lib.symbols.wxChoicebook_AdvanceSelection(this.#ptr, bForward ? 1 : 0);
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxChoicebook_DeleteAllPages(this.#ptr) as number) !== 0;
  }

  DeletePage(nPage: number): boolean {
    return (lib.symbols.wxChoicebook_DeletePage(this.#ptr, nPage) as number) !== 0;
  }

  GetChoiceCtrl(): Deno.PointerValue {
    return lib.symbols.wxChoicebook_GetChoiceCtrl(this.#ptr);
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxChoicebook_GetImageList(this.#ptr);
  }

  GetPage(nPage: number): Deno.PointerValue {
    return lib.symbols.wxChoicebook_GetPage(this.#ptr, nPage);
  }

  GetPageCount(): number {
    return lib.symbols.wxChoicebook_GetPageCount(this.#ptr);
  }

  GetPageImage(nPage: number): number {
    return lib.symbols.wxChoicebook_GetPageImage(this.#ptr, nPage);
  }

  GetPageText(nPage: number): Deno.PointerValue {
    return lib.symbols.wxChoicebook_GetPageText(this.#ptr, nPage);
  }

  GetSelection(): number {
    return lib.symbols.wxChoicebook_GetSelection(this.#ptr);
  }

  HitTest(x: number, y: number, flags: Deno.PointerValue): number {
    return lib.symbols.wxChoicebook_HitTest(this.#ptr, x, y, flags);
  }

  InsertPage(nPage: number, pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxChoicebook_InsertPage(this.#ptr, nPage, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(nPage: number): boolean {
    return (lib.symbols.wxChoicebook_RemovePage(this.#ptr, nPage) as number) !== 0;
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxChoicebook_SetImageList(this.#ptr, imageList);
  }

  SetPageImage(nPage: number, nImage: number): boolean {
    return (lib.symbols.wxChoicebook_SetPageImage(this.#ptr, nPage, nImage) as number) !== 0;
  }

  SetPageText(nPage: number, strText: Deno.PointerValue): boolean {
    return (lib.symbols.wxChoicebook_SetPageText(this.#ptr, nPage, strText) as number) !== 0;
  }

  SetSelection(nPage: number): number {
    return lib.symbols.wxChoicebook_SetSelection(this.#ptr, nPage);
  }

}
