// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxClassInfo {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  CreateClassByName(): Deno.PointerValue {
    return lib.symbols.wxClassInfo_CreateClassByName(this.#ptr);
  }

  GetClassName(): Deno.PointerValue {
    return lib.symbols.wxClassInfo_GetClassName(this.#ptr);
  }

  IsKindOf(name: Deno.PointerValue): boolean {
    return (lib.symbols.wxClassInfo_IsKindOf(this.#ptr, name) as number) !== 0;
  }

}
