// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxWindowDC } from "./wxWindowDC_gen.ts";

export class wxClientDC extends wxWindowDC {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(win: Deno.PointerValue): wxClientDC | null {
    const rawPtr = lib.symbols.wxClientDC_Create(win);
    if (rawPtr === null) return null;
    return new wxClientDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxClientDC_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
