// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxClosure {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(fun: Deno.PointerValue, data: Deno.PointerValue): wxClosure | null {
    const rawPtr = lib.symbols.wxClosure_Create(fun, data);
    if (rawPtr === null) return null;
    return new wxClosure(rawPtr);
  }

  GetData(): Deno.PointerValue {
    return lib.symbols.wxClosure_GetData(this.#ptr);
  }

}
