// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxContextHelpButton {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxContextHelpButton | null {
    const rawPtr = lib.symbols.wxContextHelpButton_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxContextHelpButton(rawPtr);
  }

}
