// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxCommandLinkButton {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, mainLabel: Deno.PointerValue, note: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxCommandLinkButton | null {
    const rawPtr = lib.symbols.wxCommandLinkButton_Create(parent, id, mainLabel, note, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxCommandLinkButton(rawPtr);
  }

  SetMainLabel(mainLabel: Deno.PointerValue): void {
    lib.symbols.wxCommandLinkButton_SetMainLabel(this.#ptr, mainLabel);
  }

  SetNote(note: Deno.PointerValue): void {
    lib.symbols.wxCommandLinkButton_SetNote(this.#ptr, note);
  }

  GetMainLabel(): Deno.PointerValue {
    return lib.symbols.wxCommandLinkButton_GetMainLabel(this.#ptr);
  }

  GetNote(): Deno.PointerValue {
    return lib.symbols.wxCommandLinkButton_GetNote(this.#ptr);
  }

  SetMainLabelAndNote(mainLabel: Deno.PointerValue, note: Deno.PointerValue): void {
    lib.symbols.wxCommandLinkButton_SetMainLabelAndNote(this.#ptr, mainLabel, note);
  }

}
