// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxCollapsiblePane {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, label: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxCollapsiblePane | null {
    const rawPtr = lib.symbols.wxCollapsiblePane_Create(parent, id, label, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxCollapsiblePane(rawPtr);
  }

  Collapse(collapse: boolean): void {
    lib.symbols.wxCollapsiblePane_Collapse(this.#ptr, collapse ? 1 : 0);
  }

  Expand(): void {
    lib.symbols.wxCollapsiblePane_Expand(this.#ptr);
  }

  IsCollapsed(): boolean {
    return (lib.symbols.wxCollapsiblePane_IsCollapsed(this.#ptr) as number) !== 0;
  }

  IsExpanded(): boolean {
    return (lib.symbols.wxCollapsiblePane_IsExpanded(this.#ptr) as number) !== 0;
  }

  GetPane(): Deno.PointerValue {
    return lib.symbols.wxCollapsiblePane_GetPane(this.#ptr);
  }

  GetLabel(): Deno.PointerValue {
    return lib.symbols.wxCollapsiblePane_GetLabel(this.#ptr);
  }

  SetLabel(label: Deno.PointerValue): void {
    lib.symbols.wxCollapsiblePane_SetLabel(this.#ptr, label);
  }

}
