// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxChoice } from "./wxChoice_gen.ts";

export class wxComboBox extends wxChoice {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, n: number, str: Deno.PointerValue, style: number): wxComboBox | null {
    const rawPtr = lib.symbols.wxComboBox_Create(parent, id, text, left, top, width, height, n, str, style);
    if (rawPtr === null) return null;
    return new wxComboBox(rawPtr);
  }

  Append(item: Deno.PointerValue): void {
    lib.symbols.wxComboBox_Append(this._ptr, item);
  }

  AppendData(item: Deno.PointerValue, clientData: Deno.PointerValue): void {
    lib.symbols.wxComboBox_AppendData(this._ptr, item, clientData);
  }

  Clear(): void {
    lib.symbols.wxComboBox_Clear(this._ptr);
  }

  Copy(): void {
    lib.symbols.wxComboBox_Copy(this._ptr);
  }

  Cut(): void {
    lib.symbols.wxComboBox_Cut(this._ptr);
  }

  Delete(index: number): void {
    lib.symbols.wxComboBox_Delete(this._ptr, index);
  }

  FindString(str: Deno.PointerValue): number {
    return lib.symbols.wxComboBox_FindString(this._ptr, str);
  }

  GetClientData(index: number): Deno.PointerValue {
    return lib.symbols.wxComboBox_GetClientData(this._ptr, index);
  }

  GetCount(): number {
    return lib.symbols.wxComboBox_GetCount(this._ptr);
  }

  GetInsertionPoint(): number {
    return lib.symbols.wxComboBox_GetInsertionPoint(this._ptr);
  }

  GetLastPosition(): number {
    return lib.symbols.wxComboBox_GetLastPosition(this._ptr);
  }

  GetSelection(): number {
    return lib.symbols.wxComboBox_GetSelection(this._ptr);
  }

  GetString(index: number): Deno.PointerValue {
    return lib.symbols.wxComboBox_GetString(this._ptr, index);
  }

  GetStringSelection(): Deno.PointerValue {
    return lib.symbols.wxComboBox_GetStringSelection(this._ptr);
  }

  GetValue(): Deno.PointerValue {
    return lib.symbols.wxComboBox_GetValue(this._ptr);
  }

  SetValue(value: Deno.PointerValue): void {
    lib.symbols.wxComboBox_SetValue(this._ptr, value);
  }

  Paste(): void {
    lib.symbols.wxComboBox_Paste(this._ptr);
  }

  Remove(from_: number, toPos: number): void {
    lib.symbols.wxComboBox_Remove(this._ptr, from_, toPos);
  }

  Replace(from_: number, toPos: number, value: Deno.PointerValue): void {
    lib.symbols.wxComboBox_Replace(this._ptr, from_, toPos, value);
  }

  SetClientData(index: number, clientData: Deno.PointerValue): void {
    lib.symbols.wxComboBox_SetClientData(this._ptr, index, clientData);
  }

  SetEditable(editable: boolean): void {
    lib.symbols.wxComboBox_SetEditable(this._ptr, editable ? 1 : 0);
  }

  SetInsertionPoint(pos: number): void {
    lib.symbols.wxComboBox_SetInsertionPoint(this._ptr, pos);
  }

  SetInsertionPointEnd(): void {
    lib.symbols.wxComboBox_SetInsertionPointEnd(this._ptr);
  }

  SetSelection(index: number): void {
    lib.symbols.wxComboBox_SetSelection(this._ptr, index);
  }

  SetString(index: number, str: Deno.PointerValue): void {
    lib.symbols.wxComboBox_SetString(this._ptr, index, str);
  }

  SetTextSelection(from_: number, toPos: number): void {
    lib.symbols.wxComboBox_SetTextSelection(this._ptr, from_, toPos);
  }

}
