// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxContextHelp {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(win: Deno.PointerValue, beginHelp: boolean): wxContextHelp | null {
    const rawPtr = lib.symbols.wxContextHelp_Create(win, beginHelp ? 1 : 0);
    if (rawPtr === null) return null;
    return new wxContextHelp(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxContextHelp_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  BeginContextHelp(win: Deno.PointerValue): boolean {
    return (lib.symbols.wxContextHelp_BeginContextHelp(this.#ptr, win) as number) !== 0;
  }

  EndContextHelp(): boolean {
    return (lib.symbols.wxContextHelp_EndContextHelp(this.#ptr) as number) !== 0;
  }

}
