// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxColourData {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxColourData | null {
    const rawPtr = lib.symbols.wxColourData_Create();
    if (rawPtr === null) return null;
    return new wxColourData(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxColourData_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetChooseFull(): boolean {
    return (lib.symbols.wxColourData_GetChooseFull(this.#ptr) as number) !== 0;
  }

  GetColour(ref: Deno.PointerValue): void {
    lib.symbols.wxColourData_GetColour(this.#ptr, ref);
  }

  GetCustomColour(index: number, ref: Deno.PointerValue): void {
    lib.symbols.wxColourData_GetCustomColour(this.#ptr, index, ref);
  }

  SetChooseFull(flag: boolean): void {
    lib.symbols.wxColourData_SetChooseFull(this.#ptr, flag ? 1 : 0);
  }

  SetColour(colour: Deno.PointerValue): void {
    lib.symbols.wxColourData_SetColour(this.#ptr, colour);
  }

  SetCustomColour(index: number, colour: Deno.PointerValue): void {
    lib.symbols.wxColourData_SetCustomColour(this.#ptr, index, colour);
  }

}
