// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxCriticalSection {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxCriticalSection | null {
    const rawPtr = lib.symbols.wxCriticalSection_Create();
    if (rawPtr === null) return null;
    return new wxCriticalSection(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxCriticalSection_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Enter(): void {
    lib.symbols.wxCriticalSection_Enter(this._ptr);
  }

  Leave(): void {
    lib.symbols.wxCriticalSection_Leave(this._ptr);
  }

}
