// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDataViewItem {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(id: Deno.PointerValue): wxDataViewItem | null {
    const rawPtr = lib.symbols.wxDataViewItem_Create(id);
    if (rawPtr === null) return null;
    return new wxDataViewItem(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxDataViewItem_Delete(this._ptr);
  }

  GetID(): Deno.PointerValue {
    return lib.symbols.wxDataViewItem_GetID(this._ptr);
  }

  IsOk(): boolean {
    return (lib.symbols.wxDataViewItem_IsOk(this._ptr) as number) !== 0;
  }

}
