// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDatePickerCtrl {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxDatePickerCtrl | null {
    const rawPtr = lib.symbols.wxDatePickerCtrl_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxDatePickerCtrl(rawPtr);
  }

  SetValue(dateTime: Deno.PointerValue): void {
    lib.symbols.wxDatePickerCtrl_SetValue(this.#ptr, dateTime);
  }

  GetValue(dateTime: Deno.PointerValue): void {
    lib.symbols.wxDatePickerCtrl_GetValue(this.#ptr, dateTime);
  }

  SetRange(dt1: Deno.PointerValue, dt2: Deno.PointerValue): void {
    lib.symbols.wxDatePickerCtrl_SetRange(this.#ptr, dt1, dt2);
  }

  GetRange(dt1: Deno.PointerValue, dt2: Deno.PointerValue): boolean {
    return (lib.symbols.wxDatePickerCtrl_GetRange(this.#ptr, dt1, dt2) as number) !== 0;
  }

}
