// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDataViewItemArray {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxDataViewItemArray | null {
    const rawPtr = lib.symbols.wxDataViewItemArray_Create();
    if (rawPtr === null) return null;
    return new wxDataViewItemArray(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxDataViewItemArray_Delete(this._ptr);
  }

  GetCount(): bigint {
    return lib.symbols.wxDataViewItemArray_GetCount(this._ptr) as bigint;
  }

  Item(index: bigint, item: Deno.PointerValue): void {
    lib.symbols.wxDataViewItemArray_Item(this._ptr, index, item);
  }

  Add(item: Deno.PointerValue): void {
    lib.symbols.wxDataViewItemArray_Add(this._ptr, item);
  }

  Clear(): void {
    lib.symbols.wxDataViewItemArray_Clear(this._ptr);
  }

}
