// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDateTime {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxDateTime | null {
    const rawPtr = lib.symbols.wxDateTime_Create();
    if (rawPtr === null) return null;
    return new wxDateTime(rawPtr);
  }

  AddDate(diff: Deno.PointerValue, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_AddDate(this.#ptr, diff, ref);
  }

  AddDateValues(years: number, month: number, week: number, day: number): void {
    lib.symbols.wxDateTime_AddDateValues(this.#ptr, years, month, week, day);
  }

  AddTime(diff: Deno.PointerValue, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_AddTime(this.#ptr, diff, ref);
  }

  AddTimeValues(hours: number, minVal: number, seconds: number, milliseconds: number): void {
    lib.symbols.wxDateTime_AddTimeValues(this.#ptr, hours, minVal, seconds, milliseconds);
  }

  ConvertYearToBC(year: number): number {
    return lib.symbols.wxDateTime_ConvertYearToBC(year);
  }

  Format(format: Deno.PointerValue, timeZone: number): Deno.PointerValue {
    return lib.symbols.wxDateTime_Format(this.#ptr, format, timeZone);
  }

  FormatDate(): Deno.PointerValue {
    return lib.symbols.wxDateTime_FormatDate(this.#ptr);
  }

  FormatISODate(): Deno.PointerValue {
    return lib.symbols.wxDateTime_FormatISODate(this.#ptr);
  }

  FormatISOTime(): Deno.PointerValue {
    return lib.symbols.wxDateTime_FormatISOTime(this.#ptr);
  }

  FormatTime(): Deno.PointerValue {
    return lib.symbols.wxDateTime_FormatTime(this.#ptr);
  }

  GetAmString(): Deno.PointerValue {
    return lib.symbols.wxDateTime_GetAmString();
  }

  GetBeginDST(year: number, country: number, dateTime: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetBeginDST(year, country, dateTime);
  }

  GetCentury(year: number): number {
    return lib.symbols.wxDateTime_GetCentury(year);
  }

  GetCountry(): number {
    return lib.symbols.wxDateTime_GetCountry();
  }

  GetCurrentMonth(cal: number): number {
    return lib.symbols.wxDateTime_GetCurrentMonth(cal);
  }

  GetCurrentYear(cal: number): number {
    return lib.symbols.wxDateTime_GetCurrentYear(cal);
  }

  GetDay(timeZone: number): number {
    return lib.symbols.wxDateTime_GetDay(this.#ptr, timeZone);
  }

  GetDayOfYear(timeZone: number): number {
    return lib.symbols.wxDateTime_GetDayOfYear(this.#ptr, timeZone);
  }

  GetEndDST(year: number, country: number, dateTime: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetEndDST(year, country, dateTime);
  }

  GetHour(timeZone: number): number {
    return lib.symbols.wxDateTime_GetHour(this.#ptr, timeZone);
  }

  GetLastMonthDay(month: number, year: number, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetLastMonthDay(this.#ptr, month, year, ref);
  }

  GetLastWeekDay(weekday: number, month: number, year: number, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetLastWeekDay(this.#ptr, weekday, month, year, ref);
  }

  GetMillisecond(timeZone: number): number {
    return lib.symbols.wxDateTime_GetMillisecond(this.#ptr, timeZone);
  }

  GetMinute(timeZone: number): number {
    return lib.symbols.wxDateTime_GetMinute(this.#ptr, timeZone);
  }

  GetMonth(timeZone: number): number {
    return lib.symbols.wxDateTime_GetMonth(this.#ptr, timeZone);
  }

  GetMonthName(month: number, flags: number): Deno.PointerValue {
    return lib.symbols.wxDateTime_GetMonthName(month, flags);
  }

  GetNextWeekDay(weekday: number, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetNextWeekDay(this.#ptr, weekday, ref);
  }

  GetNumberOfDays(year: number, cal: number): number {
    return lib.symbols.wxDateTime_GetNumberOfDays(year, cal);
  }

  GetNumberOfDaysMonth(month: number, year: number, cal: number): number {
    return lib.symbols.wxDateTime_GetNumberOfDaysMonth(month, year, cal);
  }

  GetPmString(): Deno.PointerValue {
    return lib.symbols.wxDateTime_GetPmString();
  }

  GetPrevWeekDay(weekday: number, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetPrevWeekDay(this.#ptr, weekday, ref);
  }

  GetSecond(timeZone: number): number {
    return lib.symbols.wxDateTime_GetSecond(this.#ptr, timeZone);
  }

  GetTicks(): number {
    return lib.symbols.wxDateTime_GetTicks(this.#ptr);
  }

  GetTimeNow(): number {
    return lib.symbols.wxDateTime_GetTimeNow();
  }

  GetValue(hi_long: Deno.PointerValue, lo_long: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetValue(this.#ptr, hi_long, lo_long);
  }

  GetWeekDay(weekday: number, nthWeek: number, month: number, year: number, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetWeekDay(this.#ptr, weekday, nthWeek, month, year, ref);
  }

  GetWeekDayInSameWeek(weekday: number, flags: number, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_GetWeekDayInSameWeek(this.#ptr, weekday, flags, ref);
  }

  GetWeekDayName(weekday: number, flags: number): Deno.PointerValue {
    return lib.symbols.wxDateTime_GetWeekDayName(weekday, flags);
  }

  GetWeekDayTZ(timeZone: number): number {
    return lib.symbols.wxDateTime_GetWeekDayTZ(this.#ptr, timeZone);
  }

  GetWeekOfMonth(flags: number, timeZone: number): number {
    return lib.symbols.wxDateTime_GetWeekOfMonth(this.#ptr, flags, timeZone);
  }

  GetWeekOfYear(flags: number, timeZone: number): number {
    return lib.symbols.wxDateTime_GetWeekOfYear(this.#ptr, flags, timeZone);
  }

  GetYear(timeZone: number): number {
    return lib.symbols.wxDateTime_GetYear(this.#ptr, timeZone);
  }

  IsBetween(t1: Deno.PointerValue, t2: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsBetween(this.#ptr, t1, t2) as number) !== 0;
  }

  IsDST(country: number): boolean {
    return (lib.symbols.wxDateTime_IsDST(this.#ptr, country) as number) !== 0;
  }

  IsDSTApplicable(year: number, country: number): boolean {
    return (lib.symbols.wxDateTime_IsDSTApplicable(year, country) as number) !== 0;
  }

  IsEarlierThan(datetime: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsEarlierThan(this.#ptr, datetime) as number) !== 0;
  }

  IsEqualTo(datetime: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsEqualTo(this.#ptr, datetime) as number) !== 0;
  }

  IsEqualUpTo(dateTime: Deno.PointerValue, timeSpan: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsEqualUpTo(this.#ptr, dateTime, timeSpan) as number) !== 0;
  }

  IsLaterThan(datetime: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsLaterThan(this.#ptr, datetime) as number) !== 0;
  }

  IsLeapYear(year: number, cal: number): boolean {
    return (lib.symbols.wxDateTime_IsLeapYear(year, cal) as number) !== 0;
  }

  IsSameDate(dateTime: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsSameDate(this.#ptr, dateTime) as number) !== 0;
  }

  IsSameTime(dateTime: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsSameTime(this.#ptr, dateTime) as number) !== 0;
  }

  IsStrictlyBetween(t1: Deno.PointerValue, t2: Deno.PointerValue): boolean {
    return (lib.symbols.wxDateTime_IsStrictlyBetween(this.#ptr, t1, t2) as number) !== 0;
  }

  IsValid(): boolean {
    return (lib.symbols.wxDateTime_IsValid(this.#ptr) as number) !== 0;
  }

  IsWestEuropeanCountry(country: number): boolean {
    return (lib.symbols.wxDateTime_IsWestEuropeanCountry(country) as number) !== 0;
  }

  IsWorkDay(country: number): boolean {
    return (lib.symbols.wxDateTime_IsWorkDay(this.#ptr, country) as number) !== 0;
  }

  MakeGMT(noDST: number): void {
    lib.symbols.wxDateTime_MakeGMT(this.#ptr, noDST);
  }

  MakeTimezone(timeZone: number, noDST: number): void {
    lib.symbols.wxDateTime_MakeTimezone(this.#ptr, timeZone, noDST);
  }

  Now(): void {
    lib.symbols.wxDateTime_Now(this.#ptr);
  }

  ParseDate(date: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxDateTime_ParseDate(this.#ptr, date);
  }

  ParseDateTime(datetime: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxDateTime_ParseDateTime(this.#ptr, datetime);
  }

  ParseFormat(date: Deno.PointerValue, format: Deno.PointerValue, dateDef: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxDateTime_ParseFormat(this.#ptr, date, format, dateDef);
  }

  ParseRfc822Date(date: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxDateTime_ParseRfc822Date(this.#ptr, date);
  }

  ParseTime(time: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxDateTime_ParseTime(this.#ptr, time);
  }

  ResetTime(): void {
    lib.symbols.wxDateTime_ResetTime(this.#ptr);
  }

  Set(day: number, month: number, year: number, hour: number, minute: number, second: number, millisec: number): void {
    lib.symbols.wxDateTime_Set(this.#ptr, day, month, year, hour, minute, second, millisec);
  }

  SetCountry(country: number): void {
    lib.symbols.wxDateTime_SetCountry(country);
  }

  SetDay(day: number): void {
    lib.symbols.wxDateTime_SetDay(this.#ptr, day);
  }

  SetHour(hour: number): void {
    lib.symbols.wxDateTime_SetHour(this.#ptr, hour);
  }

  SetMillisecond(millisecond: number): void {
    lib.symbols.wxDateTime_SetMillisecond(this.#ptr, millisecond);
  }

  SetMinute(minute: number): void {
    lib.symbols.wxDateTime_SetMinute(this.#ptr, minute);
  }

  SetMonth(month: number): void {
    lib.symbols.wxDateTime_SetMonth(this.#ptr, month);
  }

  SetSecond(second: number): void {
    lib.symbols.wxDateTime_SetSecond(this.#ptr, second);
  }

  SetTime(hour: number, minute: number, second: number, millisec: number): void {
    lib.symbols.wxDateTime_SetTime(this.#ptr, hour, minute, second, millisec);
  }

  SetToCurrent(): void {
    lib.symbols.wxDateTime_SetToCurrent(this.#ptr);
  }

  SetToLastMonthDay(month: number, year: number): void {
    lib.symbols.wxDateTime_SetToLastMonthDay(this.#ptr, month, year);
  }

  SetToLastWeekDay(weekday: number, month: number, year: number): boolean {
    return (lib.symbols.wxDateTime_SetToLastWeekDay(this.#ptr, weekday, month, year) as number) !== 0;
  }

  SetToNextWeekDay(weekday: number): void {
    lib.symbols.wxDateTime_SetToNextWeekDay(this.#ptr, weekday);
  }

  SetToPrevWeekDay(weekday: number): void {
    lib.symbols.wxDateTime_SetToPrevWeekDay(this.#ptr, weekday);
  }

  SetToWeekDay(weekday: number, nthWeek: number, month: number, year: number): boolean {
    return (lib.symbols.wxDateTime_SetToWeekDay(this.#ptr, weekday, nthWeek, month, year) as number) !== 0;
  }

  SetToWeekDayInSameWeek(weekday: number, flags: number): void {
    lib.symbols.wxDateTime_SetToWeekDayInSameWeek(this.#ptr, weekday, flags);
  }

  SetYear(year: number): void {
    lib.symbols.wxDateTime_SetYear(this.#ptr, year);
  }

  SubtractDate(diff: Deno.PointerValue, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_SubtractDate(this.#ptr, diff, ref);
  }

  SubtractTime(diff: Deno.PointerValue, ref: Deno.PointerValue): void {
    lib.symbols.wxDateTime_SubtractTime(this.#ptr, diff, ref);
  }

  ToGMT(noDST: number): void {
    lib.symbols.wxDateTime_ToGMT(this.#ptr, noDST);
  }

  ToTimezone(timeZone: number, noDST: number): void {
    lib.symbols.wxDateTime_ToTimezone(this.#ptr, timeZone, noDST);
  }

  Today(): void {
    lib.symbols.wxDateTime_Today(this.#ptr);
  }

  UNow(): void {
    lib.symbols.wxDateTime_UNow(this.#ptr);
  }

  wxDateTime(hi_long: number, lo_long: number): Deno.PointerValue {
    return lib.symbols.wxDateTime_wxDateTime(hi_long, lo_long);
  }

}
