// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDataObjectComposite {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxDataObjectComposite | null {
    const rawPtr = lib.symbols.wxDataObjectComposite_Create();
    if (rawPtr === null) return null;
    return new wxDataObjectComposite(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxDataObjectComposite_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Add(data: Deno.PointerValue, preferred: number): void {
    lib.symbols.wxDataObjectComposite_Add(this._ptr, data, preferred);
  }

}
