// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxTopLevelWindow } from "./wxTopLevelWindow_gen.ts";

export class wxDialog extends wxTopLevelWindow {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxDialog | null {
    const rawPtr = lib.symbols.wxDialog_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxDialog(rawPtr);
  }

  EndModal(retCode: number): void {
    lib.symbols.wxDialog_EndModal(this._ptr, retCode);
  }

  GetReturnCode(): number {
    return lib.symbols.wxDialog_GetReturnCode(this._ptr);
  }

  IsModal(): boolean {
    return (lib.symbols.wxDialog_IsModal(this._ptr) as number) !== 0;
  }

  SetReturnCode(returnCode: number): void {
    lib.symbols.wxDialog_SetReturnCode(this._ptr, returnCode);
  }

  ShowModal(): number {
    return lib.symbols.wxDialog_ShowModal(this._ptr);
  }

  SetAffirmativeId(id: number): void {
    lib.symbols.wxDialog_SetAffirmativeId(this._ptr, id);
  }

  GetAffirmativeId(): number {
    return lib.symbols.wxDialog_GetAffirmativeId(this._ptr);
  }

  SetEscapeId(id: number): void {
    lib.symbols.wxDialog_SetEscapeId(this._ptr, id);
  }

  GetEscapeId(): number {
    return lib.symbols.wxDialog_GetEscapeId(this._ptr);
  }

  CreateButtonSizer(flags: number): Deno.PointerValue {
    return lib.symbols.wxDialog_CreateButtonSizer(this._ptr, flags);
  }

  CreateSeparatedButtonSizer(flags: number): Deno.PointerValue {
    return lib.symbols.wxDialog_CreateSeparatedButtonSizer(this._ptr, flags);
  }

  CreateStdDialogButtonSizer(flags: number): Deno.PointerValue {
    return lib.symbols.wxDialog_CreateStdDialogButtonSizer(this._ptr, flags);
  }

}
