// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDialog {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxDialog | null {
    const rawPtr = lib.symbols.wxDialog_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxDialog(rawPtr);
  }

  EndModal(retCode: number): void {
    lib.symbols.wxDialog_EndModal(this.#ptr, retCode);
  }

  GetReturnCode(): number {
    return lib.symbols.wxDialog_GetReturnCode(this.#ptr);
  }

  IsModal(): boolean {
    return (lib.symbols.wxDialog_IsModal(this.#ptr) as number) !== 0;
  }

  SetReturnCode(returnCode: number): void {
    lib.symbols.wxDialog_SetReturnCode(this.#ptr, returnCode);
  }

  ShowModal(): number {
    return lib.symbols.wxDialog_ShowModal(this.#ptr);
  }

  SetAffirmativeId(id: number): void {
    lib.symbols.wxDialog_SetAffirmativeId(this.#ptr, id);
  }

  GetAffirmativeId(): number {
    return lib.symbols.wxDialog_GetAffirmativeId(this.#ptr);
  }

  SetEscapeId(id: number): void {
    lib.symbols.wxDialog_SetEscapeId(this.#ptr, id);
  }

  GetEscapeId(): number {
    return lib.symbols.wxDialog_GetEscapeId(this.#ptr);
  }

  CreateButtonSizer(flags: number): Deno.PointerValue {
    return lib.symbols.wxDialog_CreateButtonSizer(this.#ptr, flags);
  }

  CreateSeparatedButtonSizer(flags: number): Deno.PointerValue {
    return lib.symbols.wxDialog_CreateSeparatedButtonSizer(this.#ptr, flags);
  }

  CreateStdDialogButtonSizer(flags: number): Deno.PointerValue {
    return lib.symbols.wxDialog_CreateStdDialogButtonSizer(this.#ptr, flags);
  }

}
