// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxMDIParentFrame } from "./wxMDIParentFrame_gen.ts";

export class wxDocMDIParentFrame extends wxMDIParentFrame {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(manager: Deno.PointerValue, parent: Deno.PointerValue, id: number, title: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxDocMDIParentFrame | null {
    const rawPtr = lib.symbols.wxDocMDIParentFrame_Create(manager, parent, id, title, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxDocMDIParentFrame(rawPtr);
  }

  GetDocumentManager(): Deno.PointerValue {
    return lib.symbols.wxDocMDIParentFrame_GetDocumentManager(this._ptr);
  }

}
