// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxDocChildFrame {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(doc: Deno.PointerValue, view: Deno.PointerValue, parent: Deno.PointerValue, id: number, title: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxDocChildFrame | null {
    const rawPtr = lib.symbols.wxDocChildFrame_Create(doc, view, parent, id, title, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxDocChildFrame(rawPtr);
  }

  GetDocument(): Deno.PointerValue {
    return lib.symbols.wxDocChildFrame_GetDocument(this.#ptr);
  }

  GetView(): Deno.PointerValue {
    return lib.symbols.wxDocChildFrame_GetView(this.#ptr);
  }

  SetDocument(doc: Deno.PointerValue): void {
    lib.symbols.wxDocChildFrame_SetDocument(this.#ptr, doc);
  }

  SetView(view: Deno.PointerValue): void {
    lib.symbols.wxDocChildFrame_SetView(this.#ptr, view);
  }

}
