// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxWindow } from "./wxWindow_gen.ts";

export class wxDrawWindow extends wxWindow {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxDrawWindow | null {
    const rawPtr = lib.symbols.wxDrawWindow_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxDrawWindow(rawPtr);
  }

}
