// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxEncodingConverter {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxEncodingConverter | null {
    const rawPtr = lib.symbols.wxEncodingConverter_Create();
    if (rawPtr === null) return null;
    return new wxEncodingConverter(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxEncodingConverter_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Convert(input: Deno.PointerValue, output: Deno.PointerValue): void {
    lib.symbols.wxEncodingConverter_Convert(this._ptr, input, output);
  }

  GetAllEquivalents(enc: number, list: Deno.PointerValue): number {
    return lib.symbols.wxEncodingConverter_GetAllEquivalents(this._ptr, enc, list);
  }

  GetPlatformEquivalents(enc: number, platform: number, list: Deno.PointerValue): number {
    return lib.symbols.wxEncodingConverter_GetPlatformEquivalents(this._ptr, enc, platform, list);
  }

  Init(input_enc: number, output_enc: number, method: number): number {
    return lib.symbols.wxEncodingConverter_Init(this._ptr, input_enc, output_enc, method);
  }

}
