// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxFilePickerCtrl {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, path: Deno.PointerValue, message: Deno.PointerValue, wildcard: Deno.PointerValue, style: number): wxFilePickerCtrl | null {
    const rawPtr = lib.symbols.wxFilePickerCtrl_Create(parent, id, x, y, width, height, path, message, wildcard, style);
    if (rawPtr === null) return null;
    return new wxFilePickerCtrl(rawPtr);
  }

  GetPath(): Deno.PointerValue {
    return lib.symbols.wxFilePickerCtrl_GetPath(this.#ptr);
  }

  SetPath(path: Deno.PointerValue): void {
    lib.symbols.wxFilePickerCtrl_SetPath(this.#ptr, path);
  }

  SetInitialDirectory(dir: Deno.PointerValue): void {
    lib.symbols.wxFilePickerCtrl_SetInitialDirectory(this.#ptr, dir);
  }

  SetFileName(filename: Deno.PointerValue): void {
    lib.symbols.wxFilePickerCtrl_SetFileName(this.#ptr, filename);
  }

  GetFileName(): Deno.PointerValue {
    return lib.symbols.wxFilePickerCtrl_GetFileName(this.#ptr);
  }

}
