// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxDialog } from "./wxDialog_gen.ts";

export class wxFileDialog extends wxDialog {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, message: Deno.PointerValue, directory: Deno.PointerValue, files: Deno.PointerValue, weekday: Deno.PointerValue, left: number, top: number, style: number, sz_w: number, sz_h: number): wxFileDialog | null {
    const rawPtr = lib.symbols.wxFileDialog_Create(parent, message, directory, files, weekday, left, top, style, sz_w, sz_h);
    if (rawPtr === null) return null;
    return new wxFileDialog(rawPtr);
  }

  GetDirectory(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetDirectory(this._ptr);
  }

  GetFilename(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetFilename(this._ptr);
  }

  GetFilenames(paths: Deno.PointerValue): number {
    return lib.symbols.wxFileDialog_GetFilenames(this._ptr, paths);
  }

  GetFilterIndex(): number {
    return lib.symbols.wxFileDialog_GetFilterIndex(this._ptr);
  }

  GetMessage(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetMessage(this._ptr);
  }

  GetPath(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetPath(this._ptr);
  }

  GetPaths(paths: Deno.PointerValue): number {
    return lib.symbols.wxFileDialog_GetPaths(this._ptr, paths);
  }

  GetStyle(): number {
    return lib.symbols.wxFileDialog_GetStyle(this._ptr);
  }

  GetWildcard(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetWildcard(this._ptr);
  }

  SetDirectory(dir: Deno.PointerValue): void {
    lib.symbols.wxFileDialog_SetDirectory(this._ptr, dir);
  }

  SetFilename(name: Deno.PointerValue): void {
    lib.symbols.wxFileDialog_SetFilename(this._ptr, name);
  }

  SetFilterIndex(filterIndex: number): void {
    lib.symbols.wxFileDialog_SetFilterIndex(this._ptr, filterIndex);
  }

  SetMessage(message: Deno.PointerValue): void {
    lib.symbols.wxFileDialog_SetMessage(this._ptr, message);
  }

  SetPath(path: Deno.PointerValue): void {
    lib.symbols.wxFileDialog_SetPath(this._ptr, path);
  }

  SetStyle(style: number): void {
    lib.symbols.wxFileDialog_SetStyle(this._ptr, style);
  }

  SetWildcard(wildCard: Deno.PointerValue): void {
    lib.symbols.wxFileDialog_SetWildcard(this._ptr, wildCard);
  }

  GetCurrentlySelectedFilename(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetCurrentlySelectedFilename(this._ptr);
  }

  GetExtraControl(): Deno.PointerValue {
    return lib.symbols.wxFileDialog_GetExtraControl(this._ptr);
  }

}
