// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxFindReplaceDialog {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, data: Deno.PointerValue, title: Deno.PointerValue, style: number): wxFindReplaceDialog | null {
    const rawPtr = lib.symbols.wxFindReplaceDialog_Create(parent, data, title, style);
    if (rawPtr === null) return null;
    return new wxFindReplaceDialog(rawPtr);
  }

  GetData(): Deno.PointerValue {
    return lib.symbols.wxFindReplaceDialog_GetData(this.#ptr);
  }

  SetData(data: Deno.PointerValue): void {
    lib.symbols.wxFindReplaceDialog_SetData(this.#ptr, data);
  }

}
