// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxFindReplaceData {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(flags: number): wxFindReplaceData | null {
    const rawPtr = lib.symbols.wxFindReplaceData_Create(flags);
    if (rawPtr === null) return null;
    return new wxFindReplaceData(rawPtr);
  }

  static CreateDefault(): wxFindReplaceData | null {
    const rawPtr = lib.symbols.wxFindReplaceData_CreateDefault();
    if (rawPtr === null) return null;
    return new wxFindReplaceData(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxFindReplaceData_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetFindString(): Deno.PointerValue {
    return lib.symbols.wxFindReplaceData_GetFindString(this.#ptr);
  }

  GetFlags(): number {
    return lib.symbols.wxFindReplaceData_GetFlags(this.#ptr);
  }

  GetReplaceString(): Deno.PointerValue {
    return lib.symbols.wxFindReplaceData_GetReplaceString(this.#ptr);
  }

  SetFindString(str: Deno.PointerValue): void {
    lib.symbols.wxFindReplaceData_SetFindString(this.#ptr, str);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxFindReplaceData_SetFlags(this.#ptr, flags);
  }

  SetReplaceString(str: Deno.PointerValue): void {
    lib.symbols.wxFindReplaceData_SetReplaceString(this.#ptr, str);
  }

}
