// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxFileHistory {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(maxFiles: number): wxFileHistory | null {
    const rawPtr = lib.symbols.wxFileHistory_Create(maxFiles);
    if (rawPtr === null) return null;
    return new wxFileHistory(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxFileHistory_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddFileToHistory(file: Deno.PointerValue): void {
    lib.symbols.wxFileHistory_AddFileToHistory(this._ptr, file);
  }

  AddFilesToMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxFileHistory_AddFilesToMenu(this._ptr, menu);
  }

  GetCount(): number {
    return lib.symbols.wxFileHistory_GetCount(this._ptr);
  }

  GetHistoryFile(index: number): Deno.PointerValue {
    return lib.symbols.wxFileHistory_GetHistoryFile(this._ptr, index);
  }

  GetMaxFiles(): number {
    return lib.symbols.wxFileHistory_GetMaxFiles(this._ptr);
  }

  GetMenus(ref: Deno.PointerValue): number {
    return lib.symbols.wxFileHistory_GetMenus(this._ptr, ref);
  }

  Load(config: Deno.PointerValue): void {
    lib.symbols.wxFileHistory_Load(this._ptr, config);
  }

  RemoveFileFromHistory(index: number): void {
    lib.symbols.wxFileHistory_RemoveFileFromHistory(this._ptr, index);
  }

  RemoveMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxFileHistory_RemoveMenu(this._ptr, menu);
  }

  Save(config: Deno.PointerValue): void {
    lib.symbols.wxFileHistory_Save(this._ptr, config);
  }

  UseMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxFileHistory_UseMenu(this._ptr, menu);
  }

}
