// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxFileCtrl extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, defaultDirectory: Deno.PointerValue, defaultFilename: Deno.PointerValue, wildCard: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxFileCtrl | null {
    const rawPtr = lib.symbols.wxFileCtrl_Create(parent, id, defaultDirectory, defaultFilename, wildCard, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxFileCtrl(rawPtr);
  }

  GetDirectory(): Deno.PointerValue {
    return lib.symbols.wxFileCtrl_GetDirectory(this._ptr);
  }

  GetFilename(): Deno.PointerValue {
    return lib.symbols.wxFileCtrl_GetFilename(this._ptr);
  }

  GetFilenames(filenames: Deno.PointerValue): void {
    lib.symbols.wxFileCtrl_GetFilenames(this._ptr, filenames);
  }

  GetFilterIndex(): number {
    return lib.symbols.wxFileCtrl_GetFilterIndex(this._ptr);
  }

  GetPath(): Deno.PointerValue {
    return lib.symbols.wxFileCtrl_GetPath(this._ptr);
  }

  GetPaths(paths: Deno.PointerValue): void {
    lib.symbols.wxFileCtrl_GetPaths(this._ptr, paths);
  }

  GetWildcard(): Deno.PointerValue {
    return lib.symbols.wxFileCtrl_GetWildcard(this._ptr);
  }

  SetDirectory(directory: Deno.PointerValue): boolean {
    return (lib.symbols.wxFileCtrl_SetDirectory(this._ptr, directory) as number) !== 0;
  }

  SetFilename(filename: Deno.PointerValue): boolean {
    return (lib.symbols.wxFileCtrl_SetFilename(this._ptr, filename) as number) !== 0;
  }

  SetPath(path: Deno.PointerValue): boolean {
    return (lib.symbols.wxFileCtrl_SetPath(this._ptr, path) as number) !== 0;
  }

  SetFilterIndex(filterIndex: number): void {
    lib.symbols.wxFileCtrl_SetFilterIndex(this._ptr, filterIndex);
  }

  SetWildcard(wildCard: Deno.PointerValue): void {
    lib.symbols.wxFileCtrl_SetWildcard(this._ptr, wildCard);
  }

  ShowHidden(show: boolean): void {
    lib.symbols.wxFileCtrl_ShowHidden(this._ptr, show ? 1 : 0);
  }

}
