// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxFindDialogEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetFindString(ref: Deno.PointerValue): number {
    return lib.symbols.wxFindDialogEvent_GetFindString(this.#ptr, ref);
  }

  GetFlags(): number {
    return lib.symbols.wxFindDialogEvent_GetFlags(this.#ptr);
  }

  GetReplaceString(ref: Deno.PointerValue): number {
    return lib.symbols.wxFindDialogEvent_GetReplaceString(this.#ptr, ref);
  }

}
