// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxPGProperty } from "./wxPGProperty_gen.ts";

export class wxFloatProperty extends wxPGProperty {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(label: Deno.PointerValue, name: Deno.PointerValue, value: number): wxFloatProperty | null {
    const rawPtr = lib.symbols.wxFloatProperty_Create(label, name, value);
    if (rawPtr === null) return null;
    return new wxFloatProperty(rawPtr);
  }

}
