// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxFrame {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxFrame | null {
    const rawPtr = lib.symbols.wxFrame_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxFrame(rawPtr);
  }

  CreateStatusBar(number: number, style: number): Deno.PointerValue {
    return lib.symbols.wxFrame_CreateStatusBar(this.#ptr, number, style);
  }

  CreateToolBar(style: number): Deno.PointerValue {
    return lib.symbols.wxFrame_CreateToolBar(this.#ptr, style);
  }

  GetClientAreaOrigin_left(): number {
    return lib.symbols.wxFrame_GetClientAreaOrigin_left(this.#ptr);
  }

  GetClientAreaOrigin_top(): number {
    return lib.symbols.wxFrame_GetClientAreaOrigin_top(this.#ptr);
  }

  GetMenuBar(): Deno.PointerValue {
    return lib.symbols.wxFrame_GetMenuBar(this.#ptr);
  }

  GetStatusBar(): Deno.PointerValue {
    return lib.symbols.wxFrame_GetStatusBar(this.#ptr);
  }

  GetToolBar(): Deno.PointerValue {
    return lib.symbols.wxFrame_GetToolBar(this.#ptr);
  }

  Restore(): void {
    lib.symbols.wxFrame_Restore(this.#ptr);
  }

  SetMenuBar(menubar: Deno.PointerValue): void {
    lib.symbols.wxFrame_SetMenuBar(this.#ptr, menubar);
  }

  SetStatusBar(statBar: Deno.PointerValue): void {
    lib.symbols.wxFrame_SetStatusBar(this.#ptr, statBar);
  }

  SetStatusText(text: Deno.PointerValue, number: number): void {
    lib.symbols.wxFrame_SetStatusText(this.#ptr, text, number);
  }

  SetStatusWidths(count: number, widths: Deno.PointerValue): void {
    lib.symbols.wxFrame_SetStatusWidths(this.#ptr, count, widths);
  }

  SetToolBar(toolbar: Deno.PointerValue): void {
    lib.symbols.wxFrame_SetToolBar(this.#ptr, toolbar);
  }

  FindItemInMenuBar(menuId: number): Deno.PointerValue {
    return lib.symbols.wxFrame_FindItemInMenuBar(this.#ptr, menuId);
  }

  ProcessCommand(id: number): void {
    lib.symbols.wxFrame_ProcessCommand(this.#ptr, id);
  }

  SetStatusBarPane(n: number): void {
    lib.symbols.wxFrame_SetStatusBarPane(this.#ptr, n);
  }

  GetStatusBarPane(): number {
    return lib.symbols.wxFrame_GetStatusBarPane(this.#ptr);
  }

  PushStatusText(text: Deno.PointerValue, field: number): void {
    lib.symbols.wxFrame_PushStatusText(this.#ptr, text, field);
  }

  PopStatusText(field: number): void {
    lib.symbols.wxFrame_PopStatusText(this.#ptr, field);
  }

}
