// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGauge {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, range: number, left: number, top: number, width: number, height: number, style: number): wxGauge | null {
    const rawPtr = lib.symbols.wxGauge_Create(parent, id, range, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxGauge(rawPtr);
  }

  GetRange(): number {
    return lib.symbols.wxGauge_GetRange(this.#ptr);
  }

  GetValue(): number {
    return lib.symbols.wxGauge_GetValue(this.#ptr);
  }

  SetRange(range: number): void {
    lib.symbols.wxGauge_SetRange(this.#ptr, range);
  }

  SetValue(pos: number): void {
    lib.symbols.wxGauge_SetValue(this.#ptr, pos);
  }

  Pulse(): void {
    lib.symbols.wxGauge_Pulse(this.#ptr);
  }

  IsVertical(): boolean {
    return (lib.symbols.wxGauge_IsVertical(this.#ptr) as number) !== 0;
  }

}
