// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGridCellEditor {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  BeginEdit(row: number, col: number, grid: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_BeginEdit(this._ptr, row, col, grid);
  }

  Create(parent: Deno.PointerValue, id: number, evtHandler: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_Create(this._ptr, parent, id, evtHandler);
  }

  Destroy(): void {
    lib.symbols.wxGridCellEditor_Destroy(this._ptr);
  }

  EndEdit(row: number, col: number, grid: Deno.PointerValue, oldStr: Deno.PointerValue, newStr: Deno.PointerValue): number {
    return lib.symbols.wxGridCellEditor_EndEdit(this._ptr, row, col, grid, oldStr, newStr);
  }

  GetControl(): Deno.PointerValue {
    return lib.symbols.wxGridCellEditor_GetControl(this._ptr);
  }

  HandleReturn(event: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_HandleReturn(this._ptr, event);
  }

  IsAcceptedKey(event: Deno.PointerValue): boolean {
    return (lib.symbols.wxGridCellEditor_IsAcceptedKey(this._ptr, event) as number) !== 0;
  }

  IsCreated(): boolean {
    return (lib.symbols.wxGridCellEditor_IsCreated(this._ptr) as number) !== 0;
  }

  PaintBackground(dc: Deno.PointerValue, x: number, y: number, width: number, height: number, attr: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_PaintBackground(this._ptr, dc, x, y, width, height, attr);
  }

  Reset(): void {
    lib.symbols.wxGridCellEditor_Reset(this._ptr);
  }

  SetControl(control: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_SetControl(this._ptr, control);
  }

  SetParameters(params: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_SetParameters(this._ptr, params);
  }

  SetSize(x: number, y: number, width: number, height: number): void {
    lib.symbols.wxGridCellEditor_SetSize(this._ptr, x, y, width, height);
  }

  Show(show: boolean, attr: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_Show(this._ptr, show ? 1 : 0, attr);
  }

  StartingClick(): void {
    lib.symbols.wxGridCellEditor_StartingClick(this._ptr);
  }

  StartingKey(event: Deno.PointerValue): void {
    lib.symbols.wxGridCellEditor_StartingKey(this._ptr, event);
  }

}
