// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxNotifyEvent } from "./wxNotifyEvent_gen.ts";

export class wxGridSizeEvent extends wxNotifyEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  GetRowOrCol(): number {
    return lib.symbols.wxGridSizeEvent_GetRowOrCol(this._ptr);
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxGridSizeEvent_GetPosition(this._ptr);
  }

  ControlDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_ControlDown(this._ptr) as number) !== 0;
  }

  MetaDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_MetaDown(this._ptr) as number) !== 0;
  }

  ShiftDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_ShiftDown(this._ptr) as number) !== 0;
  }

  AltDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_AltDown(this._ptr) as number) !== 0;
  }

}
