// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGridBagSizer {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(vgap: number, hgap: number): wxGridBagSizer | null {
    const rawPtr = lib.symbols.wxGridBagSizer_Create(vgap, hgap);
    if (rawPtr === null) return null;
    return new wxGridBagSizer(rawPtr);
  }

  AddWindow(window: Deno.PointerValue, row: number, col: number, rowspan: number, colspan: number, flag: number, border: number, userData: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxGridBagSizer_AddWindow(this.#ptr, window, row, col, rowspan, colspan, flag, border, userData);
  }

  AddSizer(sizer: Deno.PointerValue, row: number, col: number, rowspan: number, colspan: number, flag: number, border: number, userData: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxGridBagSizer_AddSizer(this.#ptr, sizer, row, col, rowspan, colspan, flag, border, userData);
  }

  AddSpacer(width: number, height: number, row: number, col: number, rowspan: number, colspan: number, flag: number, border: number, userData: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxGridBagSizer_AddSpacer(this.#ptr, width, height, row, col, rowspan, colspan, flag, border, userData);
  }

  GetItemPosition(window: Deno.PointerValue, row: Deno.PointerValue, col: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetItemPosition(this.#ptr, window, row, col);
  }

  GetItemPositionSizer(sizer: Deno.PointerValue, row: Deno.PointerValue, col: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetItemPositionSizer(this.#ptr, sizer, row, col);
  }

  GetItemPositionIndex(index: bigint, row: Deno.PointerValue, col: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetItemPositionIndex(this.#ptr, index, row, col);
  }

  SetItemPosition(window: Deno.PointerValue, row: number, col: number): boolean {
    return (lib.symbols.wxGridBagSizer_SetItemPosition(this.#ptr, window, row, col) as number) !== 0;
  }

  SetItemPositionSizer(sizer: Deno.PointerValue, row: number, col: number): boolean {
    return (lib.symbols.wxGridBagSizer_SetItemPositionSizer(this.#ptr, sizer, row, col) as number) !== 0;
  }

  SetItemPositionIndex(index: bigint, row: number, col: number): boolean {
    return (lib.symbols.wxGridBagSizer_SetItemPositionIndex(this.#ptr, index, row, col) as number) !== 0;
  }

  GetItemSpan(window: Deno.PointerValue, rowspan: Deno.PointerValue, colspan: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetItemSpan(this.#ptr, window, rowspan, colspan);
  }

  GetItemSpanSizer(sizer: Deno.PointerValue, rowspan: Deno.PointerValue, colspan: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetItemSpanSizer(this.#ptr, sizer, rowspan, colspan);
  }

  GetItemSpanIndex(index: bigint, rowspan: Deno.PointerValue, colspan: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetItemSpanIndex(this.#ptr, index, rowspan, colspan);
  }

  SetItemSpan(window: Deno.PointerValue, rowspan: number, colspan: number): boolean {
    return (lib.symbols.wxGridBagSizer_SetItemSpan(this.#ptr, window, rowspan, colspan) as number) !== 0;
  }

  SetItemSpanSizer(sizer: Deno.PointerValue, rowspan: number, colspan: number): boolean {
    return (lib.symbols.wxGridBagSizer_SetItemSpanSizer(this.#ptr, sizer, rowspan, colspan) as number) !== 0;
  }

  SetItemSpanIndex(index: bigint, rowspan: number, colspan: number): boolean {
    return (lib.symbols.wxGridBagSizer_SetItemSpanIndex(this.#ptr, index, rowspan, colspan) as number) !== 0;
  }

  FindItemAtPosition(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGridBagSizer_FindItemAtPosition(this.#ptr, row, col);
  }

  CheckForIntersection(item: Deno.PointerValue, excludeItem: Deno.PointerValue): boolean {
    return (lib.symbols.wxGridBagSizer_CheckForIntersection(this.#ptr, item, excludeItem) as number) !== 0;
  }

  CheckForIntersectionPos(row: number, col: number, rowspan: number, colspan: number, excludeItem: Deno.PointerValue): boolean {
    return (lib.symbols.wxGridBagSizer_CheckForIntersectionPos(this.#ptr, row, col, rowspan, colspan, excludeItem) as number) !== 0;
  }

  GetEmptyCellSize(width: Deno.PointerValue, height: Deno.PointerValue): void {
    lib.symbols.wxGridBagSizer_GetEmptyCellSize(this.#ptr, width, height);
  }

  SetEmptyCellSize(width: number, height: number): void {
    lib.symbols.wxGridBagSizer_SetEmptyCellSize(this.#ptr, width, height);
  }

}
