// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGridCellCoordsArray {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxGridCellCoordsArray | null {
    const rawPtr = lib.symbols.wxGridCellCoordsArray_Create();
    if (rawPtr === null) return null;
    return new wxGridCellCoordsArray(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxGridCellCoordsArray_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetCount(): number {
    return lib.symbols.wxGridCellCoordsArray_GetCount(this.#ptr);
  }

  Item(index: number, col: Deno.PointerValue, row: Deno.PointerValue): void {
    lib.symbols.wxGridCellCoordsArray_Item(this.#ptr, index, col, row);
  }

}
