// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxGridCellTextEditor } from "./wxGridCellTextEditor_gen.ts";

export class wxGridCellNumberEditor extends wxGridCellTextEditor {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  Ctor(min: number, max: number): Deno.PointerValue {
    return lib.symbols.wxGridCellNumberEditor_Ctor(min, max);
  }

}
