// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGridRangeSelectEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetTopLeftCoords(col: Deno.PointerValue, row: Deno.PointerValue): void {
    lib.symbols.wxGridRangeSelectEvent_GetTopLeftCoords(this.#ptr, col, row);
  }

  GetBottomRightCoords(col: Deno.PointerValue, row: Deno.PointerValue): void {
    lib.symbols.wxGridRangeSelectEvent_GetBottomRightCoords(this.#ptr, col, row);
  }

  GetTopRow(): number {
    return lib.symbols.wxGridRangeSelectEvent_GetTopRow(this.#ptr);
  }

  GetBottomRow(): number {
    return lib.symbols.wxGridRangeSelectEvent_GetBottomRow(this.#ptr);
  }

  GetLeftCol(): number {
    return lib.symbols.wxGridRangeSelectEvent_GetLeftCol(this.#ptr);
  }

  GetRightCol(): number {
    return lib.symbols.wxGridRangeSelectEvent_GetRightCol(this.#ptr);
  }

  Selecting(): boolean {
    return (lib.symbols.wxGridRangeSelectEvent_Selecting(this.#ptr) as number) !== 0;
  }

  ControlDown(): boolean {
    return (lib.symbols.wxGridRangeSelectEvent_ControlDown(this.#ptr) as number) !== 0;
  }

  MetaDown(): boolean {
    return (lib.symbols.wxGridRangeSelectEvent_MetaDown(this.#ptr) as number) !== 0;
  }

  ShiftDown(): boolean {
    return (lib.symbols.wxGridRangeSelectEvent_ShiftDown(this.#ptr) as number) !== 0;
  }

  AltDown(): boolean {
    return (lib.symbols.wxGridRangeSelectEvent_AltDown(this.#ptr) as number) !== 0;
  }

}
