// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGrid {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxGrid | null {
    const rawPtr = lib.symbols.wxGrid_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxGrid(rawPtr);
  }

  AppendCols(numCols: number, updateLabels: boolean): boolean {
    return (lib.symbols.wxGrid_AppendCols(this.#ptr, numCols, updateLabels ? 1 : 0) as number) !== 0;
  }

  AppendRows(numRows: number, updateLabels: boolean): boolean {
    return (lib.symbols.wxGrid_AppendRows(this.#ptr, numRows, updateLabels ? 1 : 0) as number) !== 0;
  }

  AutoSize(): void {
    lib.symbols.wxGrid_AutoSize(this.#ptr);
  }

  AutoSizeColumn(col: number, setAsMin: boolean): void {
    lib.symbols.wxGrid_AutoSizeColumn(this.#ptr, col, setAsMin ? 1 : 0);
  }

  AutoSizeColumns(setAsMin: boolean): void {
    lib.symbols.wxGrid_AutoSizeColumns(this.#ptr, setAsMin ? 1 : 0);
  }

  AutoSizeRow(row: number, setAsMin: boolean): void {
    lib.symbols.wxGrid_AutoSizeRow(this.#ptr, row, setAsMin ? 1 : 0);
  }

  AutoSizeRows(setAsMin: boolean): void {
    lib.symbols.wxGrid_AutoSizeRows(this.#ptr, setAsMin ? 1 : 0);
  }

  BeginBatch(): void {
    lib.symbols.wxGrid_BeginBatch(this.#ptr);
  }

  BlockToDeviceRect(top: number, left: number, bottom: number, right: number): Deno.PointerValue {
    return lib.symbols.wxGrid_BlockToDeviceRect(this.#ptr, top, left, bottom, right);
  }

  CanDragColSize(col: number): boolean {
    return (lib.symbols.wxGrid_CanDragColSize(this.#ptr, col) as number) !== 0;
  }

  CanDragGridSize(): boolean {
    return (lib.symbols.wxGrid_CanDragGridSize(this.#ptr) as number) !== 0;
  }

  CanDragRowSize(row: number): boolean {
    return (lib.symbols.wxGrid_CanDragRowSize(this.#ptr, row) as number) !== 0;
  }

  CanEnableCellControl(): boolean {
    return (lib.symbols.wxGrid_CanEnableCellControl(this.#ptr) as number) !== 0;
  }

  CellToRect(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_CellToRect(this.#ptr, row, col);
  }

  ClearGrid(): void {
    lib.symbols.wxGrid_ClearGrid(this.#ptr);
  }

  ClearSelection(): void {
    lib.symbols.wxGrid_ClearSelection(this.#ptr);
  }

  CreateGrid(rows: number, cols: number, selmode: number): void {
    lib.symbols.wxGrid_CreateGrid(this.#ptr, rows, cols, selmode);
  }

  DeleteCols(pos: number, numCols: number, updateLabels: boolean): boolean {
    return (lib.symbols.wxGrid_DeleteCols(this.#ptr, pos, numCols, updateLabels ? 1 : 0) as number) !== 0;
  }

  DeleteRows(pos: number, numRows: number, updateLabels: boolean): boolean {
    return (lib.symbols.wxGrid_DeleteRows(this.#ptr, pos, numRows, updateLabels ? 1 : 0) as number) !== 0;
  }

  DisableCellEditControl(): void {
    lib.symbols.wxGrid_DisableCellEditControl(this.#ptr);
  }

  DisableDragColSize(): void {
    lib.symbols.wxGrid_DisableDragColSize(this.#ptr);
  }

  DisableDragGridSize(): void {
    lib.symbols.wxGrid_DisableDragGridSize(this.#ptr);
  }

  DisableDragRowSize(): void {
    lib.symbols.wxGrid_DisableDragRowSize(this.#ptr);
  }

  DrawAllGridLines(dc: Deno.PointerValue, reg: Deno.PointerValue): void {
    lib.symbols.wxGrid_DrawAllGridLines(this.#ptr, dc, reg);
  }

  DrawCell(dc: Deno.PointerValue, row: number, col: number): void {
    lib.symbols.wxGrid_DrawCell(this.#ptr, dc, row, col);
  }

  DrawCellBorder(dc: Deno.PointerValue, row: number, col: number): void {
    lib.symbols.wxGrid_DrawCellBorder(this.#ptr, dc, row, col);
  }

  DrawCellHighlight(dc: Deno.PointerValue, attr: Deno.PointerValue): void {
    lib.symbols.wxGrid_DrawCellHighlight(this.#ptr, dc, attr);
  }

  DrawColLabel(dc: Deno.PointerValue, col: number): void {
    lib.symbols.wxGrid_DrawColLabel(this.#ptr, dc, col);
  }

  DrawColLabels(dc: Deno.PointerValue): void {
    lib.symbols.wxGrid_DrawColLabels(this.#ptr, dc);
  }

  DrawGridSpace(dc: Deno.PointerValue): void {
    lib.symbols.wxGrid_DrawGridSpace(this.#ptr, dc);
  }

  DrawRowLabel(dc: Deno.PointerValue, row: number): void {
    lib.symbols.wxGrid_DrawRowLabel(this.#ptr, dc, row);
  }

  DrawRowLabels(dc: Deno.PointerValue): void {
    lib.symbols.wxGrid_DrawRowLabels(this.#ptr, dc);
  }

  DrawTextRectangle(dc: Deno.PointerValue, txt: Deno.PointerValue, x: number, y: number, width: number, height: number, horizontalAlignment: number, verticalAlignment: number): void {
    lib.symbols.wxGrid_DrawTextRectangle(this.#ptr, dc, txt, x, y, width, height, horizontalAlignment, verticalAlignment);
  }

  EnableCellEditControl(enable: boolean): void {
    lib.symbols.wxGrid_EnableCellEditControl(this.#ptr, enable ? 1 : 0);
  }

  EnableDragColSize(enable: boolean): void {
    lib.symbols.wxGrid_EnableDragColSize(this.#ptr, enable ? 1 : 0);
  }

  EnableDragGridSize(enable: boolean): void {
    lib.symbols.wxGrid_EnableDragGridSize(this.#ptr, enable ? 1 : 0);
  }

  EnableDragRowSize(enable: boolean): void {
    lib.symbols.wxGrid_EnableDragRowSize(this.#ptr, enable ? 1 : 0);
  }

  EnableEditing(edit: boolean): void {
    lib.symbols.wxGrid_EnableEditing(this.#ptr, edit ? 1 : 0);
  }

  EnableGridLines(enable: boolean): void {
    lib.symbols.wxGrid_EnableGridLines(this.#ptr, enable ? 1 : 0);
  }

  EndBatch(): void {
    lib.symbols.wxGrid_EndBatch(this.#ptr);
  }

  GetBatchCount(): number {
    return lib.symbols.wxGrid_GetBatchCount(this.#ptr);
  }

  GetCellAlignment(row: number, col: number, horiz: Deno.PointerValue, vert: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetCellAlignment(this.#ptr, row, col, horiz, vert);
  }

  GetCellBackgroundColour(row: number, col: number, colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetCellBackgroundColour(this.#ptr, row, col, colour);
  }

  GetCellEditor(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetCellEditor(this.#ptr, row, col);
  }

  GetCellFont(row: number, col: number, font: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetCellFont(this.#ptr, row, col, font);
  }

  GetCellHighlightColour(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetCellHighlightColour(this.#ptr, ref);
  }

  GetCellRenderer(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetCellRenderer(this.#ptr, row, col);
  }

  GetCellTextColour(row: number, col: number, colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetCellTextColour(this.#ptr, row, col, colour);
  }

  GetCellValue(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetCellValue(this.#ptr, row, col);
  }

  GetColLabelAlignment(horiz: Deno.PointerValue, vert: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetColLabelAlignment(this.#ptr, horiz, vert);
  }

  GetColLabelSize(): number {
    return lib.symbols.wxGrid_GetColLabelSize(this.#ptr);
  }

  GetColLabelValue(col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetColLabelValue(this.#ptr, col);
  }

  GetColSize(col: number): number {
    return lib.symbols.wxGrid_GetColSize(this.#ptr, col);
  }

  GetDefaultCellAlignment(horiz: Deno.PointerValue, vert: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetDefaultCellAlignment(this.#ptr, horiz, vert);
  }

  GetDefaultCellBackgroundColour(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetDefaultCellBackgroundColour(this.#ptr, ref);
  }

  GetDefaultCellFont(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetDefaultCellFont(this.#ptr, ref);
  }

  GetDefaultCellTextColour(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetDefaultCellTextColour(this.#ptr, ref);
  }

  GetDefaultColLabelSize(): number {
    return lib.symbols.wxGrid_GetDefaultColLabelSize(this.#ptr);
  }

  GetDefaultColSize(): number {
    return lib.symbols.wxGrid_GetDefaultColSize(this.#ptr);
  }

  GetDefaultEditor(): Deno.PointerValue {
    return lib.symbols.wxGrid_GetDefaultEditor(this.#ptr);
  }

  GetDefaultEditorForCell(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetDefaultEditorForCell(this.#ptr, row, col);
  }

  GetDefaultEditorForType(typeName: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxGrid_GetDefaultEditorForType(this.#ptr, typeName);
  }

  GetDefaultRenderer(): Deno.PointerValue {
    return lib.symbols.wxGrid_GetDefaultRenderer(this.#ptr);
  }

  GetDefaultRendererForCell(row: number, col: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetDefaultRendererForCell(this.#ptr, row, col);
  }

  GetDefaultRendererForType(typeName: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxGrid_GetDefaultRendererForType(this.#ptr, typeName);
  }

  GetDefaultRowLabelSize(): number {
    return lib.symbols.wxGrid_GetDefaultRowLabelSize(this.#ptr);
  }

  GetDefaultRowSize(): number {
    return lib.symbols.wxGrid_GetDefaultRowSize(this.#ptr);
  }

  GetGridCursorCol(): number {
    return lib.symbols.wxGrid_GetGridCursorCol(this.#ptr);
  }

  GetGridCursorRow(): number {
    return lib.symbols.wxGrid_GetGridCursorRow(this.#ptr);
  }

  GetGridLineColour(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetGridLineColour(this.#ptr, ref);
  }

  GetLabelBackgroundColour(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetLabelBackgroundColour(this.#ptr, ref);
  }

  GetLabelFont(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetLabelFont(this.#ptr, ref);
  }

  GetLabelTextColour(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetLabelTextColour(this.#ptr, ref);
  }

  GetNumberCols(): number {
    return lib.symbols.wxGrid_GetNumberCols(this.#ptr);
  }

  GetNumberRows(): number {
    return lib.symbols.wxGrid_GetNumberRows(this.#ptr);
  }

  GetRowLabelAlignment(horiz: Deno.PointerValue, vert: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetRowLabelAlignment(this.#ptr, horiz, vert);
  }

  GetRowLabelSize(): number {
    return lib.symbols.wxGrid_GetRowLabelSize(this.#ptr);
  }

  GetRowLabelValue(row: number): Deno.PointerValue {
    return lib.symbols.wxGrid_GetRowLabelValue(this.#ptr, row);
  }

  GetRowSize(row: number): number {
    return lib.symbols.wxGrid_GetRowSize(this.#ptr, row);
  }

  GetSelectionBackground(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetSelectionBackground(this.#ptr, ref);
  }

  GetSelectionForeground(ref: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetSelectionForeground(this.#ptr, ref);
  }

  GetTable(): Deno.PointerValue {
    return lib.symbols.wxGrid_GetTable(this.#ptr);
  }

  GetTextBoxSize(dc: Deno.PointerValue, count: number, lines: Deno.PointerValue, width: Deno.PointerValue, height: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetTextBoxSize(this.#ptr, dc, count, lines, width, height);
  }

  GridLinesEnabled(): number {
    return lib.symbols.wxGrid_GridLinesEnabled(this.#ptr);
  }

  HideCellEditControl(): void {
    lib.symbols.wxGrid_HideCellEditControl(this.#ptr);
  }

  InsertCols(pos: number, numCols: number, updateLabels: boolean): boolean {
    return (lib.symbols.wxGrid_InsertCols(this.#ptr, pos, numCols, updateLabels ? 1 : 0) as number) !== 0;
  }

  InsertRows(pos: number, numRows: number, updateLabels: boolean): boolean {
    return (lib.symbols.wxGrid_InsertRows(this.#ptr, pos, numRows, updateLabels ? 1 : 0) as number) !== 0;
  }

  IsCellEditControlEnabled(): boolean {
    return (lib.symbols.wxGrid_IsCellEditControlEnabled(this.#ptr) as number) !== 0;
  }

  IsCellEditControlShown(): boolean {
    return (lib.symbols.wxGrid_IsCellEditControlShown(this.#ptr) as number) !== 0;
  }

  IsCurrentCellReadOnly(): boolean {
    return (lib.symbols.wxGrid_IsCurrentCellReadOnly(this.#ptr) as number) !== 0;
  }

  IsEditable(): boolean {
    return (lib.symbols.wxGrid_IsEditable(this.#ptr) as number) !== 0;
  }

  IsInSelection(row: number, col: number): boolean {
    return (lib.symbols.wxGrid_IsInSelection(this.#ptr, row, col) as number) !== 0;
  }

  IsReadOnly(row: number, col: number): boolean {
    return (lib.symbols.wxGrid_IsReadOnly(this.#ptr, row, col) as number) !== 0;
  }

  IsSelection(): boolean {
    return (lib.symbols.wxGrid_IsSelection(this.#ptr) as number) !== 0;
  }

  IsVisible(row: number, col: number, wholeCellVisible: boolean): boolean {
    return (lib.symbols.wxGrid_IsVisible(this.#ptr, row, col, wholeCellVisible ? 1 : 0) as number) !== 0;
  }

  MakeCellVisible(row: number, col: number): void {
    lib.symbols.wxGrid_MakeCellVisible(this.#ptr, row, col);
  }

  MoveCursorDown(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorDown(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorDownBlock(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorDownBlock(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorLeft(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorLeft(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorLeftBlock(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorLeftBlock(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorRight(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorRight(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorRightBlock(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorRightBlock(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorUp(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorUp(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MoveCursorUpBlock(expandSelection: boolean): boolean {
    return (lib.symbols.wxGrid_MoveCursorUpBlock(this.#ptr, expandSelection ? 1 : 0) as number) !== 0;
  }

  MovePageDown(): boolean {
    return (lib.symbols.wxGrid_MovePageDown(this.#ptr) as number) !== 0;
  }

  MovePageUp(): boolean {
    return (lib.symbols.wxGrid_MovePageUp(this.#ptr) as number) !== 0;
  }

  ProcessTableMessage(evt: Deno.PointerValue): boolean {
    return (lib.symbols.wxGrid_ProcessTableMessage(this.#ptr, evt) as number) !== 0;
  }

  RegisterDataType(typeName: Deno.PointerValue, renderer: Deno.PointerValue, editor: Deno.PointerValue): void {
    lib.symbols.wxGrid_RegisterDataType(this.#ptr, typeName, renderer, editor);
  }

  SaveEditControlValue(): void {
    lib.symbols.wxGrid_SaveEditControlValue(this.#ptr);
  }

  SelectAll(): void {
    lib.symbols.wxGrid_SelectAll(this.#ptr);
  }

  SelectBlock(topRow: number, leftCol: number, bottomRow: number, rightCol: number, addToSelected: boolean): void {
    lib.symbols.wxGrid_SelectBlock(this.#ptr, topRow, leftCol, bottomRow, rightCol, addToSelected ? 1 : 0);
  }

  SelectCol(col: number, addToSelected: boolean): void {
    lib.symbols.wxGrid_SelectCol(this.#ptr, col, addToSelected ? 1 : 0);
  }

  SelectRow(row: number, addToSelected: boolean): void {
    lib.symbols.wxGrid_SelectRow(this.#ptr, row, addToSelected ? 1 : 0);
  }

  SetCellAlignment(row: number, col: number, horiz: number, vert: number): void {
    lib.symbols.wxGrid_SetCellAlignment(this.#ptr, row, col, horiz, vert);
  }

  SetCellBackgroundColour(row: number, col: number, colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellBackgroundColour(this.#ptr, row, col, colour);
  }

  SetCellEditor(row: number, col: number, editor: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellEditor(this.#ptr, row, col, editor);
  }

  SetCellFont(row: number, col: number, font: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellFont(this.#ptr, row, col, font);
  }

  SetCellHighlightColour(col: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellHighlightColour(this.#ptr, col);
  }

  SetCellRenderer(row: number, col: number, renderer: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellRenderer(this.#ptr, row, col, renderer);
  }

  SetCellTextColour(row: number, col: number, colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellTextColour(this.#ptr, row, col, colour);
  }

  SetCellValue(row: number, col: number, str: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetCellValue(this.#ptr, row, col, str);
  }

  SetColAttr(col: number, attr: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetColAttr(this.#ptr, col, attr);
  }

  SetColFormatBool(col: number): void {
    lib.symbols.wxGrid_SetColFormatBool(this.#ptr, col);
  }

  SetColFormatCustom(col: number, typeName: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetColFormatCustom(this.#ptr, col, typeName);
  }

  SetColFormatFloat(col: number, width: number, precision: number): void {
    lib.symbols.wxGrid_SetColFormatFloat(this.#ptr, col, width, precision);
  }

  SetColFormatNumber(col: number): void {
    lib.symbols.wxGrid_SetColFormatNumber(this.#ptr, col);
  }

  SetColLabelAlignment(horiz: number, vert: number): void {
    lib.symbols.wxGrid_SetColLabelAlignment(this.#ptr, horiz, vert);
  }

  SetColLabelSize(height: number): void {
    lib.symbols.wxGrid_SetColLabelSize(this.#ptr, height);
  }

  SetColLabelValue(col: number, label: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetColLabelValue(this.#ptr, col, label);
  }

  SetColMinimalWidth(col: number, width: number): void {
    lib.symbols.wxGrid_SetColMinimalWidth(this.#ptr, col, width);
  }

  SetColSize(col: number, width: number): void {
    lib.symbols.wxGrid_SetColSize(this.#ptr, col, width);
  }

  SetDefaultCellAlignment(horiz: number, vert: number): void {
    lib.symbols.wxGrid_SetDefaultCellAlignment(this.#ptr, horiz, vert);
  }

  SetDefaultCellBackgroundColour(colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetDefaultCellBackgroundColour(this.#ptr, colour);
  }

  SetDefaultCellFont(font: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetDefaultCellFont(this.#ptr, font);
  }

  SetDefaultCellTextColour(colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetDefaultCellTextColour(this.#ptr, colour);
  }

  SetDefaultColSize(width: number, resizeExistingCols: boolean): void {
    lib.symbols.wxGrid_SetDefaultColSize(this.#ptr, width, resizeExistingCols ? 1 : 0);
  }

  SetDefaultEditor(editor: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetDefaultEditor(this.#ptr, editor);
  }

  SetDefaultRenderer(renderer: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetDefaultRenderer(this.#ptr, renderer);
  }

  SetDefaultRowSize(height: number, resizeExistingRows: boolean): void {
    lib.symbols.wxGrid_SetDefaultRowSize(this.#ptr, height, resizeExistingRows ? 1 : 0);
  }

  SetGridCursor(row: number, col: number): void {
    lib.symbols.wxGrid_SetGridCursor(this.#ptr, row, col);
  }

  SetGridLineColour(col: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetGridLineColour(this.#ptr, col);
  }

  SetLabelBackgroundColour(colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetLabelBackgroundColour(this.#ptr, colour);
  }

  SetLabelFont(font: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetLabelFont(this.#ptr, font);
  }

  SetLabelTextColour(colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetLabelTextColour(this.#ptr, colour);
  }

  SetMargins(extraWidth: number, extraHeight: number): void {
    lib.symbols.wxGrid_SetMargins(this.#ptr, extraWidth, extraHeight);
  }

  SetReadOnly(row: number, col: number, isReadOnly: boolean): void {
    lib.symbols.wxGrid_SetReadOnly(this.#ptr, row, col, isReadOnly ? 1 : 0);
  }

  SetRowAttr(row: number, attr: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetRowAttr(this.#ptr, row, attr);
  }

  SetRowLabelAlignment(horiz: number, vert: number): void {
    lib.symbols.wxGrid_SetRowLabelAlignment(this.#ptr, horiz, vert);
  }

  SetRowLabelSize(width: number): void {
    lib.symbols.wxGrid_SetRowLabelSize(this.#ptr, width);
  }

  SetRowLabelValue(row: number, label: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetRowLabelValue(this.#ptr, row, label);
  }

  SetRowMinimalHeight(row: number, width: number): void {
    lib.symbols.wxGrid_SetRowMinimalHeight(this.#ptr, row, width);
  }

  SetRowSize(row: number, height: number): void {
    lib.symbols.wxGrid_SetRowSize(this.#ptr, row, height);
  }

  SetSelectionBackground(colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetSelectionBackground(this.#ptr, colour);
  }

  SetSelectionForeground(colour: Deno.PointerValue): void {
    lib.symbols.wxGrid_SetSelectionForeground(this.#ptr, colour);
  }

  SetSelectionMode(selmode: number): void {
    lib.symbols.wxGrid_SetSelectionMode(this.#ptr, selmode);
  }

  SetTable(table: Deno.PointerValue, takeOwnership: boolean, selmode: number): boolean {
    return (lib.symbols.wxGrid_SetTable(this.#ptr, table, takeOwnership ? 1 : 0, selmode) as number) !== 0;
  }

  ShowCellEditControl(): void {
    lib.symbols.wxGrid_ShowCellEditControl(this.#ptr);
  }

  StringToLines(value: Deno.PointerValue, lines: Deno.PointerValue): number {
    return lib.symbols.wxGrid_StringToLines(this.#ptr, value, lines);
  }

  XToCol(x: number, clipToMinMax: boolean): number {
    return lib.symbols.wxGrid_XToCol(this.#ptr, x, clipToMinMax ? 1 : 0);
  }

  XToEdgeOfCol(x: number): number {
    return lib.symbols.wxGrid_XToEdgeOfCol(this.#ptr, x);
  }

  XYToCell(x: number, y: number, row: Deno.PointerValue, col: Deno.PointerValue): void {
    lib.symbols.wxGrid_XYToCell(this.#ptr, x, y, row, col);
  }

  YToEdgeOfRow(y: number): number {
    return lib.symbols.wxGrid_YToEdgeOfRow(this.#ptr, y);
  }

  YToRow(y: number, clipToMinMax: boolean): number {
    return lib.symbols.wxGrid_YToRow(this.#ptr, y, clipToMinMax ? 1 : 0);
  }

  GetSelectedCells(array: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetSelectedCells(this.#ptr, array);
  }

  GetSelectionBlockTopLeft(array: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetSelectionBlockTopLeft(this.#ptr, array);
  }

  GetSelectionBlockBottomRight(array: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetSelectionBlockBottomRight(this.#ptr, array);
  }

  GetSelectedRows(array: Deno.PointerValue): number {
    return lib.symbols.wxGrid_GetSelectedRows(this.#ptr, array);
  }

  GetSelectedCols(array: Deno.PointerValue): number {
    return lib.symbols.wxGrid_GetSelectedCols(this.#ptr, array);
  }

  GetCellSize(row: number, col: number, srow: Deno.PointerValue, scol: Deno.PointerValue): void {
    lib.symbols.wxGrid_GetCellSize(this.#ptr, row, col, srow, scol);
  }

  SetCellSize(row: number, col: number, srow: number, scol: number): void {
    lib.symbols.wxGrid_SetCellSize(this.#ptr, row, col, srow, scol);
  }

}
