// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxGridSizeEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetRowOrCol(): number {
    return lib.symbols.wxGridSizeEvent_GetRowOrCol(this.#ptr);
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxGridSizeEvent_GetPosition(this.#ptr);
  }

  ControlDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_ControlDown(this.#ptr) as number) !== 0;
  }

  MetaDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_MetaDown(this.#ptr) as number) !== 0;
  }

  ShiftDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_ShiftDown(this.#ptr) as number) !== 0;
  }

  AltDown(): boolean {
    return (lib.symbols.wxGridSizeEvent_AltDown(this.#ptr) as number) !== 0;
  }

}
