// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxHelpProvider {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  Delete(): void {
    lib.symbols.wxHelpProvider_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddHelp(window: Deno.PointerValue, text: Deno.PointerValue): void {
    lib.symbols.wxHelpProvider_AddHelp(this.#ptr, window, text);
  }

  AddHelpById(id: number, text: Deno.PointerValue): void {
    lib.symbols.wxHelpProvider_AddHelpById(this.#ptr, id, text);
  }

  Get(): Deno.PointerValue {
    return lib.symbols.wxHelpProvider_Get();
  }

  GetHelp(window: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxHelpProvider_GetHelp(this.#ptr, window);
  }

  RemoveHelp(window: Deno.PointerValue): void {
    lib.symbols.wxHelpProvider_RemoveHelp(this.#ptr, window);
  }

  Set(): Deno.PointerValue {
    return lib.symbols.wxHelpProvider_Set(this.#ptr);
  }

  ShowHelp(window: Deno.PointerValue): boolean {
    return (lib.symbols.wxHelpProvider_ShowHelp(this.#ptr, window) as number) !== 0;
  }

}
