// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxHelpProvider {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  Delete(): void {
    lib.symbols.wxHelpProvider_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddHelp(window: Deno.PointerValue, text: Deno.PointerValue): void {
    lib.symbols.wxHelpProvider_AddHelp(this._ptr, window, text);
  }

  AddHelpById(id: number, text: Deno.PointerValue): void {
    lib.symbols.wxHelpProvider_AddHelpById(this._ptr, id, text);
  }

  Get(): Deno.PointerValue {
    return lib.symbols.wxHelpProvider_Get();
  }

  GetHelp(window: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxHelpProvider_GetHelp(this._ptr, window);
  }

  RemoveHelp(window: Deno.PointerValue): void {
    lib.symbols.wxHelpProvider_RemoveHelp(this._ptr, window);
  }

  Set(): Deno.PointerValue {
    return lib.symbols.wxHelpProvider_Set(this._ptr);
  }

  ShowHelp(window: Deno.PointerValue): boolean {
    return (lib.symbols.wxHelpProvider_ShowHelp(this._ptr, window) as number) !== 0;
  }

}
