// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxIconBundle {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static CreateDefault(): wxIconBundle | null {
    const rawPtr = lib.symbols.wxIconBundle_CreateDefault();
    if (rawPtr === null) return null;
    return new wxIconBundle(rawPtr);
  }

  static CreateFromFile(file: Deno.PointerValue, type_: number): wxIconBundle | null {
    const rawPtr = lib.symbols.wxIconBundle_CreateFromFile(file, type_);
    if (rawPtr === null) return null;
    return new wxIconBundle(rawPtr);
  }

  static CreateFromIcon(icon: Deno.PointerValue): wxIconBundle | null {
    const rawPtr = lib.symbols.wxIconBundle_CreateFromIcon(icon);
    if (rawPtr === null) return null;
    return new wxIconBundle(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxIconBundle_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddIcon(icon: Deno.PointerValue): void {
    lib.symbols.wxIconBundle_AddIcon(this._ptr, icon);
  }

  AddIconFromFile(file: Deno.PointerValue, type_: number): void {
    lib.symbols.wxIconBundle_AddIconFromFile(this._ptr, file, type_);
  }

  Assign(ref: Deno.PointerValue): void {
    lib.symbols.wxIconBundle_Assign(this._ptr, ref);
  }

  GetIcon(width: number, height: number, flags: number, ref: Deno.PointerValue): void {
    lib.symbols.wxIconBundle_GetIcon(this._ptr, width, height, flags, ref);
  }

}
