// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxBitmap } from "./wxBitmap_gen.ts";

export class wxIcon extends wxBitmap {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static CreateDefault(): wxIcon | null {
    const rawPtr = lib.symbols.wxIcon_CreateDefault();
    if (rawPtr === null) return null;
    return new wxIcon(rawPtr);
  }

  static CreateLoad(name: Deno.PointerValue, type_: number, width: number, height: number): wxIcon | null {
    const rawPtr = lib.symbols.wxIcon_CreateLoad(name, type_, width, height);
    if (rawPtr === null) return null;
    return new wxIcon(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxIcon_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Assign(other: Deno.PointerValue): void {
    lib.symbols.wxIcon_Assign(this._ptr, other);
  }

  CopyFromBitmap(bmp: Deno.PointerValue): void {
    lib.symbols.wxIcon_CopyFromBitmap(this._ptr, bmp);
  }

  FromRaw(width: number, height: number): Deno.PointerValue {
    return lib.symbols.wxIcon_FromRaw(this._ptr, width, height);
  }

  FromXPM(): Deno.PointerValue {
    return lib.symbols.wxIcon_FromXPM(this._ptr);
  }

  GetDepth(): number {
    return lib.symbols.wxIcon_GetDepth(this._ptr);
  }

  GetHeight(): number {
    return lib.symbols.wxIcon_GetHeight(this._ptr);
  }

  GetWidth(): number {
    return lib.symbols.wxIcon_GetWidth(this._ptr);
  }

  IsEqual(): boolean {
    return (lib.symbols.wxIcon_IsEqual(this._ptr, this._ptr) as number) !== 0;
  }

  Load(name: Deno.PointerValue, type_: number, width: number, height: number): number {
    return lib.symbols.wxIcon_Load(this._ptr, name, type_, width, height);
  }

  IsOk(): boolean {
    return (lib.symbols.wxIcon_IsOk(this._ptr) as number) !== 0;
  }

}
