// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxIdleEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  MoreRequested(): boolean {
    return (lib.symbols.wxIdleEvent_MoreRequested(this.#ptr) as number) !== 0;
  }

  RequestMore(needMore: boolean): void {
    lib.symbols.wxIdleEvent_RequestMore(this.#ptr, needMore ? 1 : 0);
  }

}
