// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxInfoBar {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number): wxInfoBar | null {
    const rawPtr = lib.symbols.wxInfoBar_Create(parent, id);
    if (rawPtr === null) return null;
    return new wxInfoBar(rawPtr);
  }

  AddButton(btnid: number, label: Deno.PointerValue): void {
    lib.symbols.wxInfoBar_AddButton(this.#ptr, btnid, label);
  }

  Dismiss(): void {
    lib.symbols.wxInfoBar_Dismiss(this.#ptr);
  }

  GetButtonCount(): bigint {
    return lib.symbols.wxInfoBar_GetButtonCount(this.#ptr) as bigint;
  }

  GetButtonId(idx: number): number {
    return lib.symbols.wxInfoBar_GetButtonId(this.#ptr, idx);
  }

  GetEffectDuration(): number {
    return lib.symbols.wxInfoBar_GetEffectDuration(this.#ptr);
  }

  GetShowEffect(): number {
    return lib.symbols.wxInfoBar_GetShowEffect(this.#ptr);
  }

  GetHideEffect(): number {
    return lib.symbols.wxInfoBar_GetHideEffect(this.#ptr);
  }

  HasFlag(flag: number): boolean {
    return (lib.symbols.wxInfoBar_HasFlag(this.#ptr, flag) as number) !== 0;
  }

  RemoveButton(btnid: number): void {
    lib.symbols.wxInfoBar_RemoveButton(this.#ptr, btnid);
  }

  SetEffectDuration(duration: number): void {
    lib.symbols.wxInfoBar_SetEffectDuration(this.#ptr, duration);
  }

  SetShowHideEffects(showEffect: number, hideEffect: number): void {
    lib.symbols.wxInfoBar_SetShowHideEffects(this.#ptr, showEffect, hideEffect);
  }

  ShowMessage(msg: Deno.PointerValue, flags: number): void {
    lib.symbols.wxInfoBar_ShowMessage(this.#ptr, msg, flags);
  }

}
