// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxStreamBase } from "./wxStreamBase_gen.ts";

export class wxInputStream extends wxStreamBase {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  Delete(): void {
    lib.symbols.wxInputStream_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Eof(): boolean {
    return (lib.symbols.wxInputStream_Eof(this._ptr) as number) !== 0;
  }

  GetC(): number {
    return lib.symbols.wxInputStream_GetC(this._ptr);
  }

  LastRead(): number {
    return lib.symbols.wxInputStream_LastRead(this._ptr);
  }

  Peek(): number {
    return lib.symbols.wxInputStream_Peek(this._ptr);
  }

  Read(buffer: Deno.PointerValue, size: number): void {
    lib.symbols.wxInputStream_Read(this._ptr, buffer, size);
  }

  SeekI(pos: number, mode: number): number {
    return lib.symbols.wxInputStream_SeekI(this._ptr, pos, mode);
  }

  Tell(): number {
    return lib.symbols.wxInputStream_Tell(this._ptr);
  }

  UngetBuffer(buffer: Deno.PointerValue, size: number): number {
    return lib.symbols.wxInputStream_UngetBuffer(this._ptr, buffer, size);
  }

  Ungetch(character: number): number {
    return lib.symbols.wxInputStream_Ungetch(this._ptr, character);
  }

}
