// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxItemContainer {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetCount(): number {
    return lib.symbols.wxItemContainer_GetCount(this.#ptr);
  }

  IsEmpty(): boolean {
    return (lib.symbols.wxItemContainer_IsEmpty(this.#ptr) as number) !== 0;
  }

  GetString(n: number): Deno.PointerValue {
    return lib.symbols.wxItemContainer_GetString(this.#ptr, n);
  }

  SetString(n: number, s: Deno.PointerValue): void {
    lib.symbols.wxItemContainer_SetString(this.#ptr, n, s);
  }

  FindString(s: Deno.PointerValue, caseSensitive: boolean): number {
    return lib.symbols.wxItemContainer_FindString(this.#ptr, s, caseSensitive ? 1 : 0);
  }

  SetSelection(n: number): void {
    lib.symbols.wxItemContainer_SetSelection(this.#ptr, n);
  }

  GetSelection(): number {
    return lib.symbols.wxItemContainer_GetSelection(this.#ptr);
  }

  SetStringSelection(s: Deno.PointerValue): boolean {
    return (lib.symbols.wxItemContainer_SetStringSelection(this.#ptr, s) as number) !== 0;
  }

  GetStringSelection(): Deno.PointerValue {
    return lib.symbols.wxItemContainer_GetStringSelection(this.#ptr);
  }

  Select(n: number): void {
    lib.symbols.wxItemContainer_Select(this.#ptr, n);
  }

  Append(item: Deno.PointerValue): number {
    return lib.symbols.wxItemContainer_Append(this.#ptr, item);
  }

  AppendItems(count: number, items: Deno.PointerValue): number {
    return lib.symbols.wxItemContainer_AppendItems(this.#ptr, count, items);
  }

  Insert(item: Deno.PointerValue, pos: number): number {
    return lib.symbols.wxItemContainer_Insert(this.#ptr, item, pos);
  }

  InsertItems(count: number, items: Deno.PointerValue, pos: number): number {
    return lib.symbols.wxItemContainer_InsertItems(this.#ptr, count, items, pos);
  }

  Set(count: number, items: Deno.PointerValue): void {
    lib.symbols.wxItemContainer_Set(this.#ptr, count, items);
  }

  Clear(): void {
    lib.symbols.wxItemContainer_Clear(this.#ptr);
  }

  Delete(pos: number): void {
    lib.symbols.wxItemContainer_Delete(this.#ptr, pos);
  }

  IsSorted(): boolean {
    return (lib.symbols.wxItemContainer_IsSorted(this.#ptr) as number) !== 0;
  }

  SetClientData(n: number, clientData: Deno.PointerValue): void {
    lib.symbols.wxItemContainer_SetClientData(this.#ptr, n, clientData);
  }

  GetClientData(n: number): Deno.PointerValue {
    return lib.symbols.wxItemContainer_GetClientData(this.#ptr, n);
  }

  HasClientData(): boolean {
    return (lib.symbols.wxItemContainer_HasClientData(this.#ptr) as number) !== 0;
  }

}
