// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxEvent } from "./wxEvent_gen.ts";

export class wxJoystickEvent extends wxEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  ButtonDown(but: number): boolean {
    return (lib.symbols.wxJoystickEvent_ButtonDown(this._ptr, but) as number) !== 0;
  }

  ButtonIsDown(but: number): boolean {
    return (lib.symbols.wxJoystickEvent_ButtonIsDown(this._ptr, but) as number) !== 0;
  }

  ButtonUp(but: number): boolean {
    return (lib.symbols.wxJoystickEvent_ButtonUp(this._ptr, but) as number) !== 0;
  }

  GetButtonChange(): number {
    return lib.symbols.wxJoystickEvent_GetButtonChange(this._ptr);
  }

  GetButtonState(): number {
    return lib.symbols.wxJoystickEvent_GetButtonState(this._ptr);
  }

  GetJoystick(): number {
    return lib.symbols.wxJoystickEvent_GetJoystick(this._ptr);
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxJoystickEvent_GetPosition(this._ptr);
  }

  GetZPosition(): number {
    return lib.symbols.wxJoystickEvent_GetZPosition(this._ptr);
  }

  IsButton(): boolean {
    return (lib.symbols.wxJoystickEvent_IsButton(this._ptr) as number) !== 0;
  }

  IsMove(): boolean {
    return (lib.symbols.wxJoystickEvent_IsMove(this._ptr) as number) !== 0;
  }

  IsZMove(): boolean {
    return (lib.symbols.wxJoystickEvent_IsZMove(this._ptr) as number) !== 0;
  }

  SetButtonChange(change: number): void {
    lib.symbols.wxJoystickEvent_SetButtonChange(this._ptr, change);
  }

  SetButtonState(state: number): void {
    lib.symbols.wxJoystickEvent_SetButtonState(this._ptr, state);
  }

  SetJoystick(stick: number): void {
    lib.symbols.wxJoystickEvent_SetJoystick(this._ptr, stick);
  }

  SetPosition(x: number, y: number): void {
    lib.symbols.wxJoystickEvent_SetPosition(this._ptr, x, y);
  }

  SetZPosition(zPos: number): void {
    lib.symbols.wxJoystickEvent_SetZPosition(this._ptr, zPos);
  }

}
