// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxJoystickEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  ButtonDown(but: number): boolean {
    return (lib.symbols.wxJoystickEvent_ButtonDown(this.#ptr, but) as number) !== 0;
  }

  ButtonIsDown(but: number): boolean {
    return (lib.symbols.wxJoystickEvent_ButtonIsDown(this.#ptr, but) as number) !== 0;
  }

  ButtonUp(but: number): boolean {
    return (lib.symbols.wxJoystickEvent_ButtonUp(this.#ptr, but) as number) !== 0;
  }

  GetButtonChange(): number {
    return lib.symbols.wxJoystickEvent_GetButtonChange(this.#ptr);
  }

  GetButtonState(): number {
    return lib.symbols.wxJoystickEvent_GetButtonState(this.#ptr);
  }

  GetJoystick(): number {
    return lib.symbols.wxJoystickEvent_GetJoystick(this.#ptr);
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxJoystickEvent_GetPosition(this.#ptr);
  }

  GetZPosition(): number {
    return lib.symbols.wxJoystickEvent_GetZPosition(this.#ptr);
  }

  IsButton(): boolean {
    return (lib.symbols.wxJoystickEvent_IsButton(this.#ptr) as number) !== 0;
  }

  IsMove(): boolean {
    return (lib.symbols.wxJoystickEvent_IsMove(this.#ptr) as number) !== 0;
  }

  IsZMove(): boolean {
    return (lib.symbols.wxJoystickEvent_IsZMove(this.#ptr) as number) !== 0;
  }

  SetButtonChange(change: number): void {
    lib.symbols.wxJoystickEvent_SetButtonChange(this.#ptr, change);
  }

  SetButtonState(state: number): void {
    lib.symbols.wxJoystickEvent_SetButtonState(this.#ptr, state);
  }

  SetJoystick(stick: number): void {
    lib.symbols.wxJoystickEvent_SetJoystick(this.#ptr, stick);
  }

  SetPosition(x: number, y: number): void {
    lib.symbols.wxJoystickEvent_SetPosition(this.#ptr, x, y);
  }

  SetZPosition(zPos: number): void {
    lib.symbols.wxJoystickEvent_SetZPosition(this.#ptr, zPos);
  }

}
