// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxListItem {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxListItem | null {
    const rawPtr = lib.symbols.wxListItem_Create();
    if (rawPtr === null) return null;
    return new wxListItem(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxListItem_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Clear(): void {
    lib.symbols.wxListItem_Clear(this.#ptr);
  }

  ClearAttributes(): void {
    lib.symbols.wxListItem_ClearAttributes(this.#ptr);
  }

  GetAlign(): number {
    return lib.symbols.wxListItem_GetAlign(this.#ptr);
  }

  GetAttributes(): Deno.PointerValue {
    return lib.symbols.wxListItem_GetAttributes(this.#ptr);
  }

  GetBackgroundColour(ref: Deno.PointerValue): void {
    lib.symbols.wxListItem_GetBackgroundColour(this.#ptr, ref);
  }

  GetColumn(): number {
    return lib.symbols.wxListItem_GetColumn(this.#ptr);
  }

  GetData(): number {
    return lib.symbols.wxListItem_GetData(this.#ptr);
  }

  GetFont(ref: Deno.PointerValue): void {
    lib.symbols.wxListItem_GetFont(this.#ptr, ref);
  }

  GetId(): number {
    return lib.symbols.wxListItem_GetId(this.#ptr);
  }

  GetImage(): number {
    return lib.symbols.wxListItem_GetImage(this.#ptr);
  }

  GetMask(): number {
    return lib.symbols.wxListItem_GetMask(this.#ptr);
  }

  GetState(): number {
    return lib.symbols.wxListItem_GetState(this.#ptr);
  }

  GetText(): Deno.PointerValue {
    return lib.symbols.wxListItem_GetText(this.#ptr);
  }

  GetTextColour(ref: Deno.PointerValue): void {
    lib.symbols.wxListItem_GetTextColour(this.#ptr, ref);
  }

  GetWidth(): number {
    return lib.symbols.wxListItem_GetWidth(this.#ptr);
  }

  HasAttributes(): boolean {
    return (lib.symbols.wxListItem_HasAttributes(this.#ptr) as number) !== 0;
  }

  SetAlign(align: number): void {
    lib.symbols.wxListItem_SetAlign(this.#ptr, align);
  }

  SetBackgroundColour(colBack: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetBackgroundColour(this.#ptr, colBack);
  }

  SetColumn(col: number): void {
    lib.symbols.wxListItem_SetColumn(this.#ptr, col);
  }

  SetData(data: number): void {
    lib.symbols.wxListItem_SetData(this.#ptr, data);
  }

  SetDataPointer(data: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetDataPointer(this.#ptr, data);
  }

  SetFont(font: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetFont(this.#ptr, font);
  }

  SetId(id: number): void {
    lib.symbols.wxListItem_SetId(this.#ptr, id);
  }

  SetImage(image: number): void {
    lib.symbols.wxListItem_SetImage(this.#ptr, image);
  }

  SetMask(mask: number): void {
    lib.symbols.wxListItem_SetMask(this.#ptr, mask);
  }

  SetState(state: number): void {
    lib.symbols.wxListItem_SetState(this.#ptr, state);
  }

  SetStateMask(stateMask: number): void {
    lib.symbols.wxListItem_SetStateMask(this.#ptr, stateMask);
  }

  SetText(text: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetText(this.#ptr, text);
  }

  SetTextColour(colText: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetTextColour(this.#ptr, colText);
  }

  SetWidth(width: number): void {
    lib.symbols.wxListItem_SetWidth(this.#ptr, width);
  }

}
