// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxListItem {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxListItem | null {
    const rawPtr = lib.symbols.wxListItem_Create();
    if (rawPtr === null) return null;
    return new wxListItem(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxListItem_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Clear(): void {
    lib.symbols.wxListItem_Clear(this._ptr);
  }

  ClearAttributes(): void {
    lib.symbols.wxListItem_ClearAttributes(this._ptr);
  }

  GetAlign(): number {
    return lib.symbols.wxListItem_GetAlign(this._ptr);
  }

  GetAttributes(): Deno.PointerValue {
    return lib.symbols.wxListItem_GetAttributes(this._ptr);
  }

  GetBackgroundColour(ref: Deno.PointerValue): void {
    lib.symbols.wxListItem_GetBackgroundColour(this._ptr, ref);
  }

  GetColumn(): number {
    return lib.symbols.wxListItem_GetColumn(this._ptr);
  }

  GetData(): number {
    return lib.symbols.wxListItem_GetData(this._ptr);
  }

  GetFont(ref: Deno.PointerValue): void {
    lib.symbols.wxListItem_GetFont(this._ptr, ref);
  }

  GetId(): number {
    return lib.symbols.wxListItem_GetId(this._ptr);
  }

  GetImage(): number {
    return lib.symbols.wxListItem_GetImage(this._ptr);
  }

  GetMask(): number {
    return lib.symbols.wxListItem_GetMask(this._ptr);
  }

  GetState(): number {
    return lib.symbols.wxListItem_GetState(this._ptr);
  }

  GetText(): Deno.PointerValue {
    return lib.symbols.wxListItem_GetText(this._ptr);
  }

  GetTextColour(ref: Deno.PointerValue): void {
    lib.symbols.wxListItem_GetTextColour(this._ptr, ref);
  }

  GetWidth(): number {
    return lib.symbols.wxListItem_GetWidth(this._ptr);
  }

  HasAttributes(): boolean {
    return (lib.symbols.wxListItem_HasAttributes(this._ptr) as number) !== 0;
  }

  SetAlign(align: number): void {
    lib.symbols.wxListItem_SetAlign(this._ptr, align);
  }

  SetBackgroundColour(colBack: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetBackgroundColour(this._ptr, colBack);
  }

  SetColumn(col: number): void {
    lib.symbols.wxListItem_SetColumn(this._ptr, col);
  }

  SetData(data: number): void {
    lib.symbols.wxListItem_SetData(this._ptr, data);
  }

  SetDataPointer(data: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetDataPointer(this._ptr, data);
  }

  SetFont(font: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetFont(this._ptr, font);
  }

  SetId(id: number): void {
    lib.symbols.wxListItem_SetId(this._ptr, id);
  }

  SetImage(image: number): void {
    lib.symbols.wxListItem_SetImage(this._ptr, image);
  }

  SetMask(mask: number): void {
    lib.symbols.wxListItem_SetMask(this._ptr, mask);
  }

  SetState(state: number): void {
    lib.symbols.wxListItem_SetState(this._ptr, state);
  }

  SetStateMask(stateMask: number): void {
    lib.symbols.wxListItem_SetStateMask(this._ptr, stateMask);
  }

  SetText(text: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetText(this._ptr, text);
  }

  SetTextColour(colText: Deno.PointerValue): void {
    lib.symbols.wxListItem_SetTextColour(this._ptr, colText);
  }

  SetWidth(width: number): void {
    lib.symbols.wxListItem_SetWidth(this._ptr, width);
  }

}
