// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxBookCtrlBase } from "./wxBookCtrlBase_gen.ts";

export class wxListbook extends wxBookCtrlBase {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxListbook | null {
    const rawPtr = lib.symbols.wxListbook_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxListbook(rawPtr);
  }

  AddPage(pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxListbook_AddPage(this._ptr, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  AdvanceSelection(bForward: boolean): void {
    lib.symbols.wxListbook_AdvanceSelection(this._ptr, bForward ? 1 : 0);
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxListbook_DeleteAllPages(this._ptr) as number) !== 0;
  }

  DeletePage(nPage: number): boolean {
    return (lib.symbols.wxListbook_DeletePage(this._ptr, nPage) as number) !== 0;
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxListbook_GetImageList(this._ptr);
  }

  GetListView(): Deno.PointerValue {
    return lib.symbols.wxListbook_GetListView(this._ptr);
  }

  GetPage(nPage: number): Deno.PointerValue {
    return lib.symbols.wxListbook_GetPage(this._ptr, nPage);
  }

  GetPageCount(): number {
    return lib.symbols.wxListbook_GetPageCount(this._ptr);
  }

  GetPageImage(nPage: number): number {
    return lib.symbols.wxListbook_GetPageImage(this._ptr, nPage);
  }

  GetPageText(nPage: number): Deno.PointerValue {
    return lib.symbols.wxListbook_GetPageText(this._ptr, nPage);
  }

  GetSelection(): number {
    return lib.symbols.wxListbook_GetSelection(this._ptr);
  }

  HitTest(x: number, y: number, flags: Deno.PointerValue): number {
    return lib.symbols.wxListbook_HitTest(this._ptr, x, y, flags);
  }

  InsertPage(nPage: number, pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxListbook_InsertPage(this._ptr, nPage, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(nPage: number): boolean {
    return (lib.symbols.wxListbook_RemovePage(this._ptr, nPage) as number) !== 0;
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxListbook_SetImageList(this._ptr, imageList);
  }

  SetPageImage(nPage: number, nImage: number): boolean {
    return (lib.symbols.wxListbook_SetPageImage(this._ptr, nPage, nImage) as number) !== 0;
  }

  SetPageText(nPage: number, strText: Deno.PointerValue): boolean {
    return (lib.symbols.wxListbook_SetPageText(this._ptr, nPage, strText) as number) !== 0;
  }

  SetSelection(nPage: number): number {
    return lib.symbols.wxListbook_SetSelection(this._ptr, nPage);
  }

}
