// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxNotifyEvent } from "./wxNotifyEvent_gen.ts";

export class wxListEvent extends wxNotifyEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  Cancelled(): boolean {
    return (lib.symbols.wxListEvent_Cancelled(this._ptr) as number) !== 0;
  }

  GetCode(): number {
    return lib.symbols.wxListEvent_GetCode(this._ptr);
  }

  GetColumn(): number {
    return lib.symbols.wxListEvent_GetColumn(this._ptr);
  }

  GetData(): number {
    return lib.symbols.wxListEvent_GetData(this._ptr);
  }

  GetImage(): number {
    return lib.symbols.wxListEvent_GetImage(this._ptr);
  }

  GetIndex(): number {
    return lib.symbols.wxListEvent_GetIndex(this._ptr);
  }

  GetItem(ref: Deno.PointerValue): void {
    lib.symbols.wxListEvent_GetItem(this._ptr, ref);
  }

  GetLabel(): Deno.PointerValue {
    return lib.symbols.wxListEvent_GetLabel(this._ptr);
  }

  GetMask(): number {
    return lib.symbols.wxListEvent_GetMask(this._ptr);
  }

  GetPoint(): Deno.PointerValue {
    return lib.symbols.wxListEvent_GetPoint(this._ptr);
  }

  GetText(): Deno.PointerValue {
    return lib.symbols.wxListEvent_GetText(this._ptr);
  }

}
