// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxListBox extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, n: number, str: Deno.PointerValue, style: number): wxListBox | null {
    const rawPtr = lib.symbols.wxListBox_Create(parent, id, left, top, width, height, n, str, style);
    if (rawPtr === null) return null;
    return new wxListBox(rawPtr);
  }

  Append(item: Deno.PointerValue): void {
    lib.symbols.wxListBox_Append(this._ptr, item);
  }

  AppendData(item: Deno.PointerValue, data: Deno.PointerValue): void {
    lib.symbols.wxListBox_AppendData(this._ptr, item, data);
  }

  Clear(): void {
    lib.symbols.wxListBox_Clear(this._ptr);
  }

  Delete(index: number): void {
    lib.symbols.wxListBox_Delete(this._ptr, index);
  }

  FindString(str: Deno.PointerValue): number {
    return lib.symbols.wxListBox_FindString(this._ptr, str);
  }

  GetClientData(index: number): Deno.PointerValue {
    return lib.symbols.wxListBox_GetClientData(this._ptr, index);
  }

  GetCount(): number {
    return lib.symbols.wxListBox_GetCount(this._ptr);
  }

  GetSelection(): number {
    return lib.symbols.wxListBox_GetSelection(this._ptr);
  }

  GetSelections(aSelections: Deno.PointerValue, allocated: number): number {
    return lib.symbols.wxListBox_GetSelections(this._ptr, aSelections, allocated);
  }

  GetString(index: number): Deno.PointerValue {
    return lib.symbols.wxListBox_GetString(this._ptr, index);
  }

  InsertItems(items: Deno.PointerValue, pos: number, count: number): void {
    lib.symbols.wxListBox_InsertItems(this._ptr, items, pos, count);
  }

  IsSelected(index: number): boolean {
    return (lib.symbols.wxListBox_IsSelected(this._ptr, index) as number) !== 0;
  }

  SetClientData(index: number, clientData: Deno.PointerValue): void {
    lib.symbols.wxListBox_SetClientData(this._ptr, index, clientData);
  }

  SetFirstItem(index: number): void {
    lib.symbols.wxListBox_SetFirstItem(this._ptr, index);
  }

  SetSelection(index: number, select: boolean): void {
    lib.symbols.wxListBox_SetSelection(this._ptr, index, select ? 1 : 0);
  }

  SetString(index: number, str: Deno.PointerValue): void {
    lib.symbols.wxListBox_SetString(this._ptr, index, str);
  }

  SetStringSelection(str: Deno.PointerValue, sel: boolean): void {
    lib.symbols.wxListBox_SetStringSelection(this._ptr, str, sel ? 1 : 0);
  }

  EnsureVisible(index: number): void {
    lib.symbols.wxListBox_EnsureVisible(this._ptr, index);
  }

  HitTest(x: number, y: number): number {
    return lib.symbols.wxListBox_HitTest(this._ptr, x, y);
  }

  GetTopItem(): number {
    return lib.symbols.wxListBox_GetTopItem(this._ptr);
  }

  GetCountPerPage(): number {
    return lib.symbols.wxListBox_GetCountPerPage(this._ptr);
  }

}
