// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxLogChain {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(logger: Deno.PointerValue): wxLogChain | null {
    const rawPtr = lib.symbols.wxLogChain_Create(logger);
    if (rawPtr === null) return null;
    return new wxLogChain(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxLogChain_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetOldLog(): Deno.PointerValue {
    return lib.symbols.wxLogChain_GetOldLog(this.#ptr);
  }

  IsPassingMessages(): boolean {
    return (lib.symbols.wxLogChain_IsPassingMessages(this.#ptr) as number) !== 0;
  }

  PassMessages(bDoPass: boolean): void {
    lib.symbols.wxLogChain_PassMessages(this.#ptr, bDoPass ? 1 : 0);
  }

  SetLog(logger: Deno.PointerValue): void {
    lib.symbols.wxLogChain_SetLog(this.#ptr, logger);
  }

}
