// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxLocale {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(name: number, flags: number): wxLocale | null {
    const rawPtr = lib.symbols.wxLocale_Create(name, flags);
    if (rawPtr === null) return null;
    return new wxLocale(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxLocale_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddCatalog(szDomain: Deno.PointerValue, msgIdLanguage: number): number {
    return lib.symbols.wxLocale_AddCatalog(this._ptr, szDomain, msgIdLanguage);
  }

  AddCatalogLookupPathPrefix(prefix: Deno.PointerValue): void {
    lib.symbols.wxLocale_AddCatalogLookupPathPrefix(this._ptr, prefix);
  }

  GetLocale(): Deno.PointerValue {
    return lib.symbols.wxLocale_GetLocale(this._ptr);
  }

  GetName(): Deno.PointerValue {
    return lib.symbols.wxLocale_GetName(this._ptr);
  }

  GetString(szOrigString: Deno.PointerValue, szDomain: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxLocale_GetString(this._ptr, szOrigString, szDomain);
  }

  IsLoaded(szDomain: Deno.PointerValue): boolean {
    return (lib.symbols.wxLocale_IsLoaded(this._ptr, szDomain) as number) !== 0;
  }

  IsOk(): boolean {
    return (lib.symbols.wxLocale_IsOk(this._ptr) as number) !== 0;
  }

}
