// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMDIParentFrame {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxMDIParentFrame | null {
    const rawPtr = lib.symbols.wxMDIParentFrame_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxMDIParentFrame(rawPtr);
  }

  ActivateNext(): void {
    lib.symbols.wxMDIParentFrame_ActivateNext(this.#ptr);
  }

  ActivatePrevious(): void {
    lib.symbols.wxMDIParentFrame_ActivatePrevious(this.#ptr);
  }

  ArrangeIcons(): void {
    lib.symbols.wxMDIParentFrame_ArrangeIcons(this.#ptr);
  }

  Cascade(): void {
    lib.symbols.wxMDIParentFrame_Cascade(this.#ptr);
  }

  GetActiveChild(): Deno.PointerValue {
    return lib.symbols.wxMDIParentFrame_GetActiveChild(this.#ptr);
  }

  GetClientWindow(): Deno.PointerValue {
    return lib.symbols.wxMDIParentFrame_GetClientWindow(this.#ptr);
  }

  GetWindowMenu(): Deno.PointerValue {
    return lib.symbols.wxMDIParentFrame_GetWindowMenu(this.#ptr);
  }

  OnCreateClient(): Deno.PointerValue {
    return lib.symbols.wxMDIParentFrame_OnCreateClient(this.#ptr);
  }

  SetWindowMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxMDIParentFrame_SetWindowMenu(this.#ptr, menu);
  }

  Tile(orient: number): void {
    lib.symbols.wxMDIParentFrame_Tile(this.#ptr, orient);
  }

}
