// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxFrame } from "./wxFrame_gen.ts";

export class wxMDIChildFrame extends wxFrame {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxMDIChildFrame | null {
    const rawPtr = lib.symbols.wxMDIChildFrame_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxMDIChildFrame(rawPtr);
  }

  Activate(): void {
    lib.symbols.wxMDIChildFrame_Activate(this._ptr);
  }

  GetMDIParent(): Deno.PointerValue {
    return lib.symbols.wxMDIChildFrame_GetMDIParent(this._ptr);
  }

}
