// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxDialog } from "./wxDialog_gen.ts";

export class wxMessageDialog extends wxDialog {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, message: Deno.PointerValue, caption: Deno.PointerValue, style: number): wxMessageDialog | null {
    const rawPtr = lib.symbols.wxMessageDialog_Create(parent, message, caption, style);
    if (rawPtr === null) return null;
    return new wxMessageDialog(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxMessageDialog_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  ShowModal(): number {
    return lib.symbols.wxMessageDialog_ShowModal(this._ptr);
  }

  SetMessage(message: Deno.PointerValue): void {
    lib.symbols.wxMessageDialog_SetMessage(this._ptr, message);
  }

  GetMessage(): Deno.PointerValue {
    return lib.symbols.wxMessageDialog_GetMessage(this._ptr);
  }

  SetExtendedMessage(message: Deno.PointerValue): void {
    lib.symbols.wxMessageDialog_SetExtendedMessage(this._ptr, message);
  }

  GetExtendedMessage(): Deno.PointerValue {
    return lib.symbols.wxMessageDialog_GetExtendedMessage(this._ptr);
  }

  SetOKLabel(label: Deno.PointerValue): boolean {
    return (lib.symbols.wxMessageDialog_SetOKLabel(this._ptr, label) as number) !== 0;
  }

  SetOKCancelLabels(ok: Deno.PointerValue, cancel: Deno.PointerValue): boolean {
    return (lib.symbols.wxMessageDialog_SetOKCancelLabels(this._ptr, ok, cancel) as number) !== 0;
  }

  SetYesNoLabels(yes: Deno.PointerValue, no: Deno.PointerValue): boolean {
    return (lib.symbols.wxMessageDialog_SetYesNoLabels(this._ptr, yes, no) as number) !== 0;
  }

  SetYesNoCancelLabels(yes: Deno.PointerValue, no: Deno.PointerValue, cancel: Deno.PointerValue): boolean {
    return (lib.symbols.wxMessageDialog_SetYesNoCancelLabels(this._ptr, yes, no, cancel) as number) !== 0;
  }

  SetHelpLabel(label: Deno.PointerValue): boolean {
    return (lib.symbols.wxMessageDialog_SetHelpLabel(this._ptr, label) as number) !== 0;
  }

}
