// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMetafileDC {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(filePath: Deno.PointerValue): wxMetafileDC | null {
    const rawPtr = lib.symbols.wxMetafileDC_Create(filePath);
    if (rawPtr === null) return null;
    return new wxMetafileDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxMetafileDC_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Close(): Deno.PointerValue {
    return lib.symbols.wxMetafileDC_Close(this.#ptr);
  }

}
