// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMenuBar {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(style: number): wxMenuBar | null {
    const rawPtr = lib.symbols.wxMenuBar_Create(style);
    if (rawPtr === null) return null;
    return new wxMenuBar(rawPtr);
  }

  Append(menu: Deno.PointerValue, title: Deno.PointerValue): number {
    return lib.symbols.wxMenuBar_Append(this.#ptr, menu, title);
  }

  Check(id: number, check: boolean): void {
    lib.symbols.wxMenuBar_Check(this.#ptr, id, check ? 1 : 0);
  }

  DeletePointer(): void {
    lib.symbols.wxMenuBar_DeletePointer(this.#ptr);
  }

  Enable(enable: boolean): number {
    return lib.symbols.wxMenuBar_Enable(this.#ptr, enable ? 1 : 0);
  }

  EnableItem(id: number, enable: boolean): void {
    lib.symbols.wxMenuBar_EnableItem(this.#ptr, id, enable ? 1 : 0);
  }

  EnableTop(pos: number, enable: boolean): void {
    lib.symbols.wxMenuBar_EnableTop(this.#ptr, pos, enable ? 1 : 0);
  }

  FindItem(id: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_FindItem(this.#ptr, id);
  }

  FindMenu(title: Deno.PointerValue): number {
    return lib.symbols.wxMenuBar_FindMenu(this.#ptr, title);
  }

  FindMenuItem(menuString: Deno.PointerValue, itemString: Deno.PointerValue): number {
    return lib.symbols.wxMenuBar_FindMenuItem(this.#ptr, menuString, itemString);
  }

  GetHelpString(id: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_GetHelpString(this.#ptr, id);
  }

  GetLabel(id: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_GetLabel(this.#ptr, id);
  }

  GetMenuLabel(pos: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_GetMenuLabel(this.#ptr, pos);
  }

  GetMenu(pos: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_GetMenu(this.#ptr, pos);
  }

  GetMenuCount(): number {
    return lib.symbols.wxMenuBar_GetMenuCount(this.#ptr);
  }

  Insert(pos: number, menu: Deno.PointerValue, title: Deno.PointerValue): number {
    return lib.symbols.wxMenuBar_Insert(this.#ptr, pos, menu, title);
  }

  IsChecked(id: number): boolean {
    return (lib.symbols.wxMenuBar_IsChecked(this.#ptr, id) as number) !== 0;
  }

  IsEnabled(id: number): boolean {
    return (lib.symbols.wxMenuBar_IsEnabled(this.#ptr, id) as number) !== 0;
  }

  Remove(pos: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_Remove(this.#ptr, pos);
  }

  Replace(pos: number, menu: Deno.PointerValue, title: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxMenuBar_Replace(this.#ptr, pos, menu, title);
  }

  SetHelpString(id: number, helpString: Deno.PointerValue): void {
    lib.symbols.wxMenuBar_SetHelpString(this.#ptr, id, helpString);
  }

  SetItemLabel(id: number, label: Deno.PointerValue): void {
    lib.symbols.wxMenuBar_SetItemLabel(this.#ptr, id, label);
  }

  SetLabel(str: Deno.PointerValue): void {
    lib.symbols.wxMenuBar_SetLabel(this.#ptr, str);
  }

  SetMenuLabel(pos: number, label: Deno.PointerValue): void {
    lib.symbols.wxMenuBar_SetMenuLabel(this.#ptr, pos, label);
  }

  IsEnabledTop(pos: number): boolean {
    return (lib.symbols.wxMenuBar_IsEnabledTop(this.#ptr, pos) as number) !== 0;
  }

  GetMenuLabelText(pos: number): Deno.PointerValue {
    return lib.symbols.wxMenuBar_GetMenuLabelText(this.#ptr, pos);
  }

  UpdateMenus(): void {
    lib.symbols.wxMenuBar_UpdateMenus(this.#ptr);
  }

}
