// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMenuItem {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxMenuItem | null {
    const rawPtr = lib.symbols.wxMenuItem_Create();
    if (rawPtr === null) return null;
    return new wxMenuItem(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxMenuItem_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Check(check: boolean): void {
    lib.symbols.wxMenuItem_Check(this._ptr, check ? 1 : 0);
  }

  Enable(enable: boolean): void {
    lib.symbols.wxMenuItem_Enable(this._ptr, enable ? 1 : 0);
  }

  GetHelp(): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetHelp(this._ptr);
  }

  GetId(): number {
    return lib.symbols.wxMenuItem_GetId(this._ptr);
  }

  GetItemLabelText(): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetItemLabelText(this._ptr);
  }

  GetLabelText(text: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetLabelText(text);
  }

  GetMenu(): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetMenu(this._ptr);
  }

  GetSubMenu(): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetSubMenu(this._ptr);
  }

  GetItemLabel(): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetItemLabel(this._ptr);
  }

  IsCheckable(): boolean {
    return (lib.symbols.wxMenuItem_IsCheckable(this._ptr) as number) !== 0;
  }

  IsChecked(): boolean {
    return (lib.symbols.wxMenuItem_IsChecked(this._ptr) as number) !== 0;
  }

  IsEnabled(): boolean {
    return (lib.symbols.wxMenuItem_IsEnabled(this._ptr) as number) !== 0;
  }

  IsSeparator(): boolean {
    return (lib.symbols.wxMenuItem_IsSeparator(this._ptr) as number) !== 0;
  }

  IsSubMenu(): boolean {
    return (lib.symbols.wxMenuItem_IsSubMenu(this._ptr) as number) !== 0;
  }

  SetCheckable(checkable: boolean): void {
    lib.symbols.wxMenuItem_SetCheckable(this._ptr, checkable ? 1 : 0);
  }

  SetHelp(str: Deno.PointerValue): void {
    lib.symbols.wxMenuItem_SetHelp(this._ptr, str);
  }

  SetId(id: number): void {
    lib.symbols.wxMenuItem_SetId(this._ptr, id);
  }

  SetSubMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxMenuItem_SetSubMenu(this._ptr, menu);
  }

  SetItemLabel(str: Deno.PointerValue): void {
    lib.symbols.wxMenuItem_SetItemLabel(this._ptr, str);
  }

  GetKind(): number {
    return lib.symbols.wxMenuItem_GetKind(this._ptr);
  }

  IsCheck(): boolean {
    return (lib.symbols.wxMenuItem_IsCheck(this._ptr) as number) !== 0;
  }

  IsRadio(): boolean {
    return (lib.symbols.wxMenuItem_IsRadio(this._ptr) as number) !== 0;
  }

  Toggle(): void {
    lib.symbols.wxMenuItem_Toggle(this._ptr);
  }

  SetBitmap(bmp: Deno.PointerValue): void {
    lib.symbols.wxMenuItem_SetBitmap(this._ptr, bmp);
  }

  GetBitmap(): Deno.PointerValue {
    return lib.symbols.wxMenuItem_GetBitmap(this._ptr);
  }

}
