// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMimeTypesManager {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxMimeTypesManager | null {
    const rawPtr = lib.symbols.wxMimeTypesManager_Create();
    if (rawPtr === null) return null;
    return new wxMimeTypesManager(rawPtr);
  }

  AddFallbacks(types: Deno.PointerValue): void {
    lib.symbols.wxMimeTypesManager_AddFallbacks(this.#ptr, types);
  }

  EnumAllFileTypes(list: Deno.PointerValue): number {
    return lib.symbols.wxMimeTypesManager_EnumAllFileTypes(this.#ptr, list);
  }

  GetFileTypeFromExtension(extension: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxMimeTypesManager_GetFileTypeFromExtension(this.#ptr, extension);
  }

  GetFileTypeFromMimeType(name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxMimeTypesManager_GetFileTypeFromMimeType(this.#ptr, name);
  }

  IsOfType(type_: Deno.PointerValue, wildcard: Deno.PointerValue): boolean {
    return (lib.symbols.wxMimeTypesManager_IsOfType(this.#ptr, type_, wildcard) as number) !== 0;
  }

}
