// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMirrorDC {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(dc: Deno.PointerValue): wxMirrorDC | null {
    const rawPtr = lib.symbols.wxMirrorDC_Create(dc);
    if (rawPtr === null) return null;
    return new wxMirrorDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxMirrorDC_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
