// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMouseEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  AltDown(): boolean {
    return (lib.symbols.wxMouseEvent_AltDown(this.#ptr) as number) !== 0;
  }

  Button(but: number): boolean {
    return (lib.symbols.wxMouseEvent_Button(this.#ptr, but) as number) !== 0;
  }

  ButtonDClick(but: number): boolean {
    return (lib.symbols.wxMouseEvent_ButtonDClick(this.#ptr, but) as number) !== 0;
  }

  ButtonDown(but: number): boolean {
    return (lib.symbols.wxMouseEvent_ButtonDown(this.#ptr, but) as number) !== 0;
  }

  ButtonIsDown(but: number): boolean {
    return (lib.symbols.wxMouseEvent_ButtonIsDown(this.#ptr, but) as number) !== 0;
  }

  ButtonUp(but: number): boolean {
    return (lib.symbols.wxMouseEvent_ButtonUp(this.#ptr, but) as number) !== 0;
  }

  ControlDown(): boolean {
    return (lib.symbols.wxMouseEvent_ControlDown(this.#ptr) as number) !== 0;
  }

  Dragging(): boolean {
    return (lib.symbols.wxMouseEvent_Dragging(this.#ptr) as number) !== 0;
  }

  Entering(): boolean {
    return (lib.symbols.wxMouseEvent_Entering(this.#ptr) as number) !== 0;
  }

  GetLogicalPosition(dc: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxMouseEvent_GetLogicalPosition(this.#ptr, dc);
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxMouseEvent_GetPosition(this.#ptr);
  }

  GetX(): number {
    return lib.symbols.wxMouseEvent_GetX(this.#ptr);
  }

  GetY(): number {
    return lib.symbols.wxMouseEvent_GetY(this.#ptr);
  }

  IsButton(): boolean {
    return (lib.symbols.wxMouseEvent_IsButton(this.#ptr) as number) !== 0;
  }

  Leaving(): boolean {
    return (lib.symbols.wxMouseEvent_Leaving(this.#ptr) as number) !== 0;
  }

  LeftDClick(): boolean {
    return (lib.symbols.wxMouseEvent_LeftDClick(this.#ptr) as number) !== 0;
  }

  LeftDown(): boolean {
    return (lib.symbols.wxMouseEvent_LeftDown(this.#ptr) as number) !== 0;
  }

  LeftIsDown(): boolean {
    return (lib.symbols.wxMouseEvent_LeftIsDown(this.#ptr) as number) !== 0;
  }

  LeftUp(): boolean {
    return (lib.symbols.wxMouseEvent_LeftUp(this.#ptr) as number) !== 0;
  }

  MetaDown(): boolean {
    return (lib.symbols.wxMouseEvent_MetaDown(this.#ptr) as number) !== 0;
  }

  MiddleDClick(): boolean {
    return (lib.symbols.wxMouseEvent_MiddleDClick(this.#ptr) as number) !== 0;
  }

  MiddleDown(): boolean {
    return (lib.symbols.wxMouseEvent_MiddleDown(this.#ptr) as number) !== 0;
  }

  MiddleIsDown(): boolean {
    return (lib.symbols.wxMouseEvent_MiddleIsDown(this.#ptr) as number) !== 0;
  }

  MiddleUp(): boolean {
    return (lib.symbols.wxMouseEvent_MiddleUp(this.#ptr) as number) !== 0;
  }

  Moving(): boolean {
    return (lib.symbols.wxMouseEvent_Moving(this.#ptr) as number) !== 0;
  }

  RightDClick(): boolean {
    return (lib.symbols.wxMouseEvent_RightDClick(this.#ptr) as number) !== 0;
  }

  RightDown(): boolean {
    return (lib.symbols.wxMouseEvent_RightDown(this.#ptr) as number) !== 0;
  }

  RightIsDown(): boolean {
    return (lib.symbols.wxMouseEvent_RightIsDown(this.#ptr) as number) !== 0;
  }

  RightUp(): boolean {
    return (lib.symbols.wxMouseEvent_RightUp(this.#ptr) as number) !== 0;
  }

  ShiftDown(): boolean {
    return (lib.symbols.wxMouseEvent_ShiftDown(this.#ptr) as number) !== 0;
  }

}
