// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxEvent } from "./wxEvent_gen.ts";

export class wxMoveEvent extends wxEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxMoveEvent_GetPosition(this._ptr);
  }

}
