// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxMutex {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxMutex | null {
    const rawPtr = lib.symbols.wxMutex_Create();
    if (rawPtr === null) return null;
    return new wxMutex(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxMutex_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Lock(): number {
    return lib.symbols.wxMutex_Lock(this.#ptr);
  }

  TryLock(): number {
    return lib.symbols.wxMutex_TryLock(this.#ptr);
  }

  Unlock(): number {
    return lib.symbols.wxMutex_Unlock(this.#ptr);
  }

}
