// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxNotebook {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxNotebook | null {
    const rawPtr = lib.symbols.wxNotebook_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxNotebook(rawPtr);
  }

  AddPage(pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxNotebook_AddPage(this.#ptr, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  AdvanceSelection(bForward: boolean): void {
    lib.symbols.wxNotebook_AdvanceSelection(this.#ptr, bForward ? 1 : 0);
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxNotebook_DeleteAllPages(this.#ptr) as number) !== 0;
  }

  DeletePage(nPage: number): boolean {
    return (lib.symbols.wxNotebook_DeletePage(this.#ptr, nPage) as number) !== 0;
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxNotebook_GetImageList(this.#ptr);
  }

  GetPage(nPage: number): Deno.PointerValue {
    return lib.symbols.wxNotebook_GetPage(this.#ptr, nPage);
  }

  GetPageCount(): number {
    return lib.symbols.wxNotebook_GetPageCount(this.#ptr);
  }

  GetPageImage(nPage: number): number {
    return lib.symbols.wxNotebook_GetPageImage(this.#ptr, nPage);
  }

  GetPageText(nPage: number): Deno.PointerValue {
    return lib.symbols.wxNotebook_GetPageText(this.#ptr, nPage);
  }

  GetRowCount(): number {
    return lib.symbols.wxNotebook_GetRowCount(this.#ptr);
  }

  GetSelection(): number {
    return lib.symbols.wxNotebook_GetSelection(this.#ptr);
  }

  HitTest(x: number, y: number, flags: Deno.PointerValue): number {
    return lib.symbols.wxNotebook_HitTest(this.#ptr, x, y, flags);
  }

  InsertPage(nPage: number, pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxNotebook_InsertPage(this.#ptr, nPage, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(nPage: number): boolean {
    return (lib.symbols.wxNotebook_RemovePage(this.#ptr, nPage) as number) !== 0;
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxNotebook_SetImageList(this.#ptr, imageList);
  }

  SetPadding(width: number, height: number): void {
    lib.symbols.wxNotebook_SetPadding(this.#ptr, width, height);
  }

  SetPageImage(nPage: number, nImage: number): boolean {
    return (lib.symbols.wxNotebook_SetPageImage(this.#ptr, nPage, nImage) as number) !== 0;
  }

  SetPageSize(width: number, height: number): void {
    lib.symbols.wxNotebook_SetPageSize(this.#ptr, width, height);
  }

  SetPageText(nPage: number, strText: Deno.PointerValue): boolean {
    return (lib.symbols.wxNotebook_SetPageText(this.#ptr, nPage, strText) as number) !== 0;
  }

  SetSelection(nPage: number): number {
    return lib.symbols.wxNotebook_SetSelection(this.#ptr, nPage);
  }

}
