// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxOutputStream {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  Delete(): void {
    lib.symbols.wxOutputStream_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  LastWrite(): number {
    return lib.symbols.wxOutputStream_LastWrite(this.#ptr);
  }

  PutC(character: number): void {
    lib.symbols.wxOutputStream_PutC(this.#ptr, character);
  }

  Seek(pos: number, mode: number): number {
    return lib.symbols.wxOutputStream_Seek(this.#ptr, pos, mode);
  }

  Sync(): void {
    lib.symbols.wxOutputStream_Sync(this.#ptr);
  }

  Tell(): number {
    return lib.symbols.wxOutputStream_Tell(this.#ptr);
  }

  Write(buffer: Deno.PointerValue, size: number): void {
    lib.symbols.wxOutputStream_Write(this.#ptr, buffer, size);
  }

}
