// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxStreamBase } from "./wxStreamBase_gen.ts";

export class wxOutputStream extends wxStreamBase {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  Delete(): void {
    lib.symbols.wxOutputStream_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  LastWrite(): number {
    return lib.symbols.wxOutputStream_LastWrite(this._ptr);
  }

  PutC(character: number): void {
    lib.symbols.wxOutputStream_PutC(this._ptr, character);
  }

  Seek(pos: number, mode: number): number {
    return lib.symbols.wxOutputStream_Seek(this._ptr, pos, mode);
  }

  Sync(): void {
    lib.symbols.wxOutputStream_Sync(this._ptr);
  }

  Tell(): number {
    return lib.symbols.wxOutputStream_Tell(this._ptr);
  }

  Write(buffer: Deno.PointerValue, size: number): void {
    lib.symbols.wxOutputStream_Write(this._ptr, buffer, size);
  }

}
