// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxWindow } from "./wxWindow_gen.ts";

export class wxPanel extends wxWindow {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxPanel | null {
    const rawPtr = lib.symbols.wxPanel_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxPanel(rawPtr);
  }

  InitDialog(): void {
    lib.symbols.wxPanel_InitDialog(this._ptr);
  }

  SetFocus(): void {
    lib.symbols.wxPanel_SetFocus(this._ptr);
  }

  SetFocusIgnoringChildren(): void {
    lib.symbols.wxPanel_SetFocusIgnoringChildren(this._ptr);
  }

}
