// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPageSetupDialog {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, data: Deno.PointerValue): wxPageSetupDialog | null {
    const rawPtr = lib.symbols.wxPageSetupDialog_Create(parent, data);
    if (rawPtr === null) return null;
    return new wxPageSetupDialog(rawPtr);
  }

  GetPageSetupData(ref: Deno.PointerValue): void {
    lib.symbols.wxPageSetupDialog_GetPageSetupData(this.#ptr, ref);
  }

  ShowModal(): number {
    return lib.symbols.wxPageSetupDialog_ShowModal(this.#ptr);
  }

}
