// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPaletteChangedEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetChangedWindow(): Deno.PointerValue {
    return lib.symbols.wxPaletteChangedEvent_GetChangedWindow(this.#ptr);
  }

  SetChangedWindow(win: Deno.PointerValue): void {
    lib.symbols.wxPaletteChangedEvent_SetChangedWindow(this.#ptr, win);
  }

}
