// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPGProperty {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetLabel(): Deno.PointerValue {
    return lib.symbols.wxPGProperty_GetLabel(this.#ptr);
  }

  GetName(): Deno.PointerValue {
    return lib.symbols.wxPGProperty_GetName(this.#ptr);
  }

  GetValueAsString(): Deno.PointerValue {
    return lib.symbols.wxPGProperty_GetValueAsString(this.#ptr);
  }

  GetValueType(): Deno.PointerValue {
    return lib.symbols.wxPGProperty_GetValueType(this.#ptr);
  }

  SetHelpString(helpString: Deno.PointerValue): void {
    lib.symbols.wxPGProperty_SetHelpString(this.#ptr, helpString);
  }

}
