// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPostScriptPrintNativeData {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxPostScriptPrintNativeData | null {
    const rawPtr = lib.symbols.wxPostScriptPrintNativeData_Create();
    if (rawPtr === null) return null;
    return new wxPostScriptPrintNativeData(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxPostScriptPrintNativeData_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
