// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPoint {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(xx: number, yy: number): wxPoint | null {
    const rawPtr = lib.symbols.wxPoint_Create(xx, yy);
    if (rawPtr === null) return null;
    return new wxPoint(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxPoint_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetX(): number {
    return lib.symbols.wxPoint_GetX(this._ptr);
  }

  GetY(): number {
    return lib.symbols.wxPoint_GetY(this._ptr);
  }

  SetX(width: number): void {
    lib.symbols.wxPoint_SetX(this._ptr, width);
  }

  SetY(height: number): void {
    lib.symbols.wxPoint_SetY(this._ptr, height);
  }

}
