// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxEvtHandler } from "./wxEvtHandler_gen.ts";

export class wxProcess extends wxEvtHandler {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static CreateDefault(parent: Deno.PointerValue, id: number): wxProcess | null {
    const rawPtr = lib.symbols.wxProcess_CreateDefault(parent, id);
    if (rawPtr === null) return null;
    return new wxProcess(rawPtr);
  }

  static CreateRedirect(parent: Deno.PointerValue, redirect: boolean): wxProcess | null {
    const rawPtr = lib.symbols.wxProcess_CreateRedirect(parent, redirect ? 1 : 0);
    if (rawPtr === null) return null;
    return new wxProcess(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxProcess_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  CloseOutput(): void {
    lib.symbols.wxProcess_CloseOutput(this._ptr);
  }

  Detach(): void {
    lib.symbols.wxProcess_Detach(this._ptr);
  }

  GetErrorStream(): Deno.PointerValue {
    return lib.symbols.wxProcess_GetErrorStream(this._ptr);
  }

  GetInputStream(): Deno.PointerValue {
    return lib.symbols.wxProcess_GetInputStream(this._ptr);
  }

  GetOutputStream(): Deno.PointerValue {
    return lib.symbols.wxProcess_GetOutputStream(this._ptr);
  }

  IsRedirected(): boolean {
    return (lib.symbols.wxProcess_IsRedirected(this._ptr) as number) !== 0;
  }

  Redirect(): void {
    lib.symbols.wxProcess_Redirect(this._ptr);
  }

}
