// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPropertyGridManager {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxPropertyGridManager | null {
    const rawPtr = lib.symbols.wxPropertyGridManager_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxPropertyGridManager(rawPtr);
  }

  AddPage(label: Deno.PointerValue, bmp: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_AddPage(this.#ptr, label, bmp);
  }

  InsertPage(index: number, label: Deno.PointerValue, bmp: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_InsertPage(this.#ptr, index, label, bmp);
  }

  RemovePage(page: number): boolean {
    return (lib.symbols.wxPropertyGridManager_RemovePage(this.#ptr, page) as number) !== 0;
  }

  ClearPage(page: number): void {
    lib.symbols.wxPropertyGridManager_ClearPage(this.#ptr, page);
  }

  GetPageCount(): number {
    return lib.symbols.wxPropertyGridManager_GetPageCount(this.#ptr);
  }

  GetPage(index: number): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_GetPage(this.#ptr, index);
  }

  GetPageByName(name: Deno.PointerValue): number {
    return lib.symbols.wxPropertyGridManager_GetPageByName(this.#ptr, name);
  }

  GetPageName(index: number): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_GetPageName(this.#ptr, index);
  }

  GetSelectedPage(): number {
    return lib.symbols.wxPropertyGridManager_GetSelectedPage(this.#ptr);
  }

  SelectPage(index: number): void {
    lib.symbols.wxPropertyGridManager_SelectPage(this.#ptr, index);
  }

  SelectPageByLabel(label: Deno.PointerValue): void {
    lib.symbols.wxPropertyGridManager_SelectPageByLabel(this.#ptr, label);
  }

  GetGrid(): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_GetGrid(this.#ptr);
  }

  GetCurrentPage(): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_GetCurrentPage(this.#ptr);
  }

  GetToolBar(): Deno.PointerValue {
    return lib.symbols.wxPropertyGridManager_GetToolBar(this.#ptr);
  }

  SetDescBoxHeight(descBoxHeight: number, refresh: boolean): void {
    lib.symbols.wxPropertyGridManager_SetDescBoxHeight(this.#ptr, descBoxHeight, refresh ? 1 : 0);
  }

  GetDescBoxHeight(): number {
    return lib.symbols.wxPropertyGridManager_GetDescBoxHeight(this.#ptr);
  }

  ShowHeader(show: boolean): void {
    lib.symbols.wxPropertyGridManager_ShowHeader(this.#ptr, show ? 1 : 0);
  }

  IsAnyModified(): boolean {
    return (lib.symbols.wxPropertyGridManager_IsAnyModified(this.#ptr) as number) !== 0;
  }

  IsPageModified(index: bigint): boolean {
    return (lib.symbols.wxPropertyGridManager_IsPageModified(this.#ptr, index) as number) !== 0;
  }

  Clear(): void {
    lib.symbols.wxPropertyGridManager_Clear(this.#ptr);
  }

}
