// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxPGProperty } from "./wxPGProperty_gen.ts";

export class wxPropertyCategory extends wxPGProperty {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(label: Deno.PointerValue): wxPropertyCategory | null {
    const rawPtr = lib.symbols.wxPropertyCategory_Create(label);
    if (rawPtr === null) return null;
    return new wxPropertyCategory(rawPtr);
  }

}
