// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPrintDialogData {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static CreateDefault(): wxPrintDialogData | null {
    const rawPtr = lib.symbols.wxPrintDialogData_CreateDefault();
    if (rawPtr === null) return null;
    return new wxPrintDialogData(rawPtr);
  }

  static CreateFromData(printData: Deno.PointerValue): wxPrintDialogData | null {
    const rawPtr = lib.symbols.wxPrintDialogData_CreateFromData(printData);
    if (rawPtr === null) return null;
    return new wxPrintDialogData(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxPrintDialogData_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Assign(data: Deno.PointerValue): void {
    lib.symbols.wxPrintDialogData_Assign(this.#ptr, data);
  }

  AssignData(data: Deno.PointerValue): void {
    lib.symbols.wxPrintDialogData_AssignData(this.#ptr, data);
  }

  EnableHelp(flag: boolean): void {
    lib.symbols.wxPrintDialogData_EnableHelp(this.#ptr, flag ? 1 : 0);
  }

  EnablePageNumbers(flag: boolean): void {
    lib.symbols.wxPrintDialogData_EnablePageNumbers(this.#ptr, flag ? 1 : 0);
  }

  EnablePrintToFile(flag: boolean): void {
    lib.symbols.wxPrintDialogData_EnablePrintToFile(this.#ptr, flag ? 1 : 0);
  }

  EnableSelection(flag: boolean): void {
    lib.symbols.wxPrintDialogData_EnableSelection(this.#ptr, flag ? 1 : 0);
  }

  GetAllPages(): number {
    return lib.symbols.wxPrintDialogData_GetAllPages(this.#ptr);
  }

  GetCollate(): boolean {
    return (lib.symbols.wxPrintDialogData_GetCollate(this.#ptr) as number) !== 0;
  }

  GetEnableHelp(): boolean {
    return (lib.symbols.wxPrintDialogData_GetEnableHelp(this.#ptr) as number) !== 0;
  }

  GetEnablePageNumbers(): boolean {
    return (lib.symbols.wxPrintDialogData_GetEnablePageNumbers(this.#ptr) as number) !== 0;
  }

  GetEnablePrintToFile(): boolean {
    return (lib.symbols.wxPrintDialogData_GetEnablePrintToFile(this.#ptr) as number) !== 0;
  }

  GetEnableSelection(): boolean {
    return (lib.symbols.wxPrintDialogData_GetEnableSelection(this.#ptr) as number) !== 0;
  }

  GetFromPage(): number {
    return lib.symbols.wxPrintDialogData_GetFromPage(this.#ptr);
  }

  GetMaxPage(): number {
    return lib.symbols.wxPrintDialogData_GetMaxPage(this.#ptr);
  }

  GetMinPage(): number {
    return lib.symbols.wxPrintDialogData_GetMinPage(this.#ptr);
  }

  GetNoCopies(): number {
    return lib.symbols.wxPrintDialogData_GetNoCopies(this.#ptr);
  }

  GetPrintData(ref: Deno.PointerValue): void {
    lib.symbols.wxPrintDialogData_GetPrintData(this.#ptr, ref);
  }

  GetPrintToFile(): boolean {
    return (lib.symbols.wxPrintDialogData_GetPrintToFile(this.#ptr) as number) !== 0;
  }

  GetSelection(): boolean {
    return (lib.symbols.wxPrintDialogData_GetSelection(this.#ptr) as number) !== 0;
  }

  GetToPage(): number {
    return lib.symbols.wxPrintDialogData_GetToPage(this.#ptr);
  }

  SetAllPages(flag: boolean): void {
    lib.symbols.wxPrintDialogData_SetAllPages(this.#ptr, flag ? 1 : 0);
  }

  SetCollate(flag: boolean): void {
    lib.symbols.wxPrintDialogData_SetCollate(this.#ptr, flag ? 1 : 0);
  }

  SetFromPage(value: number): void {
    lib.symbols.wxPrintDialogData_SetFromPage(this.#ptr, value);
  }

  SetMaxPage(value: number): void {
    lib.symbols.wxPrintDialogData_SetMaxPage(this.#ptr, value);
  }

  SetMinPage(value: number): void {
    lib.symbols.wxPrintDialogData_SetMinPage(this.#ptr, value);
  }

  SetNoCopies(value: number): void {
    lib.symbols.wxPrintDialogData_SetNoCopies(this.#ptr, value);
  }

  SetPrintData(printData: Deno.PointerValue): void {
    lib.symbols.wxPrintDialogData_SetPrintData(this.#ptr, printData);
  }

  SetPrintToFile(flag: boolean): void {
    lib.symbols.wxPrintDialogData_SetPrintToFile(this.#ptr, flag ? 1 : 0);
  }

  SetSelection(flag: boolean): void {
    lib.symbols.wxPrintDialogData_SetSelection(this.#ptr, flag ? 1 : 0);
  }

  SetToPage(value: number): void {
    lib.symbols.wxPrintDialogData_SetToPage(this.#ptr, value);
  }

}
