// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPrintDialog {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, data: Deno.PointerValue): wxPrintDialog | null {
    const rawPtr = lib.symbols.wxPrintDialog_Create(parent, data);
    if (rawPtr === null) return null;
    return new wxPrintDialog(rawPtr);
  }

  GetPrintDC(): Deno.PointerValue {
    return lib.symbols.wxPrintDialog_GetPrintDC(this.#ptr);
  }

  GetPrintData(ref: Deno.PointerValue): void {
    lib.symbols.wxPrintDialog_GetPrintData(this.#ptr, ref);
  }

  GetPrintDialogData(): Deno.PointerValue {
    return lib.symbols.wxPrintDialog_GetPrintDialogData(this.#ptr);
  }

}
