// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPrinter {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(data: Deno.PointerValue): wxPrinter | null {
    const rawPtr = lib.symbols.wxPrinter_Create(data);
    if (rawPtr === null) return null;
    return new wxPrinter(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxPrinter_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  CreateAbortWindow(parent: Deno.PointerValue, printout: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxPrinter_CreateAbortWindow(this.#ptr, parent, printout);
  }

  GetAbort(): boolean {
    return (lib.symbols.wxPrinter_GetAbort(this.#ptr) as number) !== 0;
  }

  GetLastError(): number {
    return lib.symbols.wxPrinter_GetLastError(this.#ptr);
  }

  GetPrintDialogData(ref: Deno.PointerValue): void {
    lib.symbols.wxPrinter_GetPrintDialogData(this.#ptr, ref);
  }

  Print(parent: Deno.PointerValue, printout: Deno.PointerValue, prompt: boolean): boolean {
    return (lib.symbols.wxPrinter_Print(this.#ptr, parent, printout, prompt ? 1 : 0) as number) !== 0;
  }

  PrintDialog(parent: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxPrinter_PrintDialog(this.#ptr, parent);
  }

  ReportError(parent: Deno.PointerValue, printout: Deno.PointerValue, message: Deno.PointerValue): void {
    lib.symbols.wxPrinter_ReportError(this.#ptr, parent, printout, message);
  }

  Setup(parent: Deno.PointerValue): boolean {
    return (lib.symbols.wxPrinter_Setup(this.#ptr, parent) as number) !== 0;
  }

}
