// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxPrintPreview {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static CreateFromData(printout: Deno.PointerValue, printoutForPrinting: Deno.PointerValue, data: Deno.PointerValue): wxPrintPreview | null {
    const rawPtr = lib.symbols.wxPrintPreview_CreateFromData(printout, printoutForPrinting, data);
    if (rawPtr === null) return null;
    return new wxPrintPreview(rawPtr);
  }

  static CreateFromDialogData(printout: Deno.PointerValue, printoutForPrinting: Deno.PointerValue, data: Deno.PointerValue): wxPrintPreview | null {
    const rawPtr = lib.symbols.wxPrintPreview_CreateFromDialogData(printout, printoutForPrinting, data);
    if (rawPtr === null) return null;
    return new wxPrintPreview(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxPrintPreview_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  DetermineScaling(): void {
    lib.symbols.wxPrintPreview_DetermineScaling(this.#ptr);
  }

  DrawBlankPage(canvas: Deno.PointerValue, dc: Deno.PointerValue): boolean {
    return (lib.symbols.wxPrintPreview_DrawBlankPage(this.#ptr, canvas, dc) as number) !== 0;
  }

  GetCanvas(): Deno.PointerValue {
    return lib.symbols.wxPrintPreview_GetCanvas(this.#ptr);
  }

  GetCurrentPage(): number {
    return lib.symbols.wxPrintPreview_GetCurrentPage(this.#ptr);
  }

  GetFrame(): Deno.PointerValue {
    return lib.symbols.wxPrintPreview_GetFrame(this.#ptr);
  }

  GetMaxPage(): number {
    return lib.symbols.wxPrintPreview_GetMaxPage(this.#ptr);
  }

  GetMinPage(): number {
    return lib.symbols.wxPrintPreview_GetMinPage(this.#ptr);
  }

  GetPrintDialogData(ref: Deno.PointerValue): void {
    lib.symbols.wxPrintPreview_GetPrintDialogData(this.#ptr, ref);
  }

  GetPrintout(): Deno.PointerValue {
    return lib.symbols.wxPrintPreview_GetPrintout(this.#ptr);
  }

  GetPrintoutForPrinting(): Deno.PointerValue {
    return lib.symbols.wxPrintPreview_GetPrintoutForPrinting(this.#ptr);
  }

  GetZoom(): number {
    return lib.symbols.wxPrintPreview_GetZoom(this.#ptr);
  }

  IsOk(): boolean {
    return (lib.symbols.wxPrintPreview_IsOk(this.#ptr) as number) !== 0;
  }

  PaintPage(canvas: Deno.PointerValue, dc: Deno.PointerValue): boolean {
    return (lib.symbols.wxPrintPreview_PaintPage(this.#ptr, canvas, dc) as number) !== 0;
  }

  Print(interactive: boolean): boolean {
    return (lib.symbols.wxPrintPreview_Print(this.#ptr, interactive ? 1 : 0) as number) !== 0;
  }

  RenderPage(pageNum: number): boolean {
    return (lib.symbols.wxPrintPreview_RenderPage(this.#ptr, pageNum) as number) !== 0;
  }

  SetCanvas(canvas: Deno.PointerValue): void {
    lib.symbols.wxPrintPreview_SetCanvas(this.#ptr, canvas);
  }

  SetCurrentPage(pageNum: number): boolean {
    return (lib.symbols.wxPrintPreview_SetCurrentPage(this.#ptr, pageNum) as number) !== 0;
  }

  SetFrame(frame: Deno.PointerValue): void {
    lib.symbols.wxPrintPreview_SetFrame(this.#ptr, frame);
  }

  SetOk(isOk: boolean): void {
    lib.symbols.wxPrintPreview_SetOk(this.#ptr, isOk ? 1 : 0);
  }

  SetPrintout(printout: Deno.PointerValue): void {
    lib.symbols.wxPrintPreview_SetPrintout(this.#ptr, printout);
  }

  SetZoom(percent: number): void {
    lib.symbols.wxPrintPreview_SetZoom(this.#ptr, percent);
  }

}
