// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxEvent } from "./wxEvent_gen.ts";

export class wxQueryLayoutInfoEvent extends wxEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(id: number): wxQueryLayoutInfoEvent | null {
    const rawPtr = lib.symbols.wxQueryLayoutInfoEvent_Create(id);
    if (rawPtr === null) return null;
    return new wxQueryLayoutInfoEvent(rawPtr);
  }

  GetAlignment(): number {
    return lib.symbols.wxQueryLayoutInfoEvent_GetAlignment(this._ptr);
  }

  GetFlags(): number {
    return lib.symbols.wxQueryLayoutInfoEvent_GetFlags(this._ptr);
  }

  GetOrientation(): number {
    return lib.symbols.wxQueryLayoutInfoEvent_GetOrientation(this._ptr);
  }

  GetRequestedLength(): number {
    return lib.symbols.wxQueryLayoutInfoEvent_GetRequestedLength(this._ptr);
  }

  GetSize(): Deno.PointerValue {
    return lib.symbols.wxQueryLayoutInfoEvent_GetSize(this._ptr);
  }

  SetAlignment(align: number): void {
    lib.symbols.wxQueryLayoutInfoEvent_SetAlignment(this._ptr, align);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxQueryLayoutInfoEvent_SetFlags(this._ptr, flags);
  }

  SetOrientation(orient: number): void {
    lib.symbols.wxQueryLayoutInfoEvent_SetOrientation(this._ptr, orient);
  }

  SetRequestedLength(length: number): void {
    lib.symbols.wxQueryLayoutInfoEvent_SetRequestedLength(this._ptr, length);
  }

  SetSize(width: number, height: number): void {
    lib.symbols.wxQueryLayoutInfoEvent_SetSize(this._ptr, width, height);
  }

}
