// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxPanel } from "./wxPanel_gen.ts";

export class wxRearrangeCtrl extends wxPanel {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, order: Deno.PointerValue, items: Deno.PointerValue, style: number): wxRearrangeCtrl | null {
    const rawPtr = lib.symbols.wxRearrangeCtrl_Create(parent, id, x, y, width, height, order, items, style);
    if (rawPtr === null) return null;
    return new wxRearrangeCtrl(rawPtr);
  }

  GetCurrentOrder(): Deno.PointerValue {
    return lib.symbols.wxRearrangeCtrl_GetCurrentOrder(this._ptr);
  }

  GetList(): Deno.PointerValue {
    return lib.symbols.wxRearrangeCtrl_GetList(this._ptr);
  }

  CanMoveCurrentUp(): boolean {
    return (lib.symbols.wxRearrangeCtrl_CanMoveCurrentUp(this._ptr) as number) !== 0;
  }

  CanMoveCurrentDown(): boolean {
    return (lib.symbols.wxRearrangeCtrl_CanMoveCurrentDown(this._ptr) as number) !== 0;
  }

  MoveCurrentUp(): boolean {
    return (lib.symbols.wxRearrangeCtrl_MoveCurrentUp(this._ptr) as number) !== 0;
  }

  MoveCurrentDown(): boolean {
    return (lib.symbols.wxRearrangeCtrl_MoveCurrentDown(this._ptr) as number) !== 0;
  }

}
