// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxRichTextCtrl {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxRichTextCtrl | null {
    const rawPtr = lib.symbols.wxRichTextCtrl_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxRichTextCtrl(rawPtr);
  }

  GetValue(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetValue(this.#ptr);
  }

  SetValue(value: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_SetValue(this.#ptr, value);
  }

  GetRange(from_: number, toPos: number): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetRange(this.#ptr, from_, toPos);
  }

  GetLineLength(lineNo: number): number {
    return lib.symbols.wxRichTextCtrl_GetLineLength(this.#ptr, lineNo);
  }

  GetLineText(lineNo: number): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetLineText(this.#ptr, lineNo);
  }

  GetNumberOfLines(): number {
    return lib.symbols.wxRichTextCtrl_GetNumberOfLines(this.#ptr);
  }

  IsModified(): boolean {
    return (lib.symbols.wxRichTextCtrl_IsModified(this.#ptr) as number) !== 0;
  }

  MarkDirty(): void {
    lib.symbols.wxRichTextCtrl_MarkDirty(this.#ptr);
  }

  DiscardEdits(): void {
    lib.symbols.wxRichTextCtrl_DiscardEdits(this.#ptr);
  }

  IsEditable(): boolean {
    return (lib.symbols.wxRichTextCtrl_IsEditable(this.#ptr) as number) !== 0;
  }

  SetEditable(editable: boolean): void {
    lib.symbols.wxRichTextCtrl_SetEditable(this.#ptr, editable ? 1 : 0);
  }

  GetSelection(from_: Deno.PointerValue, to: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_GetSelection(this.#ptr, from_, to);
  }

  SetSelection(from_: number, toPos: number): void {
    lib.symbols.wxRichTextCtrl_SetSelection(this.#ptr, from_, toPos);
  }

  SelectAll(): void {
    lib.symbols.wxRichTextCtrl_SelectAll(this.#ptr);
  }

  SelectNone(): void {
    lib.symbols.wxRichTextCtrl_SelectNone(this.#ptr);
  }

  GetStringSelection(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetStringSelection(this.#ptr);
  }

  GetInsertionPoint(): number {
    return lib.symbols.wxRichTextCtrl_GetInsertionPoint(this.#ptr);
  }

  GetLastPosition(): number {
    return lib.symbols.wxRichTextCtrl_GetLastPosition(this.#ptr);
  }

  SetInsertionPoint(pos: number): void {
    lib.symbols.wxRichTextCtrl_SetInsertionPoint(this.#ptr, pos);
  }

  SetInsertionPointEnd(): void {
    lib.symbols.wxRichTextCtrl_SetInsertionPointEnd(this.#ptr);
  }

  WriteText(text: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_WriteText(this.#ptr, text);
  }

  AppendText(text: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_AppendText(this.#ptr, text);
  }

  Clear(): void {
    lib.symbols.wxRichTextCtrl_Clear(this.#ptr);
  }

  Replace(from_: number, toPos: number, value: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_Replace(this.#ptr, from_, toPos, value);
  }

  Remove(from_: number, toPos: number): void {
    lib.symbols.wxRichTextCtrl_Remove(this.#ptr, from_, toPos);
  }

  LoadFile(file: Deno.PointerValue, type_: number): boolean {
    return (lib.symbols.wxRichTextCtrl_LoadFile(this.#ptr, file, type_) as number) !== 0;
  }

  SaveFile(file: Deno.PointerValue, type_: number): boolean {
    return (lib.symbols.wxRichTextCtrl_SaveFile(this.#ptr, file, type_) as number) !== 0;
  }

  GetFilename(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetFilename(this.#ptr);
  }

  SetFilename(filename: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_SetFilename(this.#ptr, filename);
  }

  Undo(): void {
    lib.symbols.wxRichTextCtrl_Undo(this.#ptr);
  }

  Redo(): void {
    lib.symbols.wxRichTextCtrl_Redo(this.#ptr);
  }

  CanUndo(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanUndo(this.#ptr) as number) !== 0;
  }

  CanRedo(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanRedo(this.#ptr) as number) !== 0;
  }

  Copy(): void {
    lib.symbols.wxRichTextCtrl_Copy(this.#ptr);
  }

  Cut(): void {
    lib.symbols.wxRichTextCtrl_Cut(this.#ptr);
  }

  Paste(): void {
    lib.symbols.wxRichTextCtrl_Paste(this.#ptr);
  }

  DeleteSelection(): void {
    lib.symbols.wxRichTextCtrl_DeleteSelection(this.#ptr);
  }

  CanCopy(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanCopy(this.#ptr) as number) !== 0;
  }

  CanCut(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanCut(this.#ptr) as number) !== 0;
  }

  CanPaste(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanPaste(this.#ptr) as number) !== 0;
  }

  CanDeleteSelection(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanDeleteSelection(this.#ptr) as number) !== 0;
  }

  SetStyle(start: number, end: number, style: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetStyle(this.#ptr, start, end, style) as number) !== 0;
  }

  GetStyle(position: number, style: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_GetStyle(this.#ptr, position, style) as number) !== 0;
  }

  SetDefaultStyle(style: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetDefaultStyle(this.#ptr, style) as number) !== 0;
  }

  GetDefaultStyle(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetDefaultStyle(this.#ptr);
  }

  SetFont(font: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetFont(this.#ptr, font) as number) !== 0;
  }

  SetFontStyle(start: number, end: number, font: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetFontStyle(this.#ptr, start, end, font) as number) !== 0;
  }

  XYToPosition(x: number, y: number): number {
    return lib.symbols.wxRichTextCtrl_XYToPosition(this.#ptr, x, y);
  }

  PositionToXY(pos: number, x: Deno.PointerValue, y: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_PositionToXY(this.#ptr, pos, x, y) as number) !== 0;
  }

  ShowPosition(position: number): void {
    lib.symbols.wxRichTextCtrl_ShowPosition(this.#ptr, position);
  }

  SetReadOnly(readOnly: boolean): void {
    lib.symbols.wxRichTextCtrl_SetReadOnly(this.#ptr, readOnly ? 1 : 0);
  }

  IsReadOnly(): boolean {
    return (lib.symbols.wxRichTextCtrl_IsReadOnly(this.#ptr) as number) !== 0;
  }

  LayoutContent(onlyVisibleRect: boolean): boolean {
    return (lib.symbols.wxRichTextCtrl_LayoutContent(this.#ptr, onlyVisibleRect ? 1 : 0) as number) !== 0;
  }

  ForceDelayedLayout(): void {
    lib.symbols.wxRichTextCtrl_ForceDelayedLayout(this.#ptr);
  }

  ScrollIntoView(position: number, keyCode: number): void {
    lib.symbols.wxRichTextCtrl_ScrollIntoView(this.#ptr, position, keyCode);
  }

  BeginBold(): void {
    lib.symbols.wxRichTextCtrl_BeginBold(this.#ptr);
  }

  EndBold(): void {
    lib.symbols.wxRichTextCtrl_EndBold(this.#ptr);
  }

  BeginItalic(): void {
    lib.symbols.wxRichTextCtrl_BeginItalic(this.#ptr);
  }

  EndItalic(): void {
    lib.symbols.wxRichTextCtrl_EndItalic(this.#ptr);
  }

  BeginUnderline(): void {
    lib.symbols.wxRichTextCtrl_BeginUnderline(this.#ptr);
  }

  EndUnderline(): void {
    lib.symbols.wxRichTextCtrl_EndUnderline(this.#ptr);
  }

  BeginFontSize(pointSize: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginFontSize(this.#ptr, pointSize) as number) !== 0;
  }

  EndFontSize(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndFontSize(this.#ptr) as number) !== 0;
  }

  BeginFont(font: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginFont(this.#ptr, font) as number) !== 0;
  }

  EndFont(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndFont(this.#ptr) as number) !== 0;
  }

  BeginTextColour(colour: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginTextColour(this.#ptr, colour) as number) !== 0;
  }

  EndTextColour(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndTextColour(this.#ptr) as number) !== 0;
  }

  BeginAlignment(alignment: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginAlignment(this.#ptr, alignment) as number) !== 0;
  }

  EndAlignment(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndAlignment(this.#ptr) as number) !== 0;
  }

  BeginLeftIndent(leftIndent: number, leftSubIndent: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginLeftIndent(this.#ptr, leftIndent, leftSubIndent) as number) !== 0;
  }

  EndLeftIndent(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndLeftIndent(this.#ptr) as number) !== 0;
  }

  BeginRightIndent(rightIndent: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginRightIndent(this.#ptr, rightIndent) as number) !== 0;
  }

  EndRightIndent(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndRightIndent(this.#ptr) as number) !== 0;
  }

  BeginParagraphSpacing(before: number, after: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginParagraphSpacing(this.#ptr, before, after) as number) !== 0;
  }

  EndParagraphSpacing(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndParagraphSpacing(this.#ptr) as number) !== 0;
  }

  BeginLineSpacing(lineSpacing: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginLineSpacing(this.#ptr, lineSpacing) as number) !== 0;
  }

  EndLineSpacing(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndLineSpacing(this.#ptr) as number) !== 0;
  }

  BeginNumberedBullet(bulletNumber: number, leftIndent: number, leftSubIndent: number, bulletStyle: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginNumberedBullet(this.#ptr, bulletNumber, leftIndent, leftSubIndent, bulletStyle) as number) !== 0;
  }

  EndNumberedBullet(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndNumberedBullet(this.#ptr) as number) !== 0;
  }

  BeginSymbolBullet(symbol: Deno.PointerValue, leftIndent: number, leftSubIndent: number, bulletStyle: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginSymbolBullet(this.#ptr, symbol, leftIndent, leftSubIndent, bulletStyle) as number) !== 0;
  }

  EndSymbolBullet(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndSymbolBullet(this.#ptr) as number) !== 0;
  }

  BeginStandardBullet(bulletName: Deno.PointerValue, leftIndent: number, leftSubIndent: number, bulletStyle: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginStandardBullet(this.#ptr, bulletName, leftIndent, leftSubIndent, bulletStyle) as number) !== 0;
  }

  EndStandardBullet(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndStandardBullet(this.#ptr) as number) !== 0;
  }

  BeginURL(url: Deno.PointerValue, characterStyle: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginURL(this.#ptr, url, characterStyle) as number) !== 0;
  }

  EndURL(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndURL(this.#ptr) as number) !== 0;
  }

  WriteImage(image: Deno.PointerValue, bitmapType: number, textAttr: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_WriteImage(this.#ptr, image, bitmapType, textAttr) as number) !== 0;
  }

  WriteImageFile(filename: Deno.PointerValue, bitmapType: number, textAttr: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_WriteImageFile(this.#ptr, filename, bitmapType, textAttr) as number) !== 0;
  }

  Newline(): boolean {
    return (lib.symbols.wxRichTextCtrl_Newline(this.#ptr) as number) !== 0;
  }

  LineBreak(): boolean {
    return (lib.symbols.wxRichTextCtrl_LineBreak(this.#ptr) as number) !== 0;
  }

}
