// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxRibbonGallery {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxRibbonGallery | null {
    const rawPtr = lib.symbols.wxRibbonGallery_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxRibbonGallery(rawPtr);
  }

  Append(bitmap: Deno.PointerValue, id: number): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_Append(this.#ptr, bitmap, id);
  }

  Append_WithClientData(bitmap: Deno.PointerValue, id: number, clientData: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_Append_WithClientData(this.#ptr, bitmap, id, clientData);
  }

  Clear(): void {
    lib.symbols.wxRibbonGallery_Clear(this.#ptr);
  }

  IsEmpty(): boolean {
    return (lib.symbols.wxRibbonGallery_IsEmpty(this.#ptr) as number) !== 0;
  }

  GetCount(): number {
    return lib.symbols.wxRibbonGallery_GetCount(this.#ptr);
  }

  GetItem(index: number): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_GetItem(this.#ptr, index);
  }

  SetSelection(item: Deno.PointerValue): void {
    lib.symbols.wxRibbonGallery_SetSelection(this.#ptr, item);
  }

  GetSelection(): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_GetSelection(this.#ptr);
  }

  GetHoveredItem(): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_GetHoveredItem(this.#ptr);
  }

  GetActiveItem(): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_GetActiveItem(this.#ptr);
  }

  SetItemClientData(item: Deno.PointerValue, data: Deno.PointerValue): void {
    lib.symbols.wxRibbonGallery_SetItemClientData(this.#ptr, item, data);
  }

  GetItemClientData(item: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_GetItemClientData(this.#ptr, item);
  }

  ScrollLines(lines: number): boolean {
    return (lib.symbols.wxRibbonGallery_ScrollLines(this.#ptr, lines) as number) !== 0;
  }

  ScrollPixels(pixels: number): boolean {
    return (lib.symbols.wxRibbonGallery_ScrollPixels(this.#ptr, pixels) as number) !== 0;
  }

  EnsureVisible(item: Deno.PointerValue): void {
    lib.symbols.wxRibbonGallery_EnsureVisible(this.#ptr, item);
  }

  GetUpButtonState(): number {
    return lib.symbols.wxRibbonGallery_GetUpButtonState(this.#ptr);
  }

  GetDownButtonState(): number {
    return lib.symbols.wxRibbonGallery_GetDownButtonState(this.#ptr);
  }

  GetExtensionButtonState(): number {
    return lib.symbols.wxRibbonGallery_GetExtensionButtonState(this.#ptr);
  }

  IsHovered(): boolean {
    return (lib.symbols.wxRibbonGallery_IsHovered(this.#ptr) as number) !== 0;
  }

  IsSizingContinuous(): boolean {
    return (lib.symbols.wxRibbonGallery_IsSizingContinuous(this.#ptr) as number) !== 0;
  }

  SetArtProvider(art: Deno.PointerValue): void {
    lib.symbols.wxRibbonGallery_SetArtProvider(this.#ptr, art);
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxRibbonGallery_GetArtProvider(this.#ptr);
  }

}
