// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxRibbonPage {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, label: Deno.PointerValue, icon: Deno.PointerValue, style: number): wxRibbonPage | null {
    const rawPtr = lib.symbols.wxRibbonPage_Create(parent, id, label, icon, style);
    if (rawPtr === null) return null;
    return new wxRibbonPage(rawPtr);
  }

  DismissExpandedPanel(): void {
    lib.symbols.wxRibbonPage_DismissExpandedPanel(this.#ptr);
  }

  ScrollLines(lines: number): boolean {
    return (lib.symbols.wxRibbonPage_ScrollLines(this.#ptr, lines) as number) !== 0;
  }

  ScrollPixels(pixels: number): boolean {
    return (lib.symbols.wxRibbonPage_ScrollPixels(this.#ptr, pixels) as number) !== 0;
  }

  GetLabel(): Deno.PointerValue {
    return lib.symbols.wxRibbonPage_GetLabel(this.#ptr);
  }

  Realize(): void {
    lib.symbols.wxRibbonPage_Realize(this.#ptr);
  }

  GetMinSize(): Deno.PointerValue {
    return lib.symbols.wxRibbonPage_GetMinSize(this.#ptr);
  }

  SetArtProvider(art: Deno.PointerValue): void {
    lib.symbols.wxRibbonPage_SetArtProvider(this.#ptr, art);
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxRibbonPage_GetArtProvider(this.#ptr);
  }

}
