// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxRichTextCtrl extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxRichTextCtrl | null {
    const rawPtr = lib.symbols.wxRichTextCtrl_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxRichTextCtrl(rawPtr);
  }

  GetValue(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetValue(this._ptr);
  }

  SetValue(value: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_SetValue(this._ptr, value);
  }

  GetRange(from_: number, toPos: number): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetRange(this._ptr, from_, toPos);
  }

  GetLineLength(lineNo: number): number {
    return lib.symbols.wxRichTextCtrl_GetLineLength(this._ptr, lineNo);
  }

  GetLineText(lineNo: number): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetLineText(this._ptr, lineNo);
  }

  GetNumberOfLines(): number {
    return lib.symbols.wxRichTextCtrl_GetNumberOfLines(this._ptr);
  }

  IsModified(): boolean {
    return (lib.symbols.wxRichTextCtrl_IsModified(this._ptr) as number) !== 0;
  }

  MarkDirty(): void {
    lib.symbols.wxRichTextCtrl_MarkDirty(this._ptr);
  }

  DiscardEdits(): void {
    lib.symbols.wxRichTextCtrl_DiscardEdits(this._ptr);
  }

  IsEditable(): boolean {
    return (lib.symbols.wxRichTextCtrl_IsEditable(this._ptr) as number) !== 0;
  }

  SetEditable(editable: boolean): void {
    lib.symbols.wxRichTextCtrl_SetEditable(this._ptr, editable ? 1 : 0);
  }

  GetSelection(from_: Deno.PointerValue, to: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_GetSelection(this._ptr, from_, to);
  }

  SetSelection(from_: number, toPos: number): void {
    lib.symbols.wxRichTextCtrl_SetSelection(this._ptr, from_, toPos);
  }

  SelectAll(): void {
    lib.symbols.wxRichTextCtrl_SelectAll(this._ptr);
  }

  SelectNone(): void {
    lib.symbols.wxRichTextCtrl_SelectNone(this._ptr);
  }

  GetStringSelection(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetStringSelection(this._ptr);
  }

  GetInsertionPoint(): number {
    return lib.symbols.wxRichTextCtrl_GetInsertionPoint(this._ptr);
  }

  GetLastPosition(): number {
    return lib.symbols.wxRichTextCtrl_GetLastPosition(this._ptr);
  }

  SetInsertionPoint(pos: number): void {
    lib.symbols.wxRichTextCtrl_SetInsertionPoint(this._ptr, pos);
  }

  SetInsertionPointEnd(): void {
    lib.symbols.wxRichTextCtrl_SetInsertionPointEnd(this._ptr);
  }

  WriteText(text: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_WriteText(this._ptr, text);
  }

  AppendText(text: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_AppendText(this._ptr, text);
  }

  Clear(): void {
    lib.symbols.wxRichTextCtrl_Clear(this._ptr);
  }

  Replace(from_: number, toPos: number, value: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_Replace(this._ptr, from_, toPos, value);
  }

  Remove(from_: number, toPos: number): void {
    lib.symbols.wxRichTextCtrl_Remove(this._ptr, from_, toPos);
  }

  LoadFile(file: Deno.PointerValue, type_: number): boolean {
    return (lib.symbols.wxRichTextCtrl_LoadFile(this._ptr, file, type_) as number) !== 0;
  }

  SaveFile(file: Deno.PointerValue, type_: number): boolean {
    return (lib.symbols.wxRichTextCtrl_SaveFile(this._ptr, file, type_) as number) !== 0;
  }

  GetFilename(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetFilename(this._ptr);
  }

  SetFilename(filename: Deno.PointerValue): void {
    lib.symbols.wxRichTextCtrl_SetFilename(this._ptr, filename);
  }

  Undo(): void {
    lib.symbols.wxRichTextCtrl_Undo(this._ptr);
  }

  Redo(): void {
    lib.symbols.wxRichTextCtrl_Redo(this._ptr);
  }

  CanUndo(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanUndo(this._ptr) as number) !== 0;
  }

  CanRedo(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanRedo(this._ptr) as number) !== 0;
  }

  Copy(): void {
    lib.symbols.wxRichTextCtrl_Copy(this._ptr);
  }

  Cut(): void {
    lib.symbols.wxRichTextCtrl_Cut(this._ptr);
  }

  Paste(): void {
    lib.symbols.wxRichTextCtrl_Paste(this._ptr);
  }

  DeleteSelection(): void {
    lib.symbols.wxRichTextCtrl_DeleteSelection(this._ptr);
  }

  CanCopy(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanCopy(this._ptr) as number) !== 0;
  }

  CanCut(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanCut(this._ptr) as number) !== 0;
  }

  CanPaste(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanPaste(this._ptr) as number) !== 0;
  }

  CanDeleteSelection(): boolean {
    return (lib.symbols.wxRichTextCtrl_CanDeleteSelection(this._ptr) as number) !== 0;
  }

  SetStyle(start: number, end: number, style: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetStyle(this._ptr, start, end, style) as number) !== 0;
  }

  GetStyle(position: number, style: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_GetStyle(this._ptr, position, style) as number) !== 0;
  }

  SetDefaultStyle(style: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetDefaultStyle(this._ptr, style) as number) !== 0;
  }

  GetDefaultStyle(): Deno.PointerValue {
    return lib.symbols.wxRichTextCtrl_GetDefaultStyle(this._ptr);
  }

  SetFont(font: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetFont(this._ptr, font) as number) !== 0;
  }

  SetFontStyle(start: number, end: number, font: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_SetFontStyle(this._ptr, start, end, font) as number) !== 0;
  }

  XYToPosition(x: number, y: number): number {
    return lib.symbols.wxRichTextCtrl_XYToPosition(this._ptr, x, y);
  }

  PositionToXY(pos: number, x: Deno.PointerValue, y: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_PositionToXY(this._ptr, pos, x, y) as number) !== 0;
  }

  ShowPosition(position: number): void {
    lib.symbols.wxRichTextCtrl_ShowPosition(this._ptr, position);
  }

  SetReadOnly(readOnly: boolean): void {
    lib.symbols.wxRichTextCtrl_SetReadOnly(this._ptr, readOnly ? 1 : 0);
  }

  IsReadOnly(): boolean {
    return (lib.symbols.wxRichTextCtrl_IsReadOnly(this._ptr) as number) !== 0;
  }

  LayoutContent(onlyVisibleRect: boolean): boolean {
    return (lib.symbols.wxRichTextCtrl_LayoutContent(this._ptr, onlyVisibleRect ? 1 : 0) as number) !== 0;
  }

  ForceDelayedLayout(): void {
    lib.symbols.wxRichTextCtrl_ForceDelayedLayout(this._ptr);
  }

  ScrollIntoView(position: number, keyCode: number): void {
    lib.symbols.wxRichTextCtrl_ScrollIntoView(this._ptr, position, keyCode);
  }

  BeginBold(): void {
    lib.symbols.wxRichTextCtrl_BeginBold(this._ptr);
  }

  EndBold(): void {
    lib.symbols.wxRichTextCtrl_EndBold(this._ptr);
  }

  BeginItalic(): void {
    lib.symbols.wxRichTextCtrl_BeginItalic(this._ptr);
  }

  EndItalic(): void {
    lib.symbols.wxRichTextCtrl_EndItalic(this._ptr);
  }

  BeginUnderline(): void {
    lib.symbols.wxRichTextCtrl_BeginUnderline(this._ptr);
  }

  EndUnderline(): void {
    lib.symbols.wxRichTextCtrl_EndUnderline(this._ptr);
  }

  BeginFontSize(pointSize: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginFontSize(this._ptr, pointSize) as number) !== 0;
  }

  EndFontSize(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndFontSize(this._ptr) as number) !== 0;
  }

  BeginFont(font: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginFont(this._ptr, font) as number) !== 0;
  }

  EndFont(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndFont(this._ptr) as number) !== 0;
  }

  BeginTextColour(colour: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginTextColour(this._ptr, colour) as number) !== 0;
  }

  EndTextColour(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndTextColour(this._ptr) as number) !== 0;
  }

  BeginAlignment(alignment: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginAlignment(this._ptr, alignment) as number) !== 0;
  }

  EndAlignment(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndAlignment(this._ptr) as number) !== 0;
  }

  BeginLeftIndent(leftIndent: number, leftSubIndent: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginLeftIndent(this._ptr, leftIndent, leftSubIndent) as number) !== 0;
  }

  EndLeftIndent(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndLeftIndent(this._ptr) as number) !== 0;
  }

  BeginRightIndent(rightIndent: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginRightIndent(this._ptr, rightIndent) as number) !== 0;
  }

  EndRightIndent(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndRightIndent(this._ptr) as number) !== 0;
  }

  BeginParagraphSpacing(before: number, after: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginParagraphSpacing(this._ptr, before, after) as number) !== 0;
  }

  EndParagraphSpacing(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndParagraphSpacing(this._ptr) as number) !== 0;
  }

  BeginLineSpacing(lineSpacing: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginLineSpacing(this._ptr, lineSpacing) as number) !== 0;
  }

  EndLineSpacing(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndLineSpacing(this._ptr) as number) !== 0;
  }

  BeginNumberedBullet(bulletNumber: number, leftIndent: number, leftSubIndent: number, bulletStyle: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginNumberedBullet(this._ptr, bulletNumber, leftIndent, leftSubIndent, bulletStyle) as number) !== 0;
  }

  EndNumberedBullet(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndNumberedBullet(this._ptr) as number) !== 0;
  }

  BeginSymbolBullet(symbol: Deno.PointerValue, leftIndent: number, leftSubIndent: number, bulletStyle: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginSymbolBullet(this._ptr, symbol, leftIndent, leftSubIndent, bulletStyle) as number) !== 0;
  }

  EndSymbolBullet(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndSymbolBullet(this._ptr) as number) !== 0;
  }

  BeginStandardBullet(bulletName: Deno.PointerValue, leftIndent: number, leftSubIndent: number, bulletStyle: number): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginStandardBullet(this._ptr, bulletName, leftIndent, leftSubIndent, bulletStyle) as number) !== 0;
  }

  EndStandardBullet(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndStandardBullet(this._ptr) as number) !== 0;
  }

  BeginURL(url: Deno.PointerValue, characterStyle: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_BeginURL(this._ptr, url, characterStyle) as number) !== 0;
  }

  EndURL(): boolean {
    return (lib.symbols.wxRichTextCtrl_EndURL(this._ptr) as number) !== 0;
  }

  WriteImage(image: Deno.PointerValue, bitmapType: number, textAttr: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_WriteImage(this._ptr, image, bitmapType, textAttr) as number) !== 0;
  }

  WriteImageFile(filename: Deno.PointerValue, bitmapType: number, textAttr: Deno.PointerValue): boolean {
    return (lib.symbols.wxRichTextCtrl_WriteImageFile(this._ptr, filename, bitmapType, textAttr) as number) !== 0;
  }

  Newline(): boolean {
    return (lib.symbols.wxRichTextCtrl_Newline(this._ptr) as number) !== 0;
  }

  LineBreak(): boolean {
    return (lib.symbols.wxRichTextCtrl_LineBreak(this._ptr) as number) !== 0;
  }

}
