// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxRibbonToolBar {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxRibbonToolBar | null {
    const rawPtr = lib.symbols.wxRibbonToolBar_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxRibbonToolBar(rawPtr);
  }

  AddTool(tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue, kind: number, bitmap_disabled: Deno.PointerValue, client_data: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_AddTool(this.#ptr, tool_id, bitmap, help_string, kind, bitmap_disabled, client_data);
  }

  AddDropdownTool(tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_AddDropdownTool(this.#ptr, tool_id, bitmap, help_string);
  }

  AddHybridTool(tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_AddHybridTool(this.#ptr, tool_id, bitmap, help_string);
  }

  AddToggleTool(tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_AddToggleTool(this.#ptr, tool_id, bitmap, help_string);
  }

  AddSeparator(): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_AddSeparator(this.#ptr);
  }

  InsertTool(pos: bigint, tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue, kind: number, bitmap_disabled: Deno.PointerValue, client_data: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_InsertTool(this.#ptr, pos, tool_id, bitmap, help_string, kind, bitmap_disabled, client_data);
  }

  InsertDropdownTool(pos: bigint, tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_InsertDropdownTool(this.#ptr, pos, tool_id, bitmap, help_string);
  }

  InsertHybridTool(pos: bigint, tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_InsertHybridTool(this.#ptr, pos, tool_id, bitmap, help_string);
  }

  InsertToggleTool(pos: bigint, tool_id: number, bitmap: Deno.PointerValue, help_string: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_InsertToggleTool(this.#ptr, pos, tool_id, bitmap, help_string);
  }

  InsertSeparator(pos: bigint): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_InsertSeparator(this.#ptr, pos);
  }

  ClearTools(): void {
    lib.symbols.wxRibbonToolBar_ClearTools(this.#ptr);
  }

  DeleteTool(tool_id: number): boolean {
    return (lib.symbols.wxRibbonToolBar_DeleteTool(this.#ptr, tool_id) as number) !== 0;
  }

  DeleteToolByPos(pos: bigint): boolean {
    return (lib.symbols.wxRibbonToolBar_DeleteToolByPos(this.#ptr, pos) as number) !== 0;
  }

  FindById(tool_id: number): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_FindById(this.#ptr, tool_id);
  }

  GetToolByPos(pos: bigint): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_GetToolByPos(this.#ptr, pos);
  }

  GetToolByPos_Coords(x: number, y: number): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_GetToolByPos_Coords(this.#ptr, x, y);
  }

  GetToolCount(): bigint {
    return lib.symbols.wxRibbonToolBar_GetToolCount(this.#ptr) as bigint;
  }

  GetToolId(tool: Deno.PointerValue): number {
    return lib.symbols.wxRibbonToolBar_GetToolId(this.#ptr, tool);
  }

  GetActiveTool(): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_GetActiveTool(this.#ptr);
  }

  GetToolPos(tool_id: number): number {
    return lib.symbols.wxRibbonToolBar_GetToolPos(this.#ptr, tool_id);
  }

  GetToolRect(tool_id: number, x: Deno.PointerValue, y: Deno.PointerValue, width: Deno.PointerValue, height: Deno.PointerValue): void {
    lib.symbols.wxRibbonToolBar_GetToolRect(this.#ptr, tool_id, x, y, width, height);
  }

  EnableTool(tool_id: number, enable: boolean): void {
    lib.symbols.wxRibbonToolBar_EnableTool(this.#ptr, tool_id, enable ? 1 : 0);
  }

  GetToolEnabled(tool_id: number): boolean {
    return (lib.symbols.wxRibbonToolBar_GetToolEnabled(this.#ptr, tool_id) as number) !== 0;
  }

  GetToolHelpString(tool_id: number): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_GetToolHelpString(this.#ptr, tool_id);
  }

  SetToolHelpString(tool_id: number, help_string: Deno.PointerValue): void {
    lib.symbols.wxRibbonToolBar_SetToolHelpString(this.#ptr, tool_id, help_string);
  }

  GetToolKind(tool_id: number): number {
    return lib.symbols.wxRibbonToolBar_GetToolKind(this.#ptr, tool_id);
  }

  GetToolState(tool_id: number): boolean {
    return (lib.symbols.wxRibbonToolBar_GetToolState(this.#ptr, tool_id) as number) !== 0;
  }

  SetToolNormalBitmap(tool_id: number, bitmap: Deno.PointerValue): void {
    lib.symbols.wxRibbonToolBar_SetToolNormalBitmap(this.#ptr, tool_id, bitmap);
  }

  SetToolDisabledBitmap(tool_id: number, bitmap: Deno.PointerValue): void {
    lib.symbols.wxRibbonToolBar_SetToolDisabledBitmap(this.#ptr, tool_id, bitmap);
  }

  SetToolClientData(tool_id: number, clientData: Deno.PointerValue): void {
    lib.symbols.wxRibbonToolBar_SetToolClientData(this.#ptr, tool_id, clientData);
  }

  GetToolClientData(tool_id: number): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_GetToolClientData(this.#ptr, tool_id);
  }

  SetRows(nMin: number, nMax: number): void {
    lib.symbols.wxRibbonToolBar_SetRows(this.#ptr, nMin, nMax);
  }

  Realize(): void {
    lib.symbols.wxRibbonToolBar_Realize(this.#ptr);
  }

  SetArtProvider(art: Deno.PointerValue): void {
    lib.symbols.wxRibbonToolBar_SetArtProvider(this.#ptr, art);
  }

  GetArtProvider(): Deno.PointerValue {
    return lib.symbols.wxRibbonToolBar_GetArtProvider(this.#ptr);
  }

}
