// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxSashWindow {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxSashWindow | null {
    const rawPtr = lib.symbols.wxSashWindow_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxSashWindow(rawPtr);
  }

  GetDefaultBorderSize(): number {
    return lib.symbols.wxSashWindow_GetDefaultBorderSize(this.#ptr);
  }

  GetEdgeMargin(edge: number): number {
    return lib.symbols.wxSashWindow_GetEdgeMargin(this.#ptr, edge);
  }

  GetExtraBorderSize(): number {
    return lib.symbols.wxSashWindow_GetExtraBorderSize(this.#ptr);
  }

  GetMaximumSizeX(): number {
    return lib.symbols.wxSashWindow_GetMaximumSizeX(this.#ptr);
  }

  GetMaximumSizeY(): number {
    return lib.symbols.wxSashWindow_GetMaximumSizeY(this.#ptr);
  }

  GetMinimumSizeX(): number {
    return lib.symbols.wxSashWindow_GetMinimumSizeX(this.#ptr);
  }

  GetMinimumSizeY(): number {
    return lib.symbols.wxSashWindow_GetMinimumSizeY(this.#ptr);
  }

  GetSashVisible(edge: number): boolean {
    return (lib.symbols.wxSashWindow_GetSashVisible(this.#ptr, edge) as number) !== 0;
  }

  HasBorder(edge: number): boolean {
    return (lib.symbols.wxSashWindow_HasBorder(this.#ptr, edge) as number) !== 0;
  }

  SetDefaultBorderSize(width: number): void {
    lib.symbols.wxSashWindow_SetDefaultBorderSize(this.#ptr, width);
  }

  SetExtraBorderSize(width: number): void {
    lib.symbols.wxSashWindow_SetExtraBorderSize(this.#ptr, width);
  }

  SetMaximumSizeX(max: number): void {
    lib.symbols.wxSashWindow_SetMaximumSizeX(this.#ptr, max);
  }

  SetMaximumSizeY(max: number): void {
    lib.symbols.wxSashWindow_SetMaximumSizeY(this.#ptr, max);
  }

  SetMinimumSizeX(min: number): void {
    lib.symbols.wxSashWindow_SetMinimumSizeX(this.#ptr, min);
  }

  SetMinimumSizeY(min: number): void {
    lib.symbols.wxSashWindow_SetMinimumSizeY(this.#ptr, min);
  }

  SetSashBorder(edge: number, border: boolean): void {
    lib.symbols.wxSashWindow_SetSashBorder(this.#ptr, edge, border ? 1 : 0);
  }

  SetSashVisible(edge: number, sash: boolean): void {
    lib.symbols.wxSashWindow_SetSashVisible(this.#ptr, edge, sash ? 1 : 0);
  }

}
