// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxWindow } from "./wxWindow_gen.ts";

export class wxSashWindow extends wxWindow {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxSashWindow | null {
    const rawPtr = lib.symbols.wxSashWindow_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxSashWindow(rawPtr);
  }

  GetDefaultBorderSize(): number {
    return lib.symbols.wxSashWindow_GetDefaultBorderSize(this._ptr);
  }

  GetEdgeMargin(edge: number): number {
    return lib.symbols.wxSashWindow_GetEdgeMargin(this._ptr, edge);
  }

  GetExtraBorderSize(): number {
    return lib.symbols.wxSashWindow_GetExtraBorderSize(this._ptr);
  }

  GetMaximumSizeX(): number {
    return lib.symbols.wxSashWindow_GetMaximumSizeX(this._ptr);
  }

  GetMaximumSizeY(): number {
    return lib.symbols.wxSashWindow_GetMaximumSizeY(this._ptr);
  }

  GetMinimumSizeX(): number {
    return lib.symbols.wxSashWindow_GetMinimumSizeX(this._ptr);
  }

  GetMinimumSizeY(): number {
    return lib.symbols.wxSashWindow_GetMinimumSizeY(this._ptr);
  }

  GetSashVisible(edge: number): boolean {
    return (lib.symbols.wxSashWindow_GetSashVisible(this._ptr, edge) as number) !== 0;
  }

  HasBorder(edge: number): boolean {
    return (lib.symbols.wxSashWindow_HasBorder(this._ptr, edge) as number) !== 0;
  }

  SetDefaultBorderSize(width: number): void {
    lib.symbols.wxSashWindow_SetDefaultBorderSize(this._ptr, width);
  }

  SetExtraBorderSize(width: number): void {
    lib.symbols.wxSashWindow_SetExtraBorderSize(this._ptr, width);
  }

  SetMaximumSizeX(max: number): void {
    lib.symbols.wxSashWindow_SetMaximumSizeX(this._ptr, max);
  }

  SetMaximumSizeY(max: number): void {
    lib.symbols.wxSashWindow_SetMaximumSizeY(this._ptr, max);
  }

  SetMinimumSizeX(min: number): void {
    lib.symbols.wxSashWindow_SetMinimumSizeX(this._ptr, min);
  }

  SetMinimumSizeY(min: number): void {
    lib.symbols.wxSashWindow_SetMinimumSizeY(this._ptr, min);
  }

  SetSashBorder(edge: number, border: boolean): void {
    lib.symbols.wxSashWindow_SetSashBorder(this._ptr, edge, border ? 1 : 0);
  }

  SetSashVisible(edge: number, sash: boolean): void {
    lib.symbols.wxSashWindow_SetSashVisible(this._ptr, edge, sash ? 1 : 0);
  }

}
