// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxDC } from "./wxDC_gen.ts";

export class wxScreenDC extends wxDC {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxScreenDC | null {
    const rawPtr = lib.symbols.wxScreenDC_Create();
    if (rawPtr === null) return null;
    return new wxScreenDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxScreenDC_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
