// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxScrollEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetOrientation(): number {
    return lib.symbols.wxScrollEvent_GetOrientation(this.#ptr);
  }

  GetPosition(): number {
    return lib.symbols.wxScrollEvent_GetPosition(this.#ptr);
  }

}
