// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxScrolledWindow {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxScrolledWindow | null {
    const rawPtr = lib.symbols.wxScrolledWindow_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxScrolledWindow(rawPtr);
  }

  AdjustScrollbars(): void {
    lib.symbols.wxScrolledWindow_AdjustScrollbars(this.#ptr);
  }

  CalcScrolledPosition(x: number, y: number, xx: Deno.PointerValue, yy: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_CalcScrolledPosition(this.#ptr, x, y, xx, yy);
  }

  CalcUnscrolledPosition(x: number, y: number, xx: Deno.PointerValue, yy: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_CalcUnscrolledPosition(this.#ptr, x, y, xx, yy);
  }

  EnableScrolling(x_scrolling: boolean, y_scrolling: boolean): void {
    lib.symbols.wxScrolledWindow_EnableScrolling(this.#ptr, x_scrolling ? 1 : 0, y_scrolling ? 1 : 0);
  }

  GetScaleX(): number {
    return lib.symbols.wxScrolledWindow_GetScaleX(this.#ptr);
  }

  GetScaleY(): number {
    return lib.symbols.wxScrolledWindow_GetScaleY(this.#ptr);
  }

  GetScrollPageSize(orient: number): number {
    return lib.symbols.wxScrolledWindow_GetScrollPageSize(this.#ptr, orient);
  }

  GetScrollPixelsPerUnit(x: Deno.PointerValue, y: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_GetScrollPixelsPerUnit(this.#ptr, x, y);
  }

  GetTargetWindow(): Deno.PointerValue {
    return lib.symbols.wxScrolledWindow_GetTargetWindow(this.#ptr);
  }

  GetViewStart(x: Deno.PointerValue, y: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_GetViewStart(this.#ptr, x, y);
  }

  GetVirtualSize(x: Deno.PointerValue, y: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_GetVirtualSize(this.#ptr, x, y);
  }

  OnDraw(dc: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_OnDraw(this.#ptr, dc);
  }

  PrepareDC(dc: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_PrepareDC(this.#ptr, dc);
  }

  Scroll(x_pos: number, y_pos: number): void {
    lib.symbols.wxScrolledWindow_Scroll(this.#ptr, x_pos, y_pos);
  }

  SetScale(xScale: number, yScale: number): void {
    lib.symbols.wxScrolledWindow_SetScale(this.#ptr, xScale, yScale);
  }

  SetScrollPageSize(orient: number, pageSize: number): void {
    lib.symbols.wxScrolledWindow_SetScrollPageSize(this.#ptr, orient, pageSize);
  }

  SetScrollbars(pixelsPerUnitX: number, pixelsPerUnitY: number, noUnitsX: number, noUnitsY: number, xPos: number, yPos: number, noRefresh: boolean): void {
    lib.symbols.wxScrolledWindow_SetScrollbars(this.#ptr, pixelsPerUnitX, pixelsPerUnitY, noUnitsX, noUnitsY, xPos, yPos, noRefresh ? 1 : 0);
  }

  ShowScrollbars(showh: number, showv: number): void {
    lib.symbols.wxScrolledWindow_ShowScrollbars(this.#ptr, showh, showv);
  }

  SetTargetWindow(target: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_SetTargetWindow(this.#ptr, target);
  }

  ViewStart(x: Deno.PointerValue, y: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_ViewStart(this.#ptr, x, y);
  }

  GetScrollLines(orient: number): number {
    return lib.symbols.wxScrolledWindow_GetScrollLines(this.#ptr, orient);
  }

  IsScrollbarShown(orient: number): boolean {
    return (lib.symbols.wxScrolledWindow_IsScrollbarShown(this.#ptr, orient) as number) !== 0;
  }

  DisableKeyboardScrolling(): void {
    lib.symbols.wxScrolledWindow_DisableKeyboardScrolling(this.#ptr);
  }

  GetViewStartPixels(x: Deno.PointerValue, y: Deno.PointerValue): void {
    lib.symbols.wxScrolledWindow_GetViewStartPixels(this.#ptr, x, y);
  }

}
