// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxSearchCtrl extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, value: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxSearchCtrl | null {
    const rawPtr = lib.symbols.wxSearchCtrl_Create(parent, id, value, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxSearchCtrl(rawPtr);
  }

  SetMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxSearchCtrl_SetMenu(this._ptr, menu);
  }

  GetMenu(): Deno.PointerValue {
    return lib.symbols.wxSearchCtrl_GetMenu(this._ptr);
  }

  ShowSearchButton(show: boolean): void {
    lib.symbols.wxSearchCtrl_ShowSearchButton(this._ptr, show ? 1 : 0);
  }

  IsSearchButtonVisible(): boolean {
    return (lib.symbols.wxSearchCtrl_IsSearchButtonVisible(this._ptr) as number) !== 0;
  }

  ShowCancelButton(show: boolean): void {
    lib.symbols.wxSearchCtrl_ShowCancelButton(this._ptr, show ? 1 : 0);
  }

  IsCancelButtonVisible(): boolean {
    return (lib.symbols.wxSearchCtrl_IsCancelButtonVisible(this._ptr) as number) !== 0;
  }

  SetDescriptiveText(text: Deno.PointerValue): void {
    lib.symbols.wxSearchCtrl_SetDescriptiveText(this._ptr, text);
  }

  GetDescriptiveText(): Deno.PointerValue {
    return lib.symbols.wxSearchCtrl_GetDescriptiveText(this._ptr);
  }

}
