// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxSearchCtrl {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, value: Deno.PointerValue, x: number, y: number, width: number, height: number, style: number): wxSearchCtrl | null {
    const rawPtr = lib.symbols.wxSearchCtrl_Create(parent, id, value, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxSearchCtrl(rawPtr);
  }

  SetMenu(menu: Deno.PointerValue): void {
    lib.symbols.wxSearchCtrl_SetMenu(this.#ptr, menu);
  }

  GetMenu(): Deno.PointerValue {
    return lib.symbols.wxSearchCtrl_GetMenu(this.#ptr);
  }

  ShowSearchButton(show: boolean): void {
    lib.symbols.wxSearchCtrl_ShowSearchButton(this.#ptr, show ? 1 : 0);
  }

  IsSearchButtonVisible(): boolean {
    return (lib.symbols.wxSearchCtrl_IsSearchButtonVisible(this.#ptr) as number) !== 0;
  }

  ShowCancelButton(show: boolean): void {
    lib.symbols.wxSearchCtrl_ShowCancelButton(this.#ptr, show ? 1 : 0);
  }

  IsCancelButtonVisible(): boolean {
    return (lib.symbols.wxSearchCtrl_IsCancelButtonVisible(this.#ptr) as number) !== 0;
  }

  SetDescriptiveText(text: Deno.PointerValue): void {
    lib.symbols.wxSearchCtrl_SetDescriptiveText(this.#ptr, text);
  }

  GetDescriptiveText(): Deno.PointerValue {
    return lib.symbols.wxSearchCtrl_GetDescriptiveText(this.#ptr);
  }

}
