// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxHelpProvider } from "./wxHelpProvider_gen.ts";

export class wxSimpleHelpProvider extends wxHelpProvider {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxSimpleHelpProvider | null {
    const rawPtr = lib.symbols.wxSimpleHelpProvider_Create();
    if (rawPtr === null) return null;
    return new wxSimpleHelpProvider(rawPtr);
  }

}
