// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxSize {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(width: number, height: number): wxSize | null {
    const rawPtr = lib.symbols.wxSize_Create(width, height);
    if (rawPtr === null) return null;
    return new wxSize(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxSize_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetHeight(): number {
    return lib.symbols.wxSize_GetHeight(this.#ptr);
  }

  GetWidth(): number {
    return lib.symbols.wxSize_GetWidth(this.#ptr);
  }

  SetHeight(height: number): void {
    lib.symbols.wxSize_SetHeight(this.#ptr, height);
  }

  SetWidth(width: number): void {
    lib.symbols.wxSize_SetWidth(this.#ptr, width);
  }

}
