// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxSingleInstanceChecker {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(pObject: Deno.PointerValue, name: Deno.PointerValue, path: Deno.PointerValue): boolean {
    return (lib.symbols.wxSingleInstanceChecker_Create(pObject, name, path) as number) !== 0;
  }

  static CreateDefault(): wxSingleInstanceChecker | null {
    const rawPtr = lib.symbols.wxSingleInstanceChecker_CreateDefault();
    if (rawPtr === null) return null;
    return new wxSingleInstanceChecker(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxSingleInstanceChecker_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  IsAnotherRunning(): boolean {
    return (lib.symbols.wxSingleInstanceChecker_IsAnotherRunning(this.#ptr) as number) !== 0;
  }

}
