// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxBookCtrlBase } from "./wxBookCtrlBase_gen.ts";

export class wxSimplebook extends wxBookCtrlBase {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxSimplebook | null {
    const rawPtr = lib.symbols.wxSimplebook_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxSimplebook(rawPtr);
  }

  AddPage(pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxSimplebook_AddPage(this._ptr, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  ChangeSelection(nPage: number): number {
    return lib.symbols.wxSimplebook_ChangeSelection(this._ptr, nPage);
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxSimplebook_DeleteAllPages(this._ptr) as number) !== 0;
  }

  DeletePage(nPage: number): boolean {
    return (lib.symbols.wxSimplebook_DeletePage(this._ptr, nPage) as number) !== 0;
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxSimplebook_GetImageList(this._ptr);
  }

  GetPage(nPage: number): Deno.PointerValue {
    return lib.symbols.wxSimplebook_GetPage(this._ptr, nPage);
  }

  GetPageCount(): number {
    return lib.symbols.wxSimplebook_GetPageCount(this._ptr);
  }

  GetPageImage(nPage: number): number {
    return lib.symbols.wxSimplebook_GetPageImage(this._ptr, nPage);
  }

  GetPageText(nPage: number): Deno.PointerValue {
    return lib.symbols.wxSimplebook_GetPageText(this._ptr, nPage);
  }

  GetSelection(): number {
    return lib.symbols.wxSimplebook_GetSelection(this._ptr);
  }

  InsertPage(nPage: number, pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxSimplebook_InsertPage(this._ptr, nPage, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(nPage: number): boolean {
    return (lib.symbols.wxSimplebook_RemovePage(this._ptr, nPage) as number) !== 0;
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxSimplebook_SetImageList(this._ptr, imageList);
  }

  SetPageImage(nPage: number, nImage: number): boolean {
    return (lib.symbols.wxSimplebook_SetPageImage(this._ptr, nPage, nImage) as number) !== 0;
  }

  SetPageText(nPage: number, strText: Deno.PointerValue): boolean {
    return (lib.symbols.wxSimplebook_SetPageText(this._ptr, nPage, strText) as number) !== 0;
  }

  SetSelection(nPage: number): number {
    return lib.symbols.wxSimplebook_SetSelection(this._ptr, nPage);
  }

  ShowNewPage(page: Deno.PointerValue): void {
    lib.symbols.wxSimplebook_ShowNewPage(this._ptr, page);
  }

  SetEffect(effect: number): void {
    lib.symbols.wxSimplebook_SetEffect(this._ptr, effect);
  }

  SetEffectTimeout(timeout: number): void {
    lib.symbols.wxSimplebook_SetEffectTimeout(this._ptr, timeout);
  }

}
