// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxSizerItem {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(width: number, height: number, option: number, flag: number, border: number, userData: Deno.PointerValue): wxSizerItem | null {
    const rawPtr = lib.symbols.wxSizerItem_Create(width, height, option, flag, border, userData);
    if (rawPtr === null) return null;
    return new wxSizerItem(rawPtr);
  }

  static CreateInSizer(sizer: Deno.PointerValue, option: number, flag: number, border: number, userData: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxSizerItem_CreateInSizer(sizer, option, flag, border, userData);
  }

  static CreateInWindow(window: Deno.PointerValue, option: number, flag: number, border: number, userData: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxSizerItem_CreateInWindow(window, option, flag, border, userData);
  }

  Delete(): void {
    lib.symbols.wxSizerItem_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  CalcMin(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_CalcMin(this.#ptr);
  }

  GetBorder(): number {
    return lib.symbols.wxSizerItem_GetBorder(this.#ptr);
  }

  GetFlag(): number {
    return lib.symbols.wxSizerItem_GetFlag(this.#ptr);
  }

  GetMinSize(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetMinSize(this.#ptr);
  }

  GetPosition(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetPosition(this.#ptr);
  }

  GetRatio(): number {
    return lib.symbols.wxSizerItem_GetRatio(this.#ptr);
  }

  GetSize(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetSize(this.#ptr);
  }

  GetSizer(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetSizer(this.#ptr);
  }

  GetUserData(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetUserData(this.#ptr);
  }

  GetWindow(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetWindow(this.#ptr);
  }

  IsSizer(): boolean {
    return (lib.symbols.wxSizerItem_IsSizer(this.#ptr) as number) !== 0;
  }

  IsSpacer(): boolean {
    return (lib.symbols.wxSizerItem_IsSpacer(this.#ptr) as number) !== 0;
  }

  IsWindow(): boolean {
    return (lib.symbols.wxSizerItem_IsWindow(this.#ptr) as number) !== 0;
  }

  SetBorder(border: number): void {
    lib.symbols.wxSizerItem_SetBorder(this.#ptr, border);
  }

  SetDimension(x: number, y: number, width: number, height: number): void {
    lib.symbols.wxSizerItem_SetDimension(this.#ptr, x, y, width, height);
  }

  SetFlag(flag: number): void {
    lib.symbols.wxSizerItem_SetFlag(this.#ptr, flag);
  }

  SetFloatRatio(ratio: number): void {
    lib.symbols.wxSizerItem_SetFloatRatio(this.#ptr, ratio);
  }

  SetInitSize(x: number, y: number): void {
    lib.symbols.wxSizerItem_SetInitSize(this.#ptr, x, y);
  }

  SetRatio(width: number, height: number): void {
    lib.symbols.wxSizerItem_SetRatio(this.#ptr, width, height);
  }

  AssignSizer(sizer: Deno.PointerValue): void {
    lib.symbols.wxSizerItem_AssignSizer(this.#ptr, sizer);
  }

  AssignWindow(window: Deno.PointerValue): void {
    lib.symbols.wxSizerItem_AssignWindow(this.#ptr, window);
  }

  DeleteWindows(): void {
    lib.symbols.wxSizerItem_DeleteWindows(this.#ptr);
  }

  DetachSizer(): void {
    lib.symbols.wxSizerItem_DetachSizer(this.#ptr);
  }

  GetProportion(): number {
    return lib.symbols.wxSizerItem_GetProportion(this.#ptr);
  }

  GetRect(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetRect(this.#ptr);
  }

  GetSpacer(): Deno.PointerValue {
    return lib.symbols.wxSizerItem_GetSpacer(this.#ptr);
  }

  IsShown(): number {
    return lib.symbols.wxSizerItem_IsShown(this.#ptr);
  }

  SetProportion(proportion: number): void {
    lib.symbols.wxSizerItem_SetProportion(this.#ptr, proportion);
  }

  AssignSpacer(width: number, height: number): void {
    lib.symbols.wxSizerItem_AssignSpacer(this.#ptr, width, height);
  }

  Show(show: number): void {
    lib.symbols.wxSizerItem_Show(this.#ptr, show);
  }

}
