// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxSplashScreen {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(bitmap: Deno.PointerValue, splashStyle: number, milliseconds: number, parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxSplashScreen | null {
    const rawPtr = lib.symbols.wxSplashScreen_Create(bitmap, splashStyle, milliseconds, parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxSplashScreen(rawPtr);
  }

  GetSplashStyle(): number {
    return lib.symbols.wxSplashScreen_GetSplashStyle(this.#ptr);
  }

  GetTimeout(): number {
    return lib.symbols.wxSplashScreen_GetTimeout(this.#ptr);
  }

}
