// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxWindow } from "./wxWindow_gen.ts";

export class wxSplitterWindow extends wxWindow {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxSplitterWindow | null {
    const rawPtr = lib.symbols.wxSplitterWindow_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxSplitterWindow(rawPtr);
  }

  GetBorderSize(): number {
    return lib.symbols.wxSplitterWindow_GetBorderSize(this._ptr);
  }

  GetMinimumPaneSize(): number {
    return lib.symbols.wxSplitterWindow_GetMinimumPaneSize(this._ptr);
  }

  GetSashPosition(): number {
    return lib.symbols.wxSplitterWindow_GetSashPosition(this._ptr);
  }

  GetSashSize(): number {
    return lib.symbols.wxSplitterWindow_GetSashSize(this._ptr);
  }

  GetSplitMode(): number {
    return lib.symbols.wxSplitterWindow_GetSplitMode(this._ptr);
  }

  GetWindow1(): Deno.PointerValue {
    return lib.symbols.wxSplitterWindow_GetWindow1(this._ptr);
  }

  GetWindow2(): Deno.PointerValue {
    return lib.symbols.wxSplitterWindow_GetWindow2(this._ptr);
  }

  Initialize(window: Deno.PointerValue): void {
    lib.symbols.wxSplitterWindow_Initialize(this._ptr, window);
  }

  IsSplit(): boolean {
    return (lib.symbols.wxSplitterWindow_IsSplit(this._ptr) as number) !== 0;
  }

  ReplaceWindow(winOld: Deno.PointerValue, winNew: Deno.PointerValue): boolean {
    return (lib.symbols.wxSplitterWindow_ReplaceWindow(this._ptr, winOld, winNew) as number) !== 0;
  }

  SetBorderSize(width: number): void {
    lib.symbols.wxSplitterWindow_SetBorderSize(this._ptr, width);
  }

  SetMinimumPaneSize(min: number): void {
    lib.symbols.wxSplitterWindow_SetMinimumPaneSize(this._ptr, min);
  }

  SetSashPosition(position: number, redraw: boolean): void {
    lib.symbols.wxSplitterWindow_SetSashPosition(this._ptr, position, redraw ? 1 : 0);
  }

  SetSplitMode(mode: number): void {
    lib.symbols.wxSplitterWindow_SetSplitMode(this._ptr, mode);
  }

  SplitHorizontally(window1: Deno.PointerValue, window2: Deno.PointerValue, sashPosition: number): boolean {
    return (lib.symbols.wxSplitterWindow_SplitHorizontally(this._ptr, window1, window2, sashPosition) as number) !== 0;
  }

  SplitVertically(window1: Deno.PointerValue, window2: Deno.PointerValue, sashPosition: number): boolean {
    return (lib.symbols.wxSplitterWindow_SplitVertically(this._ptr, window1, window2, sashPosition) as number) !== 0;
  }

  Unsplit(toRemove: Deno.PointerValue): boolean {
    return (lib.symbols.wxSplitterWindow_Unsplit(this._ptr, toRemove) as number) !== 0;
  }

  GetSashGravity(): number {
    return lib.symbols.wxSplitterWindow_GetSashGravity(this._ptr);
  }

  SetSashGravity(gravity: number): void {
    lib.symbols.wxSplitterWindow_SetSashGravity(this._ptr, gravity);
  }

  UpdateSize(): void {
    lib.symbols.wxSplitterWindow_UpdateSize(this._ptr);
  }

  SetSashInvisible(invisible: boolean): void {
    lib.symbols.wxSplitterWindow_SetSashInvisible(this._ptr, invisible ? 1 : 0);
  }

  IsSashInvisible(): boolean {
    return (lib.symbols.wxSplitterWindow_IsSashInvisible(this._ptr) as number) !== 0;
  }

  GetDefaultSashSize(): number {
    return lib.symbols.wxSplitterWindow_GetDefaultSashSize(this._ptr);
  }

}
