// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxSpinCtrl extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number, minVal: number, maxVal: number, init: number): wxSpinCtrl | null {
    const rawPtr = lib.symbols.wxSpinCtrl_Create(parent, id, text, left, top, width, height, style, minVal, maxVal, init);
    if (rawPtr === null) return null;
    return new wxSpinCtrl(rawPtr);
  }

  GetBase(): number {
    return lib.symbols.wxSpinCtrl_GetBase(this._ptr);
  }

  SetBase(base: number): boolean {
    return (lib.symbols.wxSpinCtrl_SetBase(this._ptr, base) as number) !== 0;
  }

  GetMax(): number {
    return lib.symbols.wxSpinCtrl_GetMax(this._ptr);
  }

  GetMin(): number {
    return lib.symbols.wxSpinCtrl_GetMin(this._ptr);
  }

  GetValue(): number {
    return lib.symbols.wxSpinCtrl_GetValue(this._ptr);
  }

  SetRange(min_val: number, max_val: number): void {
    lib.symbols.wxSpinCtrl_SetRange(this._ptr, min_val, max_val);
  }

  SetValue(val: number): void {
    lib.symbols.wxSpinCtrl_SetValue(this._ptr, val);
  }

}
