// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxStaticLine {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxStaticLine | null {
    const rawPtr = lib.symbols.wxStaticLine_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxStaticLine(rawPtr);
  }

  GetDefaultSize(): number {
    return lib.symbols.wxStaticLine_GetDefaultSize(this.#ptr);
  }

  IsVertical(): boolean {
    return (lib.symbols.wxStaticLine_IsVertical(this.#ptr) as number) !== 0;
  }

}
