// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxBoxSizer } from "./wxBoxSizer_gen.ts";

export class wxStaticBoxSizer extends wxBoxSizer {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(box: Deno.PointerValue, orient: number): wxStaticBoxSizer | null {
    const rawPtr = lib.symbols.wxStaticBoxSizer_Create(box, orient);
    if (rawPtr === null) return null;
    return new wxStaticBoxSizer(rawPtr);
  }

  CalcMin(): Deno.PointerValue {
    return lib.symbols.wxStaticBoxSizer_CalcMin(this._ptr);
  }

  GetStaticBox(): Deno.PointerValue {
    return lib.symbols.wxStaticBoxSizer_GetStaticBox(this._ptr);
  }

  RecalcSizes(): void {
    lib.symbols.wxStaticBoxSizer_RecalcSizes(this._ptr);
  }

}
