// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxStatusBar {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxStatusBar | null {
    const rawPtr = lib.symbols.wxStatusBar_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxStatusBar(rawPtr);
  }

  GetBorderX(): number {
    return lib.symbols.wxStatusBar_GetBorderX(this.#ptr);
  }

  GetBorderY(): number {
    return lib.symbols.wxStatusBar_GetBorderY(this.#ptr);
  }

  GetFieldsCount(): number {
    return lib.symbols.wxStatusBar_GetFieldsCount(this.#ptr);
  }

  GetStatusText(number: number): Deno.PointerValue {
    return lib.symbols.wxStatusBar_GetStatusText(this.#ptr, number);
  }

  SetFieldsCount(number: number, widths: Deno.PointerValue): void {
    lib.symbols.wxStatusBar_SetFieldsCount(this.#ptr, number, widths);
  }

  SetMinHeight(height: number): void {
    lib.symbols.wxStatusBar_SetMinHeight(this.#ptr, height);
  }

  SetStatusText(text: Deno.PointerValue, number: number): void {
    lib.symbols.wxStatusBar_SetStatusText(this.#ptr, text, number);
  }

  SetStatusWidths(count: number, widths: Deno.PointerValue): void {
    lib.symbols.wxStatusBar_SetStatusWidths(this.#ptr, count, widths);
  }

  GetFieldRect(i: number, x: Deno.PointerValue, y: Deno.PointerValue, w: Deno.PointerValue, h: Deno.PointerValue): boolean {
    return (lib.symbols.wxStatusBar_GetFieldRect(this.#ptr, i, x, y, w, h) as number) !== 0;
  }

  SetStatusStyles(n: number, styles: Deno.PointerValue): void {
    lib.symbols.wxStatusBar_SetStatusStyles(this.#ptr, n, styles);
  }

  PushStatusText(text: Deno.PointerValue, field: number): void {
    lib.symbols.wxStatusBar_PushStatusText(this.#ptr, text, field);
  }

  PopStatusText(field: number): void {
    lib.symbols.wxStatusBar_PopStatusText(this.#ptr, field);
  }

  GetStatusWidth(n: number): number {
    return lib.symbols.wxStatusBar_GetStatusWidth(this.#ptr, n);
  }

  GetStatusStyle(n: number): number {
    return lib.symbols.wxStatusBar_GetStatusStyle(this.#ptr, n);
  }

}
