// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxStaticText extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxStaticText | null {
    const rawPtr = lib.symbols.wxStaticText_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxStaticText(rawPtr);
  }

  Wrap(width: number): void {
    lib.symbols.wxStaticText_Wrap(this._ptr, width);
  }

  IsEllipsized(): boolean {
    return (lib.symbols.wxStaticText_IsEllipsized(this._ptr) as number) !== 0;
  }

}
