// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxStaticBitmap {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, bitmap: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxStaticBitmap | null {
    const rawPtr = lib.symbols.wxStaticBitmap_Create(parent, id, bitmap, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxStaticBitmap(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxStaticBitmap_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetBitmap(ref: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_GetBitmap(this.#ptr, ref);
  }

  GetIcon(ref: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_GetIcon(this.#ptr, ref);
  }

  SetBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_SetBitmap(this.#ptr, bitmap);
  }

  SetIcon(icon: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_SetIcon(this.#ptr, icon);
  }

}
