// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxStaticText {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxStaticText | null {
    const rawPtr = lib.symbols.wxStaticText_Create(parent, id, text, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxStaticText(rawPtr);
  }

  Wrap(width: number): void {
    lib.symbols.wxStaticText_Wrap(this.#ptr, width);
  }

  IsEllipsized(): boolean {
    return (lib.symbols.wxStaticText_IsEllipsized(this.#ptr) as number) !== 0;
  }

}
