// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxStopWatch {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxStopWatch | null {
    const rawPtr = lib.symbols.wxStopWatch_Create();
    if (rawPtr === null) return null;
    return new wxStopWatch(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxStopWatch_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  Start(msec: number): void {
    lib.symbols.wxStopWatch_Start(this.#ptr, msec);
  }

  Pause(): void {
    lib.symbols.wxStopWatch_Pause(this.#ptr);
  }

  Resume(): void {
    lib.symbols.wxStopWatch_Resume(this.#ptr);
  }

  Time(): number {
    return lib.symbols.wxStopWatch_Time(this.#ptr);
  }

}
