// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxControl } from "./wxControl_gen.ts";

export class wxStaticBitmap extends wxControl {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, bitmap: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxStaticBitmap | null {
    const rawPtr = lib.symbols.wxStaticBitmap_Create(parent, id, bitmap, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxStaticBitmap(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxStaticBitmap_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetBitmap(ref: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_GetBitmap(this._ptr, ref);
  }

  GetIcon(ref: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_GetIcon(this._ptr, ref);
  }

  SetBitmap(bitmap: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_SetBitmap(this._ptr, bitmap);
  }

  SetIcon(icon: Deno.PointerValue): void {
    lib.symbols.wxStaticBitmap_SetIcon(this._ptr, icon);
  }

}
