// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxTaskBarIcon {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxTaskBarIcon | null {
    const rawPtr = lib.symbols.wxTaskBarIcon_Create();
    if (rawPtr === null) return null;
    return new wxTaskBarIcon(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxTaskBarIcon_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  IsIconInstalled(): boolean {
    return (lib.symbols.wxTaskBarIcon_IsIconInstalled(this.#ptr) as number) !== 0;
  }

  IsOk(): boolean {
    return (lib.symbols.wxTaskBarIcon_IsOk(this.#ptr) as number) !== 0;
  }

  PopupMenu(menu: Deno.PointerValue): boolean {
    return (lib.symbols.wxTaskBarIcon_PopupMenu(this.#ptr, menu) as number) !== 0;
  }

  RemoveIcon(): boolean {
    return (lib.symbols.wxTaskBarIcon_RemoveIcon(this.#ptr) as number) !== 0;
  }

  SetIcon(icon: Deno.PointerValue, text: Deno.PointerValue): boolean {
    return (lib.symbols.wxTaskBarIcon_SetIcon(this.#ptr, icon, text) as number) !== 0;
  }

}
