// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxTimer {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number): wxTimer | null {
    const rawPtr = lib.symbols.wxTimer_Create(parent, id);
    if (rawPtr === null) return null;
    return new wxTimer(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxTimer_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetInterval(): number {
    return lib.symbols.wxTimer_GetInterval(this._ptr);
  }

  IsOneShot(): boolean {
    return (lib.symbols.wxTimer_IsOneShot(this._ptr) as number) !== 0;
  }

  IsRunning(): boolean {
    return (lib.symbols.wxTimer_IsRunning(this._ptr) as number) !== 0;
  }

  Start(interval: number, oneShot: boolean): boolean {
    return (lib.symbols.wxTimer_Start(this._ptr, interval, oneShot ? 1 : 0) as number) !== 0;
  }

  Stop(): void {
    lib.symbols.wxTimer_Stop(this._ptr);
  }

}
