// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxTipWindow {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, text: Deno.PointerValue, maxLength: number): wxTipWindow | null {
    const rawPtr = lib.symbols.wxTipWindow_Create(parent, text, maxLength);
    if (rawPtr === null) return null;
    return new wxTipWindow(rawPtr);
  }

  Close(): void {
    lib.symbols.wxTipWindow_Close(this.#ptr);
  }

  SetBoundingRect(x: number, y: number, width: number, height: number): void {
    lib.symbols.wxTipWindow_SetBoundingRect(this.#ptr, x, y, width, height);
  }

  SetTipWindowPtr(windowPtr: Deno.PointerValue): void {
    lib.symbols.wxTipWindow_SetTipWindowPtr(this.#ptr, windowPtr);
  }

}
