// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxTimePickerCtrl {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxTimePickerCtrl | null {
    const rawPtr = lib.symbols.wxTimePickerCtrl_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxTimePickerCtrl(rawPtr);
  }

  SetValue(dateTime: Deno.PointerValue): void {
    lib.symbols.wxTimePickerCtrl_SetValue(this.#ptr, dateTime);
  }

  GetValue(dateTime: Deno.PointerValue): void {
    lib.symbols.wxTimePickerCtrl_GetValue(this.#ptr, dateTime);
  }

  SetTime(hour: number, min: number, sec: number): void {
    lib.symbols.wxTimePickerCtrl_SetTime(this.#ptr, hour, min, sec);
  }

  GetTime(hour: Deno.PointerValue, min: Deno.PointerValue, sec: Deno.PointerValue): boolean {
    return (lib.symbols.wxTimePickerCtrl_GetTime(this.#ptr, hour, min, sec) as number) !== 0;
  }

}
