// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxBookCtrlBase } from "./wxBookCtrlBase_gen.ts";

export class wxToolbook extends wxBookCtrlBase {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, x: number, y: number, width: number, height: number, style: number): wxToolbook | null {
    const rawPtr = lib.symbols.wxToolbook_Create(parent, id, x, y, width, height, style);
    if (rawPtr === null) return null;
    return new wxToolbook(rawPtr);
  }

  AddPage(pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxToolbook_AddPage(this._ptr, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  AdvanceSelection(bForward: boolean): void {
    lib.symbols.wxToolbook_AdvanceSelection(this._ptr, bForward ? 1 : 0);
  }

  DeleteAllPages(): boolean {
    return (lib.symbols.wxToolbook_DeleteAllPages(this._ptr) as number) !== 0;
  }

  DeletePage(nPage: number): boolean {
    return (lib.symbols.wxToolbook_DeletePage(this._ptr, nPage) as number) !== 0;
  }

  GetImageList(): Deno.PointerValue {
    return lib.symbols.wxToolbook_GetImageList(this._ptr);
  }

  GetPage(nPage: number): Deno.PointerValue {
    return lib.symbols.wxToolbook_GetPage(this._ptr, nPage);
  }

  GetPageCount(): number {
    return lib.symbols.wxToolbook_GetPageCount(this._ptr);
  }

  GetPageImage(nPage: number): number {
    return lib.symbols.wxToolbook_GetPageImage(this._ptr, nPage);
  }

  GetPageText(nPage: number): Deno.PointerValue {
    return lib.symbols.wxToolbook_GetPageText(this._ptr, nPage);
  }

  GetSelection(): number {
    return lib.symbols.wxToolbook_GetSelection(this._ptr);
  }

  GetToolBar(): Deno.PointerValue {
    return lib.symbols.wxToolbook_GetToolBar(this._ptr);
  }

  HitTest(x: number, y: number, flags: Deno.PointerValue): number {
    return lib.symbols.wxToolbook_HitTest(this._ptr, x, y, flags);
  }

  InsertPage(nPage: number, pPage: Deno.PointerValue, strText: Deno.PointerValue, bSelect: boolean, imageId: number): boolean {
    return (lib.symbols.wxToolbook_InsertPage(this._ptr, nPage, pPage, strText, bSelect ? 1 : 0, imageId) as number) !== 0;
  }

  RemovePage(nPage: number): boolean {
    return (lib.symbols.wxToolbook_RemovePage(this._ptr, nPage) as number) !== 0;
  }

  SetImageList(imageList: Deno.PointerValue): void {
    lib.symbols.wxToolbook_SetImageList(this._ptr, imageList);
  }

  SetPageImage(nPage: number, nImage: number): boolean {
    return (lib.symbols.wxToolbook_SetPageImage(this._ptr, nPage, nImage) as number) !== 0;
  }

  SetPageText(nPage: number, strText: Deno.PointerValue): boolean {
    return (lib.symbols.wxToolbook_SetPageText(this._ptr, nPage, strText) as number) !== 0;
  }

  SetSelection(nPage: number): number {
    return lib.symbols.wxToolbook_SetSelection(this._ptr, nPage);
  }

}
