// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxToolBar {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, left: number, top: number, width: number, height: number, style: number): wxToolBar | null {
    const rawPtr = lib.symbols.wxToolBar_Create(parent, id, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxToolBar(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxToolBar_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddControl(ctrl: Deno.PointerValue): boolean {
    return (lib.symbols.wxToolBar_AddControl(this.#ptr, ctrl) as number) !== 0;
  }

  AddSeparator(): void {
    lib.symbols.wxToolBar_AddSeparator(this.#ptr);
  }

  AddTool(toolid: number, label: Deno.PointerValue, bitmap: Deno.PointerValue, bmpDisabled: Deno.PointerValue, kind: number, shortHelp: Deno.PointerValue, longHelp: Deno.PointerValue, data: Deno.PointerValue): void {
    lib.symbols.wxToolBar_AddTool(this.#ptr, toolid, label, bitmap, bmpDisabled, kind, shortHelp, longHelp, data);
  }

  DeleteTool(id: number): boolean {
    return (lib.symbols.wxToolBar_DeleteTool(this.#ptr, id) as number) !== 0;
  }

  DeleteToolByPos(pos: number): boolean {
    return (lib.symbols.wxToolBar_DeleteToolByPos(this.#ptr, pos) as number) !== 0;
  }

  EnableTool(id: number, enable: boolean): void {
    lib.symbols.wxToolBar_EnableTool(this.#ptr, id, enable ? 1 : 0);
  }

  GetMargins(): Deno.PointerValue {
    return lib.symbols.wxToolBar_GetMargins(this.#ptr);
  }

  GetToolBitmapSize(): Deno.PointerValue {
    return lib.symbols.wxToolBar_GetToolBitmapSize(this.#ptr);
  }

  GetToolClientData(id: number): Deno.PointerValue {
    return lib.symbols.wxToolBar_GetToolClientData(this.#ptr, id);
  }

  GetToolEnabled(id: number): boolean {
    return (lib.symbols.wxToolBar_GetToolEnabled(this.#ptr, id) as number) !== 0;
  }

  GetToolLongHelp(id: number): Deno.PointerValue {
    return lib.symbols.wxToolBar_GetToolLongHelp(this.#ptr, id);
  }

  GetToolPacking(): number {
    return lib.symbols.wxToolBar_GetToolPacking(this.#ptr);
  }

  GetToolShortHelp(id: number): Deno.PointerValue {
    return lib.symbols.wxToolBar_GetToolShortHelp(this.#ptr, id);
  }

  GetToolSize(): Deno.PointerValue {
    return lib.symbols.wxToolBar_GetToolSize(this.#ptr);
  }

  GetToolState(id: number): boolean {
    return (lib.symbols.wxToolBar_GetToolState(this.#ptr, id) as number) !== 0;
  }

  InsertControl(pos: number, ctrl: Deno.PointerValue): void {
    lib.symbols.wxToolBar_InsertControl(this.#ptr, pos, ctrl);
  }

  InsertSeparator(pos: number): void {
    lib.symbols.wxToolBar_InsertSeparator(this.#ptr, pos);
  }

  Realize(): boolean {
    return (lib.symbols.wxToolBar_Realize(this.#ptr) as number) !== 0;
  }

  RemoveTool(id: number): void {
    lib.symbols.wxToolBar_RemoveTool(this.#ptr, id);
  }

  SetMargins(x: number, y: number): void {
    lib.symbols.wxToolBar_SetMargins(this.#ptr, x, y);
  }

  SetToolBitmapSize(x: number, y: number): void {
    lib.symbols.wxToolBar_SetToolBitmapSize(this.#ptr, x, y);
  }

  SetToolClientData(id: number, data: Deno.PointerValue): void {
    lib.symbols.wxToolBar_SetToolClientData(this.#ptr, id, data);
  }

  SetToolLongHelp(id: number, str: Deno.PointerValue): void {
    lib.symbols.wxToolBar_SetToolLongHelp(this.#ptr, id, str);
  }

  SetToolPacking(packing: number): void {
    lib.symbols.wxToolBar_SetToolPacking(this.#ptr, packing);
  }

  SetToolSeparation(separation: number): void {
    lib.symbols.wxToolBar_SetToolSeparation(this.#ptr, separation);
  }

  SetToolShortHelp(id: number, str: Deno.PointerValue): void {
    lib.symbols.wxToolBar_SetToolShortHelp(this.#ptr, id, str);
  }

  ToggleTool(id: number, toggle: boolean): void {
    lib.symbols.wxToolBar_ToggleTool(this.#ptr, id, toggle ? 1 : 0);
  }

  AddCheckTool(toolid: number, label: Deno.PointerValue, bitmap: Deno.PointerValue, bmpDisabled: Deno.PointerValue, shortHelp: Deno.PointerValue, longHelp: Deno.PointerValue): void {
    lib.symbols.wxToolBar_AddCheckTool(this.#ptr, toolid, label, bitmap, bmpDisabled, shortHelp, longHelp);
  }

  AddRadioTool(toolid: number, label: Deno.PointerValue, bitmap: Deno.PointerValue, bmpDisabled: Deno.PointerValue, shortHelp: Deno.PointerValue, longHelp: Deno.PointerValue): void {
    lib.symbols.wxToolBar_AddRadioTool(this.#ptr, toolid, label, bitmap, bmpDisabled, shortHelp, longHelp);
  }

  AddStretchableSpace(): Deno.PointerValue {
    return lib.symbols.wxToolBar_AddStretchableSpace(this.#ptr);
  }

  InsertStretchableSpace(pos: bigint): Deno.PointerValue {
    return lib.symbols.wxToolBar_InsertStretchableSpace(this.#ptr, pos);
  }

  InsertTool(pos: bigint, toolid: number, label: Deno.PointerValue, bitmap: Deno.PointerValue, bmpDisabled: Deno.PointerValue, kind: number, shortHelp: Deno.PointerValue, longHelp: Deno.PointerValue): void {
    lib.symbols.wxToolBar_InsertTool(this.#ptr, pos, toolid, label, bitmap, bmpDisabled, kind, shortHelp, longHelp);
  }

  ClearTools(): void {
    lib.symbols.wxToolBar_ClearTools(this.#ptr);
  }

  FindControl(id: number): Deno.PointerValue {
    return lib.symbols.wxToolBar_FindControl(this.#ptr, id);
  }

  FindToolForPosition(x: number, y: number): Deno.PointerValue {
    return lib.symbols.wxToolBar_FindToolForPosition(this.#ptr, x, y);
  }

  FindById(id: number): Deno.PointerValue {
    return lib.symbols.wxToolBar_FindById(this.#ptr, id);
  }

  GetToolPos(id: number): number {
    return lib.symbols.wxToolBar_GetToolPos(this.#ptr, id);
  }

  GetToolSeparation(): number {
    return lib.symbols.wxToolBar_GetToolSeparation(this.#ptr);
  }

  GetToolsCount(): number {
    return lib.symbols.wxToolBar_GetToolsCount(this.#ptr);
  }

  IsVertical(): boolean {
    return (lib.symbols.wxToolBar_IsVertical(this.#ptr) as number) !== 0;
  }

  SetToolNormalBitmap(id: number, bitmap: Deno.PointerValue): void {
    lib.symbols.wxToolBar_SetToolNormalBitmap(this.#ptr, id, bitmap);
  }

  SetToolDisabledBitmap(id: number, bitmap: Deno.PointerValue): void {
    lib.symbols.wxToolBar_SetToolDisabledBitmap(this.#ptr, id, bitmap);
  }

  SetDropdownMenu(id: number, menu: Deno.PointerValue): void {
    lib.symbols.wxToolBar_SetDropdownMenu(this.#ptr, id, menu);
  }

  SetToggle(id: number, toggle: boolean): void {
    lib.symbols.wxToolBar_SetToggle(this.#ptr, id, toggle ? 1 : 0);
  }

}
