// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxTreeListEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetItem(result: Deno.PointerValue): void {
    lib.symbols.wxTreeListEvent_GetItem(this.#ptr, result);
  }

  GetOldCheckedState(): number {
    return lib.symbols.wxTreeListEvent_GetOldCheckedState(this.#ptr);
  }

  GetColumn(): number {
    return lib.symbols.wxTreeListEvent_GetColumn(this.#ptr);
  }

  Veto(): void {
    lib.symbols.wxTreeListEvent_Veto(this.#ptr);
  }

  Allow(): void {
    lib.symbols.wxTreeListEvent_Allow(this.#ptr);
  }

  IsAllowed(): boolean {
    return (lib.symbols.wxTreeListEvent_IsAllowed(this.#ptr) as number) !== 0;
  }

}
