// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxUpdateUIEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  Check(check: boolean): void {
    lib.symbols.wxUpdateUIEvent_Check(this.#ptr, check ? 1 : 0);
  }

  Enable(enable: boolean): void {
    lib.symbols.wxUpdateUIEvent_Enable(this.#ptr, enable ? 1 : 0);
  }

  GetChecked(): boolean {
    return (lib.symbols.wxUpdateUIEvent_GetChecked(this.#ptr) as number) !== 0;
  }

  GetEnabled(): boolean {
    return (lib.symbols.wxUpdateUIEvent_GetEnabled(this.#ptr) as number) !== 0;
  }

  GetSetChecked(): boolean {
    return (lib.symbols.wxUpdateUIEvent_GetSetChecked(this.#ptr) as number) !== 0;
  }

  GetSetEnabled(): boolean {
    return (lib.symbols.wxUpdateUIEvent_GetSetEnabled(this.#ptr) as number) !== 0;
  }

  GetSetText(): boolean {
    return (lib.symbols.wxUpdateUIEvent_GetSetText(this.#ptr) as number) !== 0;
  }

  GetText(): Deno.PointerValue {
    return lib.symbols.wxUpdateUIEvent_GetText(this.#ptr);
  }

  SetText(text: Deno.PointerValue): void {
    lib.symbols.wxUpdateUIEvent_SetText(this.#ptr, text);
  }

}
