// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxValidator {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(): wxValidator | null {
    const rawPtr = lib.symbols.wxValidator_Create();
    if (rawPtr === null) return null;
    return new wxValidator(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxValidator_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetWindow(): Deno.PointerValue {
    return lib.symbols.wxValidator_GetWindow(this.#ptr);
  }

  SuppressBellOnError(doIt: boolean): void {
    lib.symbols.wxValidator_SuppressBellOnError(doIt ? 1 : 0);
  }

  SetWindow(win: Deno.PointerValue): void {
    lib.symbols.wxValidator_SetWindow(this.#ptr, win);
  }

  TransferFromWindow(): boolean {
    return (lib.symbols.wxValidator_TransferFromWindow(this.#ptr) as number) !== 0;
  }

  TransferToWindow(): boolean {
    return (lib.symbols.wxValidator_TransferToWindow(this.#ptr) as number) !== 0;
  }

  Validate(parent: Deno.PointerValue): boolean {
    return (lib.symbols.wxValidator_Validate(this.#ptr, parent) as number) !== 0;
  }

}
