// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxEvtHandler } from "./wxEvtHandler_gen.ts";

export class wxValidator extends wxEvtHandler {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(): wxValidator | null {
    const rawPtr = lib.symbols.wxValidator_Create();
    if (rawPtr === null) return null;
    return new wxValidator(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxValidator_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  GetWindow(): Deno.PointerValue {
    return lib.symbols.wxValidator_GetWindow(this._ptr);
  }

  SuppressBellOnError(doIt: boolean): void {
    lib.symbols.wxValidator_SuppressBellOnError(doIt ? 1 : 0);
  }

  SetWindow(win: Deno.PointerValue): void {
    lib.symbols.wxValidator_SetWindow(this._ptr, win);
  }

  TransferFromWindow(): boolean {
    return (lib.symbols.wxValidator_TransferFromWindow(this._ptr) as number) !== 0;
  }

  TransferToWindow(): boolean {
    return (lib.symbols.wxValidator_TransferToWindow(this._ptr) as number) !== 0;
  }

  Validate(parent: Deno.PointerValue): boolean {
    return (lib.symbols.wxValidator_Validate(this._ptr, parent) as number) !== 0;
  }

}
