// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxWebViewEvent {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  GetURL(): Deno.PointerValue {
    return lib.symbols.wxWebViewEvent_GetURL(this.#ptr);
  }

  GetTarget(): Deno.PointerValue {
    return lib.symbols.wxWebViewEvent_GetTarget(this.#ptr);
  }

  GetNavigationAction(): number {
    return lib.symbols.wxWebViewEvent_GetNavigationAction(this.#ptr);
  }

  GetInt(): number {
    return lib.symbols.wxWebViewEvent_GetInt(this.#ptr);
  }

  GetString(): Deno.PointerValue {
    return lib.symbols.wxWebViewEvent_GetString(this.#ptr);
  }

}
