// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxNotifyEvent } from "./wxNotifyEvent_gen.ts";

export class wxWebViewEvent extends wxNotifyEvent {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  GetURL(): Deno.PointerValue {
    return lib.symbols.wxWebViewEvent_GetURL(this._ptr);
  }

  GetTarget(): Deno.PointerValue {
    return lib.symbols.wxWebViewEvent_GetTarget(this._ptr);
  }

  GetNavigationAction(): number {
    return lib.symbols.wxWebViewEvent_GetNavigationAction(this._ptr);
  }

  GetInt(): number {
    return lib.symbols.wxWebViewEvent_GetInt(this._ptr);
  }

  GetString(): Deno.PointerValue {
    return lib.symbols.wxWebViewEvent_GetString(this._ptr);
  }

}
