// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";
import { wxDialog } from "./wxDialog_gen.ts";

export class wxWizard extends wxDialog {
  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(parent: Deno.PointerValue, id: number, text: Deno.PointerValue, bitmap: Deno.PointerValue, left: number, top: number, width: number, height: number, style: number): wxWizard | null {
    const rawPtr = lib.symbols.wxWizard_Create(parent, id, text, bitmap, left, top, width, height, style);
    if (rawPtr === null) return null;
    return new wxWizard(rawPtr);
  }

  Chain(first: Deno.PointerValue, second: Deno.PointerValue): void {
    lib.symbols.wxWizard_Chain(first, second);
  }

  GetCurrentPage(): Deno.PointerValue {
    return lib.symbols.wxWizard_GetCurrentPage(this._ptr);
  }

  GetPageSize(): Deno.PointerValue {
    return lib.symbols.wxWizard_GetPageSize(this._ptr);
  }

  RunWizard(firstPage: Deno.PointerValue): number {
    return lib.symbols.wxWizard_RunWizard(this._ptr, firstPage);
  }

  SetPageSize(width: number, height: number): void {
    lib.symbols.wxWizard_SetPageSize(this._ptr, width, height);
  }

  GetPageAreaSizer(): Deno.PointerValue {
    return lib.symbols.wxWizard_GetPageAreaSizer(this._ptr);
  }

  SetBorder(border: number): void {
    lib.symbols.wxWizard_SetBorder(this._ptr, border);
  }

  FitToPage(firstPage: Deno.PointerValue): void {
    lib.symbols.wxWizard_FitToPage(this._ptr, firstPage);
  }

  HasNextPage(page: Deno.PointerValue): boolean {
    return (lib.symbols.wxWizard_HasNextPage(this._ptr, page) as number) !== 0;
  }

  HasPrevPage(page: Deno.PointerValue): boolean {
    return (lib.symbols.wxWizard_HasPrevPage(this._ptr, page) as number) !== 0;
  }

  GetBitmap(ref: Deno.PointerValue): void {
    lib.symbols.wxWizard_GetBitmap(this._ptr, ref);
  }

}
