// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxWindowDC {
  readonly #ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this.#ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this.#ptr;
  }

  static Create(win: Deno.PointerValue): wxWindowDC | null {
    const rawPtr = lib.symbols.wxWindowDC_Create(win);
    if (rawPtr === null) return null;
    return new wxWindowDC(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxWindowDC_Delete(this.#ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

}
