// Code generated by kwxgen. DO NOT EDIT.

import { lib } from "./kwx_ffi_gen.ts";

export class wxXmlResource {
  protected readonly _ptr: Deno.PointerValue;

  constructor(ptr: Deno.PointerValue) {
    this._ptr = ptr;
  }

  /** Returns the underlying native pointer. */
  get ptr(): Deno.PointerValue {
    return this._ptr;
  }

  static Create(flags: number): wxXmlResource | null {
    const rawPtr = lib.symbols.wxXmlResource_Create(flags);
    if (rawPtr === null) return null;
    return new wxXmlResource(rawPtr);
  }

  static CreateFromFile(filemask: Deno.PointerValue, flags: number): wxXmlResource | null {
    const rawPtr = lib.symbols.wxXmlResource_CreateFromFile(filemask, flags);
    if (rawPtr === null) return null;
    return new wxXmlResource(rawPtr);
  }

  Delete(): void {
    lib.symbols.wxXmlResource_Delete(this._ptr);
  }

  [Symbol.dispose](): void {
    this.Delete();
  }

  AddHandler(handler: Deno.PointerValue): void {
    lib.symbols.wxXmlResource_AddHandler(this._ptr, handler);
  }

  AddSubclassFactory(factory: Deno.PointerValue): void {
    lib.symbols.wxXmlResource_AddSubclassFactory(this._ptr, factory);
  }

  AttachUnknownControl(control: Deno.PointerValue, parent: Deno.PointerValue): number {
    return lib.symbols.wxXmlResource_AttachUnknownControl(this._ptr, control, parent);
  }

  ClearHandlers(): void {
    lib.symbols.wxXmlResource_ClearHandlers(this._ptr);
  }

  CompareVersion(major: number, minor: number, release: number, revision: number): number {
    return lib.symbols.wxXmlResource_CompareVersion(this._ptr, major, minor, release, revision);
  }

  Get(): Deno.PointerValue {
    return lib.symbols.wxXmlResource_Get();
  }

  GetDomain(): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetDomain(this._ptr);
  }

  GetFlags(): number {
    return lib.symbols.wxXmlResource_GetFlags(this._ptr);
  }

  GetVersion(): number {
    return lib.symbols.wxXmlResource_GetVersion(this._ptr);
  }

  GetXRCID(str_id: Deno.PointerValue, value_if_not_found: number): number {
    return lib.symbols.wxXmlResource_GetXRCID(this._ptr, str_id, value_if_not_found);
  }

  InitAllHandlers(): void {
    lib.symbols.wxXmlResource_InitAllHandlers(this._ptr);
  }

  InsertHandler(handler: Deno.PointerValue): void {
    lib.symbols.wxXmlResource_InsertHandler(this._ptr, handler);
  }

  Load(filemask: Deno.PointerValue): boolean {
    return (lib.symbols.wxXmlResource_Load(this._ptr, filemask) as number) !== 0;
  }

  LoadBitmap(name: Deno.PointerValue, ref: Deno.PointerValue): void {
    lib.symbols.wxXmlResource_LoadBitmap(this._ptr, name, ref);
  }

  LoadDialog(parent: Deno.PointerValue, name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_LoadDialog(this._ptr, parent, name);
  }

  LoadFrame(parent: Deno.PointerValue, name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_LoadFrame(this._ptr, parent, name);
  }

  LoadIcon(name: Deno.PointerValue, ref: Deno.PointerValue): void {
    lib.symbols.wxXmlResource_LoadIcon(this._ptr, name, ref);
  }

  LoadMenu(name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_LoadMenu(this._ptr, name);
  }

  LoadMenuBar(parent: Deno.PointerValue, name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_LoadMenuBar(this._ptr, parent, name);
  }

  LoadPanel(parent: Deno.PointerValue, name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_LoadPanel(this._ptr, parent, name);
  }

  LoadToolBar(parent: Deno.PointerValue, name: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_LoadToolBar(this._ptr, parent, name);
  }

  GetSizer(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetSizer(this._ptr, str_id);
  }

  GetBoxSizer(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetBoxSizer(this._ptr, str_id);
  }

  GetStaticBoxSizer(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetStaticBoxSizer(this._ptr, str_id);
  }

  GetGridSizer(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetGridSizer(this._ptr, str_id);
  }

  GetFlexGridSizer(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetFlexGridSizer(this._ptr, str_id);
  }

  GetBitmapButton(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetBitmapButton(this._ptr, str_id);
  }

  GetButton(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetButton(this._ptr, str_id);
  }

  GetCalendarCtrl(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetCalendarCtrl(this._ptr, str_id);
  }

  GetCheckBox(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetCheckBox(this._ptr, str_id);
  }

  GetCheckListBox(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetCheckListBox(this._ptr, str_id);
  }

  GetChoice(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetChoice(this._ptr, str_id);
  }

  GetComboBox(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetComboBox(this._ptr, str_id);
  }

  GetGauge(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetGauge(this._ptr, str_id);
  }

  GetGrid(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetGrid(this._ptr, str_id);
  }

  GetHtmlWindow(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetHtmlWindow(this._ptr, str_id);
  }

  GetListBox(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetListBox(this._ptr, str_id);
  }

  GetListCtrl(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetListCtrl(this._ptr, str_id);
  }

  GetMDIChildFrame(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetMDIChildFrame(this._ptr, str_id);
  }

  GetMDIParentFrame(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetMDIParentFrame(this._ptr, str_id);
  }

  GetMenu(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetMenu(this._ptr, str_id);
  }

  GetMenuBar(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetMenuBar(this._ptr, str_id);
  }

  GetMenuItem(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetMenuItem(this._ptr, str_id);
  }

  GetNotebook(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetNotebook(this._ptr, str_id);
  }

  GetPanel(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetPanel(this._ptr, str_id);
  }

  GetRadioButton(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetRadioButton(this._ptr, str_id);
  }

  GetRadioBox(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetRadioBox(this._ptr, str_id);
  }

  GetScrollBar(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetScrollBar(this._ptr, str_id);
  }

  GetScrolledWindow(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetScrolledWindow(this._ptr, str_id);
  }

  GetSlider(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetSlider(this._ptr, str_id);
  }

  GetSpinButton(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetSpinButton(this._ptr, str_id);
  }

  GetSpinCtrl(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetSpinCtrl(this._ptr, str_id);
  }

  GetSplitterWindow(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetSplitterWindow(this._ptr, str_id);
  }

  GetStaticBitmap(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetStaticBitmap(this._ptr, str_id);
  }

  GetStaticBox(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetStaticBox(this._ptr, str_id);
  }

  GetStaticLine(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetStaticLine(this._ptr, str_id);
  }

  GetStaticText(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetStaticText(this._ptr, str_id);
  }

  GetTextCtrl(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetTextCtrl(this._ptr, str_id);
  }

  GetTreeCtrl(str_id: Deno.PointerValue): Deno.PointerValue {
    return lib.symbols.wxXmlResource_GetTreeCtrl(this._ptr, str_id);
  }

  Unload(filemask: Deno.PointerValue): boolean {
    return (lib.symbols.wxXmlResource_Unload(this._ptr, filemask) as number) !== 0;
  }

  Set(): Deno.PointerValue {
    return lib.symbols.wxXmlResource_Set(this._ptr, this._ptr);
  }

  SetDomain(domain: Deno.PointerValue): void {
    lib.symbols.wxXmlResource_SetDomain(this._ptr, domain);
  }

  SetFlags(flags: number): void {
    lib.symbols.wxXmlResource_SetFlags(this._ptr, flags);
  }

}
